### ISSUE TITLE
Launch tasks

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#100]
These are things we'll need to do to launch the new header/footer and News theme

### classic themes

- [x] Flip feature flag on w.org to `true`, to enable new header/footer

### trac

- [x] merge https://github.com/WordPress/wordpress.org/pull/50. xref #53
- [x] update templates (Run script in the above PR)

### codex

- [x] Systems need to deploy & clear caches. https://make.wordpress.org/systems/2022/01/13/deploy-clear-caches-for-planet-codex/

### planet

- [x] Systems need to deploy & clear caches. https://make.wordpress.org/systems/2022/01/13/deploy-clear-caches-for-planet-codex/

Post-launch tasks are tracked in #55

**Comment by iandunn** [comment]
@dd32, @ryelle if you think of anything else we'll need to do, please add it above

**Comment by dd32** [comment]
> w.org news: Update the News link in get_menu_url_for_current_page()

Not needed, that's only for making `/news-test/` point to the right place. /news/ will just use the loops below.

> trac: Enable feature flag

No feature flag, just update templates.

> trac: update rest api clients to call /news not /news-test ?

API clients are all accessing `wordpress.org/` and not /news. So no changes needed.

> trac: systems deploys?

No systems needed. If Trac breaks, SVN will still work and re can update templates. (Trac auto-updates to templates when committed to meta.svn)

> rosetta / glotpress

Nothing other than classic themes. There's some code behind the feature flags that can be removed later.

> Planet / Codex

Systems need to deploy & clear caches. Existing request: https://make.wordpress.org/systems/2022/01/13/deploy-clear-caches-for-planet-codex/
No other changes needed, unless reactive fixes are needed.

**Comment by iandunn** [comment]
i updated the list, thanks!

**Comment by iandunn** [comment]
I moved the theme stuff to https://github.com/WordPress/wporg-news-2021/issues/251, so this is done now
