### ISSUE TITLE
GlotPress string references link to Trac

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#108]
https://meta.trac.wordpress.org/changeset/11457 attempted to fix them after the initial import in `r18321-dotorg`, but it doesn't seem to have worked. e.g.:

* https://translate.wordpress.org/projects/meta/wordpress-org/en-au/default/?filters%5Boriginal_id%5D=13110327
* https://translate.wordpress.org/projects/meta/wordpress-org/fr/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=13110319&filters%5Btranslation_id%5D=91843823

See #46

**Comment by ryelle** [comment]
Is the issue here that they _should_ link to trac? I'm seeing the two you linked reference github:

<img width="942" alt="Screen Shot 2022-01-20 at 1 27 19 PM" src="https://user-images.githubusercontent.com/541093/150399297-10d01717-6a5c-4c39-88f9-bf0fecad4eaa.png">

**Comment by iandunn** [comment]
Gah, nevermind, it's working fine, I just forgot to update my sandbox this morning 🤦🏻‍♂️  😆
