### ISSUE TITLE
Rosetta menu font/alignment incorrect

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-mu-plugins#109]
On https://es.wordpress.org/ and other Rosetta sites, post-launch:

<img width="387" alt="Screen Shot 2022-01-24 at 1 56 32 pm" src="https://user-images.githubusercontent.com/7200686/150715135-40ad0746-82d5-4290-8a93-8800a4015415.png">

I'm not sure if that font (and indeed text) is intended to be there or not. If it is, the vertical alignment is out.

**Comment by dd32** [comment]
The vertical alignment of the Text matches that of the logo, it looks like maybe the menu text should be lining up, but isn't? The design mockups seem to vary in the alignment a fair bit.

The font looks to have been an explicit choice too.

**Comment by tellyworth** [comment]
Yeah you're right that the alignment matches the logo (and the font). That's more obvious in a wider viewport:
<img width="584" alt="Screen Shot 2022-01-24 at 2 34 49 pm" src="https://user-images.githubusercontent.com/7200686/150717921-252983f4-8095-40da-a9be-4f6deeac678d.png">

So I think the issues are:

* logo/title vertical alignment doesn't match the menu
* Is the white `|` intended?
* Is the language title intended?

Looking at the code the [language title seems very deliberate](https://github.com/WordPress/wporg-mu-plugins/blob/trunk/mu-plugins/blocks/global-header-footer/header.php#L42-L48). I can't see it in the Figma for a visual comparison, maybe I'm overlooking it.

**Comment by dd32** [comment]
Ah, gotcha, yes see #50

**Comment by tellyworth** [comment]
Oh thanks! In that case yeah it's working as intended, and the alignment looks more-or-less like the [mockups](https://github.com/WordPress/wporg-mu-plugins/issues/50#issuecomment-1004705164). I'll remove the milestone; @beafialho is this safe to close?

**Comment by beafialho** [comment]
This is safe to close 👍
