### ISSUE TITLE
Get WP button inaccessible from 876px - 1152px

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#11]
Below `876px`, the "Get WordPress" button is shown in the mobile menu. Above `1152px`, it's shown in the desktop menu. Between those two breakpoints, though, it seems inaccessible. 

![Screen Shot 2021-10-12 at 10 37 36 AM](https://user-images.githubusercontent.com/484068/137004488-e53845fc-15fd-4289-a3fe-6b8da90f4682.png)

@beafialho, is that intentional, or am I interpreting the mockup wrong?

**Comment by beafialho** [comment]
Sorry, I didn't make that clear in the Figma file. Below `876px`, the menu should look like this:

<img width="1101" alt="Captura de ecrã 2021-10-13, às 10 01 03" src="https://user-images.githubusercontent.com/65220155/137102053-ba190fbe-c388-4f45-8071-70436244af13.png">

**Comment by iandunn** [comment]
I get that it's part of the mobile menu _below_ `876px`, but I'm talking about _above_ `876px`. 

If you look at [the staging site](https://wordpress.org/news-test/) and make your browser `900px`, you'll see that the button can't be accessed in the mobile or desktop menus. It's not until `1152px` that it appears in the desktop menu.

I would think we'd always want it in the desktop menu above `876px`.

**Comment by beafialho** [comment]
That's right, the "Get WordPress" button should always be accessed, either in the mobile or desktop menus. Above `876px` it should be in the desktop menu. I'll correct that in Figma.

**Comment by iandunn** [comment]
Thanks!

**Comment by iandunn** [comment]
The `About` and `Get Involved` items had to be moved to the overflow menu to make room for it.

<img width="917" alt="Screen Shot 2021-10-15 at 7 16 41 AM" src="https://user-images.githubusercontent.com/484068/137502066-5b31fd73-191b-4b70-8d47-8d7c04c6d0bb.png">

**Comment by beafialho** [comment]
👍
