### ISSUE TITLE
Menu Close X not shown in Safari

### ISSUE THREAD

**Issue by dd32** [WordPress/wporg-mu-plugins#110]
As noted by @aurooba on Slack https://wordpress.slack.com/archives/C02QB8GMM/p1642992375174000 

https://user-images.githubusercontent.com/767313/150723404-e7b8b3be-ff4a-4eda-ad80-de20b8d785fb.MP4

It looks like safari isn't happy with rendering the close button outside of the menu when the menu is `overflow: auto`. Putting together a PR.

**Comment by ryelle** [comment]
Fixed with #111.
