### ISSUE TITLE
Header & Footer: Incorrect font across all site

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-mu-plugins#114]
This was hard to distinguish but the font used in the header and footer isn't `Inter`.

I have overlapped the Figma mockup and a screenshot from the live site and the site has the little tail at the bottom of the `a`, and the Figma comps do not.

<img width="1098" alt="Screen Shot 2022-01-24 at 9 18 06 AM" src="https://user-images.githubusercontent.com/65220155/150800447-327a3213-2bc8-40a6-847e-2edb1c810c9e.png">

**Comment by ryelle** [comment]
Are you saying the font _should_ be inter and it isn't? That must be a regression, because I fixed that a while back https://github.com/WordPress/wporg-mu-plugins/pull/82

What sites do you see this on?

**Comment by beafialho** [comment]
I've cleared browsing data and cache and it's only seen in Safari - I'm seeing it the homepage wordpress.org and the translated sites. On Chrome and Firefox I see Inter 👍
