### ISSUE TITLE
Header has different height than the mockup

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-mu-plugins#115]
According to the design, the Global Nav bar should have a height of `90px`. In the site, it has `103px`.

<img width="1030" alt="Captura de ecrã 2022-01-24, às 15 14 06" src="https://user-images.githubusercontent.com/65220155/150810119-26a8c35c-7980-4fc2-a8a2-e81232a1d63e.png">

<img width="1531" alt="Captura de ecrã 2022-01-24, às 15 12 54" src="https://user-images.githubusercontent.com/65220155/150810240-3040ab7d-bcc4-4bfe-ba05-904362d0b090.png">

**Comment by dd32** [comment]
Just noting that according to https://github.com/WordPress/wporg-news-2021/issues/181 the designed size was 104px, Did I misread that comment, or was this intended to be 104px and this is a request to reduce it to 90px?

**Comment by beafialho** [comment]
@dd32 I was referring to the mobile header height in that comment. In [the design](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=900%3A27) on desktop it's `90px`.

**Comment by dd32** [comment]
This was fixed via #121.
