### ISSUE TITLE
New Pattern page is broken

### ISSUE THREAD

**Issue by aurooba** [WordPress/wporg-mu-plugins#116]
Hallo! Not sure if this was intentional or if it has moved, but this page https://wordpress.org/patterns/new-pattern/, which I thought was to submit new patterns is completely broken. I also can't find a link anywhere in the Patterns Directory to _add_ new patterns anymore.

![FireShot Capture 001 - New Pattern - WordPress org - wordpress org](https://user-images.githubusercontent.com/6925260/150816289-a90d19ce-cd39-45c1-b6c5-79f09c3982be.png)

**Comment by ryelle** [comment]
Hi @aurooba, new pattern submissions aren't open yet, so that page isn't available to anyone right now. Pattern submissions should open sometime next month. Thanks!
