### ISSUE TITLE
Logo pixelated

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#117]
https://wordpress.slack.com/archives/C02QB8GMM/p1643030156211400

**Comment by ryelle** [comment]
The linked comment says

> I'm not sure if image compression of Slack gets this through well, but on Edge 97.0.1072.62 at 100% resolution scaling, the logo is pixelated and eye-straining.
![Image from iOS](https://user-images.githubusercontent.com/541093/151073816-3cdf1781-10f2-4fee-a27e-5c2830b5be12.jpg)

There was also a suggestion of using `circle` in the SVG. This would be best triaged & handled by design, IMO, so ccing @beafialho @kellychoffman

**Comment by tellyworth** [comment]
Is this a blocker for the news theme launch @kellychoffman ?

**Comment by beafialho** [comment]
I've opened it on Edge and this seems like something we can address later? So not a blocker.

![Captura Web_26-1-2022_124747_wordpress org](https://user-images.githubusercontent.com/65220155/151531191-d1018eae-cc79-4b63-acb7-7f12bf63c685.jpeg)

**Comment by ryelle** [comment]
Just confirming that this was fixed with the update in #160, the logo looks better on PC/Edge
