### ISSUE TITLE
Customize search `aria-label`

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#12]
The search "menu" needs it's `aria-label`s customized (e.g., "Open search" rather than "Open menu"), but that can't be done until https://github.com/WordPress/gutenberg/issues/24369 is resolved.

xref https://github.com/WordPress/wporg-mu-plugins/pull/9/commits/6779dd78a7f38ba93df74bb6a4f79ffc5547921e#r728528115

**Comment by ryelle** [comment]
This was done via JS in https://github.com/WordPress/wporg-mu-plugins/pull/119, so if we eventually switch over to a core method, that JS can be removed too.

Or we can consider this done and close the issue.
