### ISSUE TITLE
Search: Tweak UI / interactions

### ISSUE THREAD

**Issue by kellychoffman** [WordPress/wporg-mu-plugins#120]
A couple tweaks to make on the search field in the header: 

- [x] Mobile: Input should go full width. (See screenshot below)
- [x] When you open the search on small screen, then make the screen bigger, the search stays open and covers nearly all the screen. Instead, it should either snap to the large screen view or the search overlay should close. 

Design reference:

Search input width:
<img width="464" alt="Screen Shot 2022-01-24 at 6 28 35 PM" src="https://user-images.githubusercontent.com/5835847/150899754-f79567da-4e7e-494f-aa8d-16c54ce6e520.png">

**Comment by dd32** [comment]
>  When you open the search on small screen, then make the screen bigger, the search stays open and covers nearly all the screen. Instead, it should either snap to the large screen view or the search overlay should close.

This is similar to #56 but now affects the search too.

**Comment by dd32** [comment]
Looks like this is resolved via #121 & #122
