### ISSUE TITLE
Translate sticky headers obscured

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#124]
@zackkrida in https://github.com/WordPress/wporg-mu-plugins/issues/38#issuecomment-1020665721:

> When viewing a list of translation strings like https://translate.wordpress.org/projects/wp/dev/dsb/default/?page=4, each translation has its own sticky header and menu:
>
> ![CleanShot 2022-01-24 at 18 43 58@2x](https://user-images.githubusercontent.com/6351754/150883853-0dcb6456-7c63-40fc-8690-49946540550d.png)
>
> These can be obscured by the sticky header, which is particularly frustrating on short (namely small laptop and ultrabook) displays:
>
> > before
![CleanShot 2022-01-24 at 18 49 17@2x](https://user-images.githubusercontent.com/6351754/150884336-e087ceb2-d90d-4c7c-b579-4a17017a969e.png)
> 
> > after
![CleanShot 2022-01-24 at 18 49 01@2x](https://user-images.githubusercontent.com/6351754/150884341-4eb3ec19-b7db-4e79-9f7b-e542487d9ced.png)

**Comment by ocean90** [comment]
This was already fixed in https://meta.trac.wordpress.org/changeset/11469 I think.

**Comment by iandunn** [comment]
Is that working for you? It wasn't in my testing.

**Comment by ocean90** [comment]
Odd, seems like it's only working when logged-in for me.

**Comment by iandunn** [comment]
Huh, it doesn't seem to work in either state for me 🤷🏻

**Comment by dd32** [comment]
https://meta.trac.wordpress.org/changeset/11469 did indeed fix it, but it was then broken by https://meta.trac.wordpress.org/changeset/11470.

**Comment by iandunn** [comment]
Ah, that makes sense now, thanks!
