### ISSUE TITLE
Menu font is small

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#127]
There's been some [feedback about the small font size in the menu](https://wptavern.com/wordpress-org-gets-new-global-header-and-footer-design#comment-413392). It feels "readable but uncomfortable" to me too.

Now that we have the priority navigation (the `...`), do we still need the small font size?

**Comment by iandunn** [comment]
@beafialho , do you have any thoughts on this?

**Comment by tellyworth** [comment]
Let's make a design decision: is this a blocker for the News theme launch @kellychoffman?

If not we'll move it back to the post-launch milestone.

**Comment by beafialho** [comment]
I see no problem in making the header + footer font size `14px` if `13px` seems too small. It may seem like a small difference but it's notorious. `16px` seems overly large to me.
