### ISSUE TITLE
Admin bar not consistent across sites

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#128]
@justintadlock pointed out that [some sites in the network show the admin bar, and some don't](https://wptavern.com/wordpress-org-gets-new-global-header-and-footer-design).

`wporg-no-adminbar-if-no-blogs.php` intentionally disables it on sites that the user doesn't have a role on. The benefits I see are that it avoid confusions, preserves screen real estate, and avoids frustrating people who dislike sticky headers. The drawback is that it's not consistent.

Turning it on doesn't really add any value, other than fixing the inconsistency problem. It may also introduce links etc that don't make sense in a "i don't have a role on this blog" context. We could remove those, though. There is a `logged-out-admin-bar.php` plugin that's active on some sites.

For non-WP sites like Trac, we might be able to use the new API endpoint to include it, although we'll want to think about any security implications. It definitely should bypass Trac's cache, so we'd need to load it via JS, which might introduce some FOUC if it's not done early enough.

@beafialho, do you have any thoughts from the design perspective?

**Comment by beafialho** [comment]
> @beafialho, do you have any thoughts from the design perspective?

I agree it's not consistent but I think addressing this would be a part of the future effort of rethinking the header architecture (menu items included), and possibly integrating the admin bar to the global header.

@kellychoffman may have more useful input.

**Comment by kellychoffman** [comment]
I always wondered why it did that! Ian - Your reasoning makes sense for why it was implemented still makes sense and I say we keep it as is.

**Comment by iandunn** [comment]
👍🏻  I'll close for now, and we can reopen in the future if we decide to combine the two headers.
