### ISSUE TITLE
Global CSS styling leaking into BuddyPress.org/bbPress.org

### ISSUE THREAD

**Issue by JJJ** [WordPress/wporg-mu-plugins#129]
Hey friends 👋

The BuddyPress.org & bbPress.org sites share some must-use plugins with WordPress.org, and recently it appears that global CSS styles from `wp4.css` are making their way onto those sites.

Maybe from: https://github.com/WordPress/wporg-mu-plugins/commit/82f2f1bfb5c3d4a9b51800cee033c31aa25d8a73 ?

![jjj-on-2022-01-26-at-14-28-52@2x](https://user-images.githubusercontent.com/88951/151241933-7b7c65b6-3815-4635-bed6-ea49aa32b8b3.png)

![jjj-on-2022-01-26-at-14-29-33@2x](https://user-images.githubusercontent.com/88951/151242050-258d9a80-8c60-49c1-8909-3b5f8a0b3bf7.png)

* `a:visited` is setting a blue color to all visited links
* `p a` is underlining all links

I'm happy to override them in the `bb-base` theme (and the respective palette-swapped child themes) while everything is under construction. Otherwise, it makes to narrow the scope of when this file is enqueued somehow.

**Comment by iandunn** [comment]
Sorry about that! Fixed in `r18371-dotorg`
