### ISSUE TITLE
Global styles are not loaded on local dev sites

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-mu-plugins#138]
Again, I'm trying to use this on the Pattern Directory repo (#136), and I've run into another issue… this is a classic theme, and I don't have the News site locally to generate the custom properties, so the menu loads but is mostly unstyled:

<img width="1038" alt="Screen Shot 2022-02-01 at 5 19 04 PM" src="https://user-images.githubusercontent.com/541093/152061023-7b1d6f4c-7f64-43b5-823c-1ac4a18ec382.png">

It seems like the `fetch_global_styles` function should handle this but it isn't, it won't connect to load the styles (I _think_ because I'm sandboxing wordpress.org while working, but it should still work).

My hacky workaround so I can move on is to enqueue the styles endpoint directly in a `sandbox.php` mu-plugin:

```php
add_action(
	'wp_enqueue_scripts',
	function() {
		wp_enqueue_style(
			'global-header-footer',
			'https://wordpress.org/wp-json/global-header-footer/v1/styles',
			array(),
			'1'
		);
	}
);
```

**Comment by dd32** [comment]
I think this might be fixed by 39039e6 - If it's [not on the WordPress.org network](https://github.com/WordPress/wporg-mu-plugins/blob/39039e68d4000504f239ec17a1b0e677f64334cf/mu-plugins/blocks/global-header-footer/blocks.php#L878-L885), it should [fetch the styles from the API](https://github.com/WordPress/wporg-mu-plugins/blob/39039e68d4000504f239ec17a1b0e677f64334cf/mu-plugins/blocks/global-header-footer/blocks.php#L904-L946).

If `WPORG_SANDBOXED` is defined truthfully locally, that would break the latter function though.

**Comment by ryelle** [comment]
> If `WPORG_SANDBOXED` is defined truthfully locally, that would break the latter function though.

Yeah, we [do that](https://github.com/WordPress/pattern-directory/blob/bee5deaa150f8a8af032f0ec68ea67f1d06ed3eb/bin/index.sh#L18) in the pattern directory setup script, but TBH I'm not sure why.

**Comment by dd32** [comment]
> Yeah, we [do that](https://github.com/WordPress/pattern-directory/blob/bee5deaa150f8a8af032f0ec68ea67f1d06ed3eb/bin/index.sh#L18) in the pattern directory setup script, but TBH I'm not sure why.

Yeah that's not ideal :) 

[Looking at the uses of it](https://github.com/WordPress/pattern-directory/search?q=WPORG_SANDBOXED), I think we need to make use of [wp_get_environment_type()](https://developer.wordpress.org/reference/functions/wp_get_environment_type/) more widely - something like `local` = local machine, `staging` = WordPress.org sandboxes, `production` = WordPress.org production.

**Comment by dd32** [comment]
> [Looking at the uses of it](https://github.com/WordPress/pattern-directory/search?q=WPORG_SANDBOXED), I think we need to make use of [wp_get_environment_type()](https://developer.wordpress.org/reference/functions/wp_get_environment_type/) more widely

Just noting that I've made this change, WordPress.org sandboxes now claim to be a staging environment. This only affects sandboxes and not any environment setting `WPORG_SANDBOX`.
