### ISSUE TITLE
Mobile logo misplaced

### ISSUE THREAD

**Issue by dd32** [WordPress/wporg-mu-plugins#142]
In the mobile view the logo is misplaced by having too much padding-top. This appears to have broken in the last day.

https://user-images.githubusercontent.com/767313/152091527-1cb64db9-1bf3-472b-8f10-3208ab12182a.mov

**Comment by SchneiderSam** [comment]
And here (Safari, Iphone) and only if i am browsing at https://make.wordpress.org/:
![FKlXp61XsAEvlvo](https://user-images.githubusercontent.com/9355398/152177020-8d43b5f7-d7e9-4721-8622-ccf84b332767.jpg)
