### ISSUE TITLE
Header: Menu buttons have gradient/box shadow on iOS Safari

### ISSUE THREAD

**Issue by SchneiderSam** [WordPress/wporg-mu-plugins#145]
iphone, Safari and only on this URL: https://make.wordpress.org/
![FKlXp61XsAEvlvo](https://user-images.githubusercontent.com/9355398/152178124-1f75e9ac-b9c9-45c4-84df-79d463dd73fa.jpg)

**Comment by ryelle** [comment]
@SchneiderSam Is this a different issue than #142 ?

**Comment by SchneiderSam** [comment]
@ryelle At #142, it's all about the logo. Here I just wanted to draw attention to the menu again

**Comment by ryelle** [comment]
Do you mean the gradient/outline around the buttons in your screenshot? I can't reproduce that on iOS/Safari. What version of iOS are you using?

**Comment by SchneiderSam** [comment]
> What version of iOS are you using?

15.3, i have this gradient only on this url https://make.wordpress.org/

**Comment by dd32** [comment]
I've been unable to reproduce with Desktop Safari, I don't have an iOS device, but I've been unable to reproduce with the XCode iOS 15.2 simulator too.

@SchneiderSam What Device are you using? Based on the screenshot, you're on https://make.wordpress.org/core/  are you on one of it's pages? or the homepage? does it affect other make sites? Such as https://make.wordpress.org/meta/

**Comment by SchneiderSam** [comment]
@dd32 tested now with privat window and now there is no shadow. Ticket can be closed.
