### ISSUE TITLE
Header: Misplaced close menu icon (Add an indent for the close menu button)

### ISSUE THREAD

**Issue by dd32** [WordPress/wporg-mu-plugins#150]
As reported in https://meta.trac.wordpress.org/ticket/6084 by @Otshelnik-Fm

> The button for closing the mobile menu is "stuck" to the edge http://joxi.ru/J2bEaMDigPQR7m
> ![image](https://user-images.githubusercontent.com/767313/152903441-fdd6cd2e-efea-4c5a-bd42-c97890640c10.png)
> Fix it:
>  ![image](https://user-images.githubusercontent.com/767313/152903458-28f6d305-5984-4788-b4da-18b0b6dc80ec.png)

**Comment by ryelle** [comment]
This custom property was removed in https://github.com/WordPress/wporg-news-2021/pull/283 — I think we can define it locally in this project instead, since it's related more to the header than the news theme.
