### ISSUE TITLE
Header: Mobile menu should use 3 dashes (The menu icon should not look like an equal sign)

### ISSUE THREAD

**Issue by dd32** [WordPress/wporg-mu-plugins#151]
As reported in https://meta.trac.wordpress.org/ticket/6083 by @Otshelnik-Fm

> Non-intuitive menu icon: 
> ![image](https://user-images.githubusercontent.com/767313/152903734-eb9dba74-6d54-4656-a8a8-3d15583cb351.png)
>
> The hamburger menu is usually associated with such an icon: 
![image](https://user-images.githubusercontent.com/767313/152903744-883072cb-f550-414a-b27f-1c31e64ca943.png)
> 
> replace with a menu icon that fits the meaning. It's confusing

Upon looking at Figma, [it looks like a 3 bar icon was included in the design](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=4659%3A8203).

**Comment by ryelle** [comment]
This is the menu icon that's used by default in Gutenberg's Naviagtion block. You can see the same thing in [the Twenty Twenty Two demo](https://wp-themes.com/twentytwentytwo/). 

We can replace the icon with the designed 3-bar one (probably using something like [the `swap_submenu_arrow_svg` code](https://github.com/WordPress/wporg-mu-plugins/blob/993c85dc99f54a872101ff86adbc2925283e6d73/mu-plugins/blocks/global-header-footer/blocks.php#L1060-L1068), though [the icon is hardcoded](https://github.com/WordPress/gutenberg/blob/bef3d91e3636c1402472d55e2da9086195a1e746/packages/block-library/src/navigation/index.php#L542)), but I don't think it's that unexpected of an icon.

**Comment by Otshelnik-Fm** [comment]
Mobile menu - is 3 line, not 2
http://joxi.ru/5mdp3jvHab53pm

why invent an unintuitive icon. Well, then why 2 stripes, let's make an icon with one stripe - for example, like this: -

**Comment by dd32** [comment]
> This is the menu icon that's used by default in Gutenberg's Naviagtion block

That sounds like a good enough reason to leave it as it is to me.

> but I don't think it's that unexpected of an icon.

I agree. If it's not already, it will be once all the WordPress sites start using it.

> why invent an unintuitive icon

I don't think it's unintuitive myself, I genuinely never noticed it was 2 instead of 3 bars. The two bars feels less crowded than the decade-old 3line variant too.

I'm going to close this issue, as it's not a deliberate choice on WordPress.orgs header, but is simply inherited from Gutenberg.

I can't see an issue upstream in Gutenberg for why this icon was chosen, or a design guide, but will note the project board for the block: https://github.com/WordPress/gutenberg/projects/58
