### ISSUE TITLE
Increase contrast for Code is Poetry logo

### ISSUE THREAD

**Issue by dd32** [WordPress/wporg-mu-plugins#154]
Submitted as https://meta.trac.wordpress.org/ticket/6069 by @bijayyadav

> **Code is Poetry - Change SVG image color to white in the footer**
>
> All the other text and icons are in white color and they are clearly visible. Whereas, the Code is Poetry logo is not clearly visible. > Maybe it will be even more difficult for those having clear eye vision. I would like to suggest changing the color to white and make identical to others.

@aezazs-multidots has suggested increasing the SVG opacity in [6069.diff](https://meta.trac.wordpress.org/attachment/ticket/6069/6069.diff)

**Comment by ryelle** [comment]
cc @beafialho or @kellychoffman for input here

**Comment by beafialho** [comment]
Like @dd32 mentioned, the `Code is Poetry` text has always been at a lower visibility than the rest of the footer and the intent of the design was to simplify the footer by highlighting links and actions, Code is Poetry is not a link or action. I think it can stay the way it is — if everything is highlighted, nothing is highlighted.

**Comment by iandunn** [comment]
Closing to keep things organized, but feel free to continue discussion or reopen if needed.
