### ISSUE TITLE
Remove text shadow on subscribe button in make WordPress sites 

### ISSUE THREAD

**Issue by kafleg** [WordPress/wporg-mu-plugins#158]
There is a Subscribe button in the make WordPress sites. Due to the text-shadow, the **Subscribe** text is not clearly visible. Also, the hover state of that button is not nice as well. 
https://make.wordpress.org/themes/

![image](https://user-images.githubusercontent.com/13062231/153987963-e15bdcc4-8c2a-4b73-923d-9f3688ff1756.png)

**Comment by dd32** [comment]
This isn't a header thing, and so should be reported to meta.trac, but appears to be the same root-cause as #145 which we couldn't reproduce.
