### ISSUE TITLE
Document how the header & footer are generated on all sites

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-mu-plugins#165]
There's some documentation on the WP-generated sites, but I think it could be updated. And the non-WP sites are still "todo".

See https://github.com/WordPress/wporg-mu-plugins/blob/trunk/mu-plugins/blocks/global-header-footer/README.md

**Comment by iandunn** [comment]
I added what seems useful to me, but feel free to add more if you think there's anything still missing.
