### ISSUE TITLE
Mobile: "Get WordPress" button has black background on hover

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#167]
github seems to be having issues uploading screenshots right now, but if you hover over the "get wordpress" button, you'll see there's ~25px of black spacing on the left of the text, but 0px on the right.

**Comment by ryelle** [comment]
It's not supposed to have a background at all, looks like it inherited it from the other menu items. 

<img width="695" alt="Screen Shot 2022-02-17 at 5 58 10 PM" src="https://user-images.githubusercontent.com/541093/154585475-65eb340a-088e-4675-8b76-7d3506c45484.png">
