### ISSUE TITLE
Apply correct Get WordPress button default and hover states

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-mu-plugins#168]
The Get WordPress button shouldn't be underlined by default and it currently doesn't have a hover effect:

https://user-images.githubusercontent.com/65220155/154671409-638afeb0-07e6-4c3f-b837-5449b9284aa1.mp4

Button styles can be found [here](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=4659%3A8224).

<img width="1166" alt="Captura de ecrã 2022-02-18, às 11 12 49" src="https://user-images.githubusercontent.com/65220155/154672285-3e3f4454-2321-4093-b14c-db78f2d21b8c.png">

**Comment by dd32** [comment]
@beafialho Where are you seeing the button styled with an underline?

**Comment by beafialho** [comment]
@dd32 I believe I was seeing it in the live site, but I'm not seeing it anymore. However, the hover states mentioned above should be applied to the button.

**Comment by dd32** [comment]
@beafialho Got it! (I'm assuming you meant the News site, or W.org homepage) Thanks. I'd seen the underline in some places with broken CSS in the past, but AFAIK they'd all been fixed, that's why I questioned it, to see if there was somewhere specific that was missed.

Agreed on the button states.

**Comment by beafialho** [comment]
> Got it! (I'm assuming you meant the News site, or W.org homepage)

That's right! I meant the WordPress.org header 🙂

**Comment by iandunn** [comment]
I was seeing the underline too, but only on the desktop view. Fixed that and the button states in 93ef5c508124ec1fa71c1edeb61811025e25f303
