### ISSUE TITLE
How do I work on the header?

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-mu-plugins#177]
It isn't clear to me how I would work on the header. 
- Do I need to setup my own environment and import it? 
- Can I work on it via the wporg-news-2021 project?

**Comment by iandunn** [comment]
That's a great question. there isn't a separate environment, it should just be pulled into another repo like News.

To set it up, you'd just follow the setup instructions for the News repo. After that you should have a git checkout in `mu-plugins/wporg-mu-plugins`, and that's where you'd make commits, push, pull, etc. So it's a git repo inside of a git repo, but they're not aware of each other as far as Git is concerned (because Git submodules are awful).

`npm run start:all` will run the mu-plugins watcher in addition to the News watcher. Does that all make sense?

Maybe that answer should be added to #176?

**Comment by StevenDufresne** [comment]
Yeah, good point. 
I think that's _good enough_ for now. I'll open up a new PR.

**Comment by StevenDufresne** [comment]
@iandunn 

>So it's a git repo inside of a git repo, but they're not aware of each other as far as Git is concerned (because Git submodules are awful)

Instead of a git repo in a git repo, for [`wporg-news-2021`](https://github.com/WordPress/wporg-news-2021), I updated the mapping for `.wp-env.json` to point to the `wporg-mu-plugins` folder checked out adjacently.

**`.wp-env.json`**
```
...
"wp-content/mu-plugins": "./source/wp-content/mu-plugins",
...

```
**to**

```
...
"wp-content/mu-plugins/wporg-mu-plugins/mu-plugins": "../wporg-mu-plugins/mu-plugins",
...
```
It was a bit tricky because `wporg-news-2021` expects a few extra folders, namely `wporg-mu-plugins/mu-plugins` which don't match this project structure exactly. 

What do you think about discussing that approach in the readme and maybe updating `wporg-news-2021` mapping paths to make it easy to just swap the value portion out with a relative path?

**Comment by iandunn** [comment]
I don't use wp-env, so I don't have any opinion on the mapping stuff. As long as it continues to work in other envs I'm happy 👍🏻  @ryelle or @coreymckrill might have thoughts for wp-env.

#141 is related to the paths.

**Comment by ryelle** [comment]
Just checking, @StevenDufresne the only change suggestion is to add other setup options to the readme? 

The setup in News works for me as-is, composer checks out a functional git repo where I do my work, and I can use the yarn workspace to build the mu-plugin. I sync that up to my sandbox for testing other non-News sites. So I don't necessarily want any config to change, but I don't oppose documenting other options in the readme.

**Comment by coreymckrill** [comment]
One thing you can do without affecting any files that are under version control is add a `.wp-env.override.json` file to the project root, which can then be used to override specific values in the `.wp-env.json` file. I've used it a few times to test out a different version of Core, but you could totally do it for the mu-plugins folder as well.

**Comment by StevenDufresne** [comment]
I think this issue served it's purpose.
