### ISSUE TITLE
Header submenu's not displaying correctly with Safari 13.1.2 (13609.3.5.1.5)

### ISSUE THREAD

**Issue by dd32** [WordPress/wporg-mu-plugins#180]
As reported by @michelwppi in https://meta.trac.wordpress.org/ticket/6143

> since few weeks, wordpress.org website shows errors in submenus of support menu and rightest menu. This two sub-menus are always displayed in safari Version 13.1.2 (13609.3.5.1.5). In MacOX 10.13.6 latest update for my venerable iMac 27′, safari Version 13.1.2 (13609.3.5.1.5) was updated in 2020 and works for all WP themes with same type of menu/submenu themes. (please see screenshots attached)

![wporgerrors](https://user-images.githubusercontent.com/767313/157387799-7360fca1-b7e2-499d-b5d8-d085c24c1efe.png)

![wpticketerrors](https://user-images.githubusercontent.com/767313/157387795-7cddc0fe-73ff-438a-9737-4379de504d2d.png)

Possibly similar browser-support as #159

**Comment by ryelle** [comment]
This is the same issue as #159, Safari 13.1 doesn't support `:where`.
