### ISSUE TITLE
Header: Even out spacings between arrow and menu links

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-mu-plugins#186]
The arrow for menu items with submenus is currently sitting too far away from the item, it should be closer to it. The darker background on hover should also have padding on the right, similar to all other items.

**Currently:**
<img width="852" alt="Captura de ecrã 2022-03-14, às 14 50 32" src="https://user-images.githubusercontent.com/65220155/158199452-8c0b76ed-8fcf-40a8-bbc7-bdb0b4ab6bd5.png">

**Intended:**
<img width="876" alt="Captura de ecrã 2022-03-14, às 14 53 51" src="https://user-images.githubusercontent.com/65220155/158199465-6cd99ce6-fdf3-4226-b1e3-23665fd5edee.png">

**Comment by iandunn** [comment]
It looks like this was caused by https://github.com/WordPress/gutenberg/pull/37003

**Comment by beafialho** [comment]
@iandunn the spacing issue is solved but the arrow icons do not match the mockup.

<img width="858" alt="Captura de ecrã 2022-03-17, às 16 18 05" src="https://user-images.githubusercontent.com/65220155/158845631-c8ae5f62-29d9-4ed7-9d0e-e3dd58d6fe4e.png">
