### ISSUE TITLE
Mobile Get WP button not styled correctly on Downloads page

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#187]
It looks fine on most pages, but on the Downloads page it looks off because of `.current-menu-item`:

<img width="517" alt="Untitled" src="https://user-images.githubusercontent.com/484068/158810246-2dff3e68-66ae-4d17-8f4e-c31258dc76a2.png">

**Comment by vijayhardaha** [comment]
https://github.com/WordPress/wporg-mu-plugins/blob/5e3c41854a7f3dfc9bf9b7aefc226c2c8380b746/mu-plugins/blocks/global-header-footer/blocks.php#L976-L978

`.current-menu-item` can be ignored on download urls by adding a check on `Line 977` unless `set_current_item_class` is not being used in somewhere else.
```php
if ( get_download_url() === $item['url'] ) {
	continue;
}
```

**Comment by ryelle** [comment]
This was fixed in b0ec8cff54134cfd21e7ba10c8562e6398edf086.
