### ISSUE TITLE
Include global FSE styles in classic themes 

### ISSUE THREAD

**Issue by dd32** [WordPress/wporg-mu-plugins#19]
tracked in #38 

Currently the header & footer here can't be used separately from the news blog theme, as it's reliant upon the global styles, which appear to be theme-specific.

Specifically, loaded from https://github.com/WordPress/wporg-news-2021/blob/trunk/source/wp-content/themes/wporg-news-2021/theme.json

It seems that we might need to create a base typographical/colour definition and import that dynamically into the theme.json processing perhaps? I'm not exactly sure.

**Comment by iandunn** [comment]
What about something like:

```php
add_action( 'wp_head, function() {
    if ( ! is_block_theme() {
        create_theme_json_variables( 'path/to/news/theme.json' );
    }
}
```

Those aren't the real function names, but I'm pretty sure Gutenberg already has functions that do those things.

**Comment by iandunn** [comment]
f5835d2 implements the core of the solution, but there are lots of minor bugs to fix.

You can see it working on w.org/patterns by setting `FEATURE_2021_GLOBAL_HEADER_FOOTER` to `true` on a remote sandbox. You'll may need to sync this plugin to your sandbox first.

xref https://meta.trac.wordpress.org/changeset/11388/, `r18096-dotorg`

**Comment by iandunn** [comment]
The new header/footer can now be tested on most of w.org.

xref `r18113-dotorg`, `r18112-dotorg`, `r18111-dotorg`, https://meta.trac.wordpress.org/changeset/11400/, https://meta.trac.wordpress.org/changeset/11401/, https://meta.trac.wordpress.org/changeset/11402/

There's a few static places where it can't, like the `w.org/index.php`, `w.org/mobile`, and `w.org/hosting`. Those all have tasks in #38 to port to native WP pages. At that point they should pick up the new header automatically from the parent themes.

Profiles, Trac, etc will need to use a REST API endpoint too, which is also a separate task in #38.

**Comment by iandunn** [comment]
There are lots of small problems on various sites, but the core functionality is working well, so I'm going to close this and open a new issue for fixing the small things.
