### ISSUE TITLE
Global Header misplaced with Gutenberg 12.9

### ISSUE THREAD

**Issue by ocean90** [WordPress/wporg-mu-plugins#193]
[Gutenberg 12.9](https://make.wordpress.org/core/2022/03/30/whats-new-in-gutenberg-12-9-30-march/) has been released. After a `svn up` on my sandbox I got a broken header. Reverting to 12.8.1 restores the current header. I'm going to pin the plugin external to 12.8.1 for now. (Done in [r18671](https://dotorg.trac.wordpress.org/changeset/18671).)

![image](https://user-images.githubusercontent.com/617637/160923532-93514775-e267-48be-a9ff-209c03dec2cb.png)

**Comment by iandunn** [comment]
Thanks for catching that and pinning!

**Comment by ryelle** [comment]
Seems like the issue is that the header group is now wrapped in an `inner-container` block, possibly as a result of this change: https://github.com/WordPress/gutenberg/pull/39321 — but whether it will be wrapped depends on whether the theme has a `theme.json`, so we'll need to handle both cases.

**Comment by ocean90** [comment]
Looks like the new block specific filter needs to be added to https://github.com/WordPress/wporg-mu-plugins/blob/75e9e80f3293f41d72102e86771aa6cba7544978/mu-plugins/blocks/global-header-footer/blocks.php#L273-L305.

**Comment by iandunn** [comment]
Pinned buddypress.org in `r18672-dotorg`

**Comment by ocean90** [comment]
Fixed in #200.
