### ISSUE TITLE
Mobile Get WP button not styled correctly on focus

### ISSUE THREAD

**Issue by dd32** [WordPress/wporg-mu-plugins#195]
Potentially similar to #187 

Originally reported at https://meta.trac.wordpress.org/ticket/6237
![outline-issue-btn](https://user-images.githubusercontent.com/767313/161180378-f0c2d1ee-16cb-4274-85b2-5172767900b0.png)

The `:active` or `:focus` styles from the menu are being applied to the Download button.

**Comment by aezazs-multidots** [comment]
Hello @dd32 

For the solution to this ticket, I have created a PR.
[https://github.com/WordPress/wporg-mu-plugins/pull/199](https://github.com/WordPress/wporg-mu-plugins/pull/199)

Can you please review it?

Thank you.

**Comment by aezazs-multidots** [comment]
Hello, @iandunn and @dd32  . For the solution to this ticket, I have created a PR. https://github.com/WordPress/wporg-mu-plugins/pull/199. Please review it and merge it.

Thank you.

**Comment by dd32** [comment]
@aezazs-multidots Please be patient, Bumping tickets/issues is not welcome. We're aware of the PR, but I've not verified if it's the intended design.

**Comment by ryelle** [comment]
This issue was fixed as part of some CSS cleanup in #225.
