### ISSUE TITLE
learn.wordpress.org top leave menu hover issue

### ISSUE THREAD

**Issue by praful2111** [WordPress/wporg-mu-plugins#206]
Learn WordPress has a text-decoration issue on the top header menu part.
screenshot
![index](https://user-images.githubusercontent.com/541093/171213841-c15b5ee4-16f5-436f-b641-c275410ea974.png)

**Comment by StevenDufresne** [comment]
What do you mean by "has a text-decoration issue"? Are you expecting there to be no underline?

**Comment by ryelle** [comment]
This was also reported [on meta.trac](https://meta.trac.wordpress.org/ticket/6339), where it's clear the issue is the underline - it sounds like at the time, this behavior was different on other wporg sites. Now all the sites should have the underline on hover, so this is not an issue anymore.
