### ISSUE TITLE
Keyboard navigation jumps around through header 

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-mu-plugins#22]
When using my keyboard to tab through the site, the focus doesn't move through the header in the way I expected. After the site logo, it skips to the search & "Get WordPress" button, then moves through the nav. I would expect it to be Logo -> Nav -> Search -> Get WordPress -> Page content

What happens:
<img width="1548" alt="Screen Shot 2021-12-02 at 4 14 24 PM" src="https://user-images.githubusercontent.com/541093/144504525-48840445-0f0e-4e72-9ab5-85516f930a65.png">

This is because the search & button are before the nav menu in the markup. If the main nav section `.global-header__navigation` is brought before the search nav `global-header__search`, that should fix the issue… but I don't know if it was done this way on purpose.

**Comment by iandunn** [comment]
It was on purpose, because the design calls for a different order in the desktop than on mobile. CSS is used to reorder on desktop, and I think moving the source order would create the same confusion when testing the mobile viewport.

Do you think this is a problem for screen reader users, or just for sighted devs who are testing?

**Comment by ryelle** [comment]
> Do you think this is a problem for screen reader users, or just for sighted devs who are testing?

Neither, this isn't an issue of sight- it's about keyboard-only users (or switch access users) who can't use a mouse. It could also be an issue for sighted screen-reader users (whether they're low vision and using SR to help boost understanding, or have cognitive issues that make it easier to follow along to spoken words). 

I _think_ the reversed order would be less confusing on mobile, since it's not swinging my eyes from one end of the screen to another (so this would be an acceptable solution), but it would be ideal if the source order matched visual in both places (this would be better).

**Comment by iandunn** [comment]
Ah, my bad, thanks! 

> reversed order would be less confusing on mobile

That WFM 👍🏻 

> ideal if the source order matched visual in both places

How would you implement that?

**Comment by ryelle** [comment]
> How would you implement that?

Off the top of my head, no idea, especially when trying to work with the existing GB blocks… Which is why I think the other solution is acceptable.
