### ISSUE TITLE
Header & footer links have underlines on block themes

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-mu-plugins#232]
Seen on https://wordpress.org/main-test/

<img width="1184" alt="Screen Shot 2022-08-01 at 4 51 25 PM" src="https://user-images.githubusercontent.com/541093/182244508-45f59b66-14ef-4dd6-89b2-1991d57d9a55.png">

Either add CSS to remove this (should only appear on hover), or try the text decoration attribute on the nav menu block.

Note - not seen on News because the news theme uses [the higher-specificity selector](https://github.com/WordPress/wporg-news-2021/blob/031d9db053102bd34c9be0987768d0642b8eafb2/source/wp-content/themes/wporg-news-2021/sass/base/_elements.scss#L2) (matching GB) to remove it.

**Comment by adamwoodnz** [comment]
I tried both these settings in theme.json @ryelle but neither are specific enough to target the anchor itself

```
"styles": {
		"blocks": {
                        "core/navigation": {
				"typography": {
					"textDecoration": "none"
				}
			},
			"core/navigation-link": {
				"typography": {
					"textDecoration": "none"
				}
			},
                }
}
```

The resulting rules are 
```
.wp-block-navigation {
    text-decoration: none;
}

.wp-block-navigation-link {
    text-decoration: none;
}
```

We need to target  `.wp-block-navigation-link a` or better ` .wp-block-navigation-link .wp-block-navigation-item__content`

So I'll start on a CSS solution unless you have any other suggestions 🙏
