### ISSUE TITLE
Header Menu: codex.wordpress.org doesn't show new menu top bar at wordpress.org

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/wporg-mu-plugins#259]
From the merge https://github.com/WordPress/wporg-mu-plugins/pull/257 there's a new menu top bar at wordpress.org
This new menu top bar doesn't appear at codex.wordpress.org

Related Issue: https://github.com/WordPress/wporg-mu-plugins/issues/251

**Comment by ryelle** [comment]
The codex is [heavily cached,](https://make.wordpress.org/systems/2022/04/04/clear-codex-cache-lower-cache-ttl/) but it should clear after by the end of today.

**Comment by iandunn** [comment]
It looks good now, but we can reopen if there's still an issue.
