### ISSUE TITLE
Proposal to bring comments link back to admin bar

### ISSUE THREAD

**Issue by justintadlock** [WordPress/wporg-mu-plugins#260]
With the recent [admin bar redesign](https://github.com/WordPress/wporg-mu-plugins/pull/256), Make Blogs no longer show the "Comments" link.  For some of us who moderate comments on one or more blogs, this was previously a quick way to see if there were any comments in the queue and click if so.  Now, this requires more steps in the workflow:

- Hover profile menu
- Click admin link for the specific blog
- Click comments link

I'd like to see if we could at least bring the comments icon and number back.

![wporg-toolbar-missing-comments](https://user-images.githubusercontent.com/1816309/188152369-ef3f0639-09c4-4f75-91be-71943fee7976.png)

**Comment by jasmussen** [comment]
Seems okay to bring back, and perhaps may be even more important than "Customize". The most important aspects of the refresh is mainly the removal of the dual logo and dual search, and ensuring a minimal adminbar experience for most visitors who will be logged out.

**Comment by tobifjellner** [comment]
I second this. In the front-end logged-in toolbar we (Polyglots admins) used to have one number for pending posts and one number for pending comments. 
Here's a screenshot of what the similar links still look like in back-end.
![2022-09-07](https://user-images.githubusercontent.com/24384895/188886687-265e4f5f-13d0-48a6-8240-87f7f8f93217.png)
