### ISSUE TITLE
Changing the wording in the new navigation for documentation

### ISSUE THREAD

**Issue by estelaris** [WordPress/wporg-mu-plugins#262]
The new menu has changed **documentation** for **support**

The words have different meaning and are not interchangeable: Support implies human interaction (what users have in the forums) vs documentation is about data/information that the user can read without human interaction.

The #docs team does not provide support of any type, thus, documentation shouldn't be referred to as support.
Can the word be changed back to documentation?

**Comment by eidolonnight** [comment]
The current "Support" link (which appears under the "learn" parent item) links to https://wordpress.org/support/ which has the page title "WordPress Support" so this looks consistent to me.

> Support implies human interaction

I know that that is not the case where I am, but can certainly understand if that's an implication in some regions/locales. That said, I don't think it makes sense to change only the menu when the titles and URLs all say "support". This seems like a bigger conversation than changing the nav reference.

**Comment by estelaris** [comment]
I understand the need for a longer conversation and that's why we had open this ticket a while back https://meta.trac.wordpress.org/ticket/6387

Also, by providing only support links you have removed documentation from the site as it will take a minute before external users (not us that we peruse this site many times a day) figure out that support = documentation. The consistency you talk about is damaging the user experience in Wp.org.

How can we proceed to make that change happen?

**Comment by zzap** [comment]
Hello @eidolonnight,

The end user documentation should have never been under `/support/` slug. This was done to prevent end users going directly to support forums **before** reading existing documentation. The technical issue was connecting forums with end user documentation, hence the decision was made to create a child theme for the forums where all end user documentation will live. Having documentation under `support` slug was not a good decision. We already saw in WordPress a number of bad naming decisions.

By keeping the "Support" name we continue to make bad decisions. We don't have Documentation in menu any more. We have Support and Forums which implies that now we have live and async support but not the Documentation. 

![dropdown](https://user-images.githubusercontent.com/1508963/193468343-850a622e-d123-42dd-98c5-8833027d2ce2.png)

We can argue what "support" means in different locales but this is not the issue for different locales. Locales have their own Rosetta sites. We have to apply what is considered a norm in English speaking software industry, where Support means human interaction and Documentation means written manual/guide/tutorial. 

Please, change it back to the Documentation. Thank you.

**Comment by Kenshino** [comment]
Hello @eidolonnight 

I've just written up a patch to change what it says on the header.

If you have access to change the menu (which I assume is why you've replied :D), please help us complete this series of changes.

1. Change menu text to say Documentation (this ticket)
2. Change header text to say Documentation (https://meta.trac.wordpress.org/ticket/6517; meta team will deal with this)
3. Change the URL (which is a big task and asked for in https://meta.trac.wordpress.org/ticket/6387 ; meta team will deal with this)

For now, we're happy with just completing 1 and 2. Step 3 will take time.

**Comment by eidolonnight** [comment]
Thank you everyone for chiming in, and especially @zzap for explaining all the background to me while we were at WCUS. Sorry that this took a bit longer than expected in the busy weeks that followed. I've made a [Meta post requesting the change](https://make.wordpress.org/meta/2022/10/11/renaming-wordpress-org-support-to-documentation/) to the page title and nav (@Kenshino 's items 1 and 2), and I also promised to keep an eye on metrics over the next few weeks to ensure we don't see any unexpected negative impact.

**Comment by ryelle** [comment]
Removing "[Status] Needs Design Feedback." The menu item currently called "Support" can now be updated to read "Documentation"

As for changing the page title (assuming that means [the big header here](https://wordpress.org/support/)), that's tracked in https://meta.trac.wordpress.org/ticket/6517.
