### ISSUE TITLE
Global navigation: add link to "make"

### ISSUE THREAD

**Issue by tobifjellner** [WordPress/wporg-mu-plugins#264]
The new menu structure in the global header would allow us to add a link to make.wordpress.org under "Community".
Let's do that!

**Comment by ryelle** [comment]
The top-level "Community" item already links to make.wordpress.org. I wonder if this is related to this comment from  @iandunn (https://github.com/WordPress/wporg-mu-plugins/pull/257#pullrequestreview-1092191880)

> I think making the top-level items link is confusing though, since they go to loosely related pages rather than a "section overview" page. IMO it'd be more clear if the submenu parent items were just text, and a new link was added to each submenu.

We can't add non-links to the menu (as far as I can tell, Gutenberg doesn't support that), but we could add a second duplicate link to each submenu.

**Comment by iandunn** [comment]
I like the idea of adding a duplicate link 👍🏻 

IMO, we would ideally also create new landing pages for each section (e.g., w.org/community), and change the top-level menu item to point there. Then the landing page could briefly describe and link to each submenu item, similar to developer.w.org

Alternatively, we might be able to set the `href` to `#` or `javascript:;`, and then the `cursor` to `pointer`? That should make it appear and function like a button, at least visually. I'm not sure about a11y though.

**Comment by thetinyl** [comment]
> we could add a second duplicate link to each submenu

@ryelle Are you seeing the duplicate links being labeled the same as the top-level nav items?

FWIW, I'm with @iandunn on liking the idea.

**Comment by tellyworth** [comment]
Let's open a companion Gutenberg ticket to suggest an upstream solution (maybe allowing non-link menu items?) as well as whatever we decide to do here.

Is it possible to filter the nav menu output to remove the links and turn the top-level items into non-links?

**Comment by SergeyBiryukov** [comment]
This was also [brought up a few days ago](https://wordpress.slack.com/archives/C02QB8GMM/p1662730329258409) by @jomarieminney on WordPress Slack. The current placement for the link to make.w.org appears to be unintuitive.

I would support adding a Contribute link as the first item under Community, linking to the same location, and doing something similar for the other submenus too. The first items would then link to the same location as the respective top-level items, while having a different label to avoid repetition. That would be consistent with how the WordPress admin menu works :slightly_smiling_face:

**Comment by iandunn** [comment]
I reported this upstream in https://github.com/WordPress/gutenberg/issues/44134
