### ISSUE TITLE
The header search bar button is out of place.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-mu-plugins#275]
The search bar closing button seems broken when viewing https://wordpress.org/about/.

<img width="428" alt="Screen Shot 2022-09-19 at 10 20 01 AM" src="https://user-images.githubusercontent.com/1657336/190936769-875116a0-100d-4ad8-9809-7c9f28732a12.png">

## Environment
MacOs
Chrome: Version 105.0.5195.125 (Official Build) (x86_64)

**Comment by ryelle** [comment]
This looks to be related to the fix I pushed last week for mobile styles: https://github.com/WordPress/wporg-mu-plugins/commit/385f134f7c131d6ffaa6ec3e426079d5f24d70f2

**Comment by StevenDufresne** [comment]
Is it possible that this introduced a different issue? 

I am unable to open the search bar on https://wordpress.org/showcase/.

Affected Browsers:
Safari, Firefox, Chrome
