### ISSUE TITLE
Unable to open search control on /showcase.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-mu-plugins#281]
Clicking on the magnifying glass does not open the search bar as expected on wordpress.org/showcase. It seems to work properly on other pages.

Related: https://github.com/WordPress/wporg-mu-plugins/issues/275

## Screenshot
![Screen Capture on 2022-09-21 at 16-17-00](https://user-images.githubusercontent.com/1657336/191439643-0dfdb870-52b3-44a9-802b-386df1653214.gif)

## Browsers 
Safari, Chrome, FireFox

**Comment by outdoor2kode** [comment]
~It seems to work on the sandbox (revision: r19296)~

![Screen Capture on 2022-09-21 at 15-28-57](https://user-images.githubusercontent.com/18050944/191442154-3377323e-d669-4664-8bf4-82fd016d3f28.gif)

#### Update

It doesn't work after executing `svnup-all`, previously I only updated in `mu-plugins`.

**Comment by outdoor2kode** [comment]
These pages also have problems opening search control:

https://wordpress.org/five-for-the-future/
https://wordpress.org/photos/
https://make.wordpress.org/
https://wordpress.org/support/forums/
https://wordpress.org/support/
https://wordpress.org/openverse/
https://wordpress.org/plugins/
https://wordpress.org/themes/

**Comment by ryelle** [comment]
The difference is that Gutenberg is not active on those sites, so it doesn't have the modal script. I think that's also part of the issue I found in #275, where I _thought_ the problem was classic theme vs block theme.

To avoid these kinds of conflicts, we should network activate Gutenberg.

**Comment by ryelle** [comment]
With gutenberg network activated, the search opens correctly on all the sites 👍🏻
