### ISSUE TITLE
Profile Bar is not looking proper after login

### ISSUE THREAD

**Issue by varshil-doshi** [WordPress/wporg-mu-plugins#282]
Hello Team,

When we Login and open the Profile bar, there is a gap coming between 2 sections. For better understanding I have attached the screenshot below:

![CleanShot 2022-09-21 at 16 57 44](https://user-images.githubusercontent.com/94299018/191492605-5d0a5a7d-fbd7-4b82-9c3b-5c632aa4ff95.png)

Thank you.

**Comment by ryelle** [comment]
Fixed in #283
