### ISSUE TITLE
Adjust vertical position of the navigation arrows

### ISSUE THREAD

**Issue by javierarce** [WordPress/wporg-mu-plugins#287]
Currently, the chevrons in the navigation appear a bit too high, we should lower them. 

### Current
<img width="652" alt="before" src="https://user-images.githubusercontent.com/4933/193040304-f9e88084-4d07-4948-af8e-7d2fde9c23fc.png">

### Fixed
<img width="652" alt="after" src="https://user-images.githubusercontent.com/4933/193040301-9032a001-3df4-4ddc-b316-128a29fb8a2f.png">

Setting the `line-height` to `0` to the `.wp-block-navigation-submenu__toggle` seems to do the trick.

**Comment by ryelle** [comment]
Fixed in https://github.com/WordPress/wporg-mu-plugins/commit/5bc78e5875b23859e3d6f949ffa976f3d9c8d5ea.
