### ISSUE TITLE
Support using header in widget

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#288]
https://fr.wordpress.org/support/ has the global header in a widget (the one that comes after `Résolution des problèmes`), but it doesn't currently work. I'm guessing that it did at one point though, and it seems like a valid use case.

Today it was causing a fatal error because `header.php` was being `require`'d twice, which re-defines `recursive_menu()`. I switched that to `require_once` in b108d4401354b588548842d3377e7fc3f8e33044 as a short term fix.

Long term, a better fix is probably to move `recursive_menu()` into `blocks.php` and switch back to a plain `require`. That would make `header.php` a pure view file rather than a mix of View and Model. I briefly tried that, but it seems like there's some additional work needed, since the output was still blank.

What do folks think about supporting that use case?

**Comment by ryelle** [comment]
I'm not sure I can see a valid case for having the header block in a widget… or available at all, honestly. It's encoded into the templates, so it shouldn't be needed. What was the valid use case you were thinking of?

If we decide to disable it, we can add `"supports: { "inserter": false }` to the `block.json` (for both header & footer).

**Comment by iandunn** [comment]
Er, that's a good point, I was initially thinking that [the page](https://fr.wordpress.org/support/) was using it to link to the _English_ versions of all the main pages, to fill in gaps where things weren't translated, etc. 

In that context, the _styles_ didn't make sense, but the _menu content_ did. I just realized that they wouldn't get the English versions, though, they'd just get the same `get_rosetta_menu_items()` as the header has.

So, yeah, I think you're right 👍🏻
