### ISSUE TITLE
Preload required font subsets for rosetta sites global header

### ISSUE THREAD

**Issue by outdoor2kode** [WordPress/wporg-mu-plugins#293]
See https://github.com/WordPress/wporg-mu-plugins/pull/247/commits/449df49d14f77a86ac75c41de671f891317bc93b#r995103206

**Comment by ryelle** [comment]
If you do try something like https://github.com/WordPress/wporg-main-2022/issues/136#issuecomment-1278192526, I think you'll also want to split out [the `*-ext` subsets here](https://github.com/WordPress/wporg-mu-plugins/blob/43252c27f1a6b65582a6703a816ffad13482ff0c/mu-plugins/global-fonts/index.php#L116). Not all languages require the ext versions, for example ru.w.org & bg.w.org only load `latin` & `cyrillic`, but kk.w.org also loads `cyrillic-ext`. It took a few tries to find one that also loaded `ext` :)

Similarly, it sounds like greek-ext might only be used for [writing ancient greek](https://en.wikipedia.org/wiki/Greek_Extended)? Not confident about that, but if we're splitting them out intentionally, we shouldn't bundle them again when preloading.
