### ISSUE TITLE
All items in submenu bold when using new theme

### ISSUE THREAD

**Issue by bph** [WordPress/wporg-mu-plugins#306]
Javier noted: "All the links in the Learn submenu in the navigation are in bold"
![Screen Shot 2022-11-21 at 09 54 17](https://user-images.githubusercontent.com/39980/203085786-caad96bb-5857-46d2-b5dd-243e450cfd81.png)

cc: @javierarce  @jasmussen

**Comment by ryelle** [comment]
Looks like this is an issue in the global-header itself, since I see the same bug on https://wordpress.org/download/ — I'm going to transfer this issue to that repo.
