### ISSUE TITLE
Add header/footer variation for white text on charcoal-1

### ISSUE THREAD

**Issue by bengreeley** [WordPress/wporg-mu-plugins#308]
The Enterprise website needs the charcoal-1 background color to be set in the header and footer, which currently isn't supported.

Created PR to add variation. @ryelle @StevenDufresne  let me know if this needs any changes. It works well for me locally, but my local has had a few gremlins, so I'd love a second set of eyes.
https://github.com/WordPress/wporg-mu-plugins/pull/307

**Comment by ryelle** [comment]
Just for consistency, I'd like to confirm that this is really needed from design — for example, the download counter is also a dark page, but it uses `charcoal-2` as the main background, which matches the default dark header. Is it possible Enterprise could also use this, or do you think we'll need a `charcoal-1` header for more pages?  @jasmussen @javierarce 

Here's a comparison of the existing dark header + background combo on [the download counter](https://wordpress.org/download/counter/).

| Download Counter | Enterprise |
|-----|-------|
| ![dlc](https://user-images.githubusercontent.com/541093/206731397-1bddb9af-0596-457e-bf7d-bcd45fd9d198.png) | ![ent](https://user-images.githubusercontent.com/541093/206731025-1e52e878-a2cf-4699-9e59-a5f700ec53e8.png) |

Edit: What I'm trying to avoid here is an arbitrary set of header colors, all slightly different.

**Comment by jasmussen** [comment]
I would think using charcoal-2 can work, but I'd let @panchovm confirm.

**Comment by fcoveram** [comment]
Let's use the existing dark header. The `charcoal-1` is a mockup error. Thanks for the ping.

**Comment by ryelle** [comment]
Thanks! I'll close this issue then.
