### ISSUE TITLE
Update breadcrumb hover color

### ISSUE THREAD

**Issue by javierarce** [WordPress/wporg-mu-plugins#312]
While reviewing [a PR in the Documentation repo](https://github.com/WordPress/wporg-documentation-2022/pull/19) we noticed the hover styles of the breadcrumb items appear with a lighter opacity. 

Unless we decide otherwise, they should appear with full opacity. I've updated the WordPress.org Design Library [with some examples](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?node-id=848%3A1756&t=br5sK6h4d0IcaUxI-4)

![image](https://user-images.githubusercontent.com/4933/207399966-3523b829-0b52-489d-b49c-d28425dfd73d.png)

cc: @beafialho @jasmussen

**Comment by ryelle** [comment]
@javierarce I see the mockup has changed since this was created, is this ready to implement? I already had this spun up with the blueberry hover color, and was about to make the PR for it when I realized it didn't match the image anymore.

**Comment by javierarce** [comment]
Sorry about that. The first version of the image I attached to the issue had the links set in blueberry as you said, but I updated it when I realized my mistake: they should maintain the same color.

**Comment by jasmussen** [comment]
I would agree, there doesn't seem to be a ton of value in changing the color on hover. The underline is a nice touch though.

**Comment by beafialho** [comment]
I also agree these should be full opacity.
