### ISSUE TITLE
Site Breadcrumbs should collapse on mobile

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-mu-plugins#325]
We've solved the breadcrumbs wrapping on mobile in a few sites so far, https://github.com/WordPress/wporg-developer/pull/166, https://github.com/WordPress/wporg-documentation-2022/pull/19, and now https://github.com/WordPress/wporg-showcase-2022/pull/96.

Let's DRY this up and set some better defaults for the block's CSS.

**Comment by ryelle** [comment]
Came across this nesting while testing something else. We shouldn't assume any fixed number of nested items or that we can hide items at specific breakpoints, because it might need to start wrapping at 1550px wide 😱 

<img width="1673" alt="Screenshot 2023-01-30 at 3 35 32 PM" src="https://user-images.githubusercontent.com/541093/215589270-de9abef1-2c53-4caa-8ea1-2deca27a6612.png">

For reference, on the current developer site, this wraps:
<img width="603" alt="Screenshot 2023-01-30 at 3 36 21 PM" src="https://user-images.githubusercontent.com/541093/215589363-7444dd14-0944-47d3-89e8-631f7b54c461.png">

**Comment by adamwoodnz** [comment]
Just noting a new community plugin in this space https://gutenbergtimes.com/introducing-the-breadcrumbs-wordpress-block-plugin/

**Comment by StevenDufresne** [comment]
Since the breadcrumbs will be pulled into the content area and no longer compete with a variable length menu on the right, I don't think this is needed anymore, at least not in the way this ticket was imagining.

**Comment by adamwoodnz** [comment]
Temporarily reverted #437
