### ISSUE TITLE
Table Of Contents content is hidden off screen.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-mu-plugins#333]
Content in the Table of Contents control seem to be hidden 

Page: https://developer.wordpress.org/redesign-test/rest-api/reference/page-revisions/

## Screenshot

<img width="1918" alt="Screen Shot 2023-02-06 at 12 50 20 PM" src="https://user-images.githubusercontent.com/1657336/216880010-91c63eee-3fb7-46bb-b9b9-864f7efba5e7.png">

**Comment by ryelle** [comment]
It looks like there's a window of screen-height where the menu is mistakenly sticky when it should not be - on this page, it starts sticking at 902px, but really it should wait until 1030px. The code controlling this is here: https://github.com/WordPress/wporg-mu-plugins/blob/trunk/mu-plugins/blocks/table-of-contents/src/view.js
