### ISSUE TITLE
Border colors and behaviour in WordPress.org

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-mu-plugins#338]
A discussion came up on [this issue](https://github.com/WordPress/wporg-main-2022/issues/199) regarding the header and when it should have a border vs when it shouldn't. The thinking would be, whenever the header background is the same color as the cover background, there should be a border to act as a visual mark.

**The example for the header in the Hosting page:**

<img width="1318" alt="Captura de ecrã 2023-02-14, às 15 46 06" src="https://user-images.githubusercontent.com/65220155/218787735-29f9ee60-13c6-44aa-b7d4-86f7ab21f41d.png">

**Same for the footer.**

<img width="1317" alt="Captura de ecrã 2023-02-14, às 15 46 57" src="https://user-images.githubusercontent.com/65220155/218787745-e30f34c6-68f0-4b2f-8070-98ee8cebe3ac.png">

**Another example with the header and cover in black as well, there should be a white border with opacity between them.**

<img width="1317" alt="Captura de ecrã 2023-02-14, às 15 44 56" src="https://user-images.githubusercontent.com/65220155/218787779-93ce6598-12e4-4157-9cbe-9b0bddad9331.png">

**Here's an example with coloured backgrounds:**

<img width="1318" alt="Captura de ecrã 2023-02-14, às 15 45 41" src="https://user-images.githubusercontent.com/65220155/218789093-6fb021c0-1da8-4bfc-849a-6fb409ec67cc.png">

<img width="1317" alt="Captura de ecrã 2023-02-14, às 15 53 31" src="https://user-images.githubusercontent.com/65220155/218789321-66d427e6-b61a-475b-862f-ec16309d1367.png">

There may be exceptions depending on the concept of the design (such as [About](https://wordpress.org/about/)) where separators don't have opacity, or thumbnails that could require a bit more opacity, but after a few tests I think 10% opacity for header and footer could work. What do you think @WordPress/meta-design @marko-srb?

**Comment by jasmussen** [comment]
The fewer exceptions the better, of course, we might even find we can do without them. But yes, sounds good.

**Comment by marko-srb** [comment]
I think having a 10% opacity there works well. Bea and I went over this issue for one additional page and it seems like a necessary element to me. Afterward, I tested various opacity lines on different pages and I think 10% works best, plus that we need that line. Hope this helps.
