### ISSUE TITLE
Assign `active-menu-item` dynamically

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#35]
part of #38

right now it's hardcoded, but we'll need it to be set based on the current site

my first thought is something like this:

```php
// in `render_global_header()`, after all menu items have been added
$menu_items = set_current_item_class( $menu_items );
```

...and then that function would do something like:

```php
foreach ( $menu_items as $item ) {
	if ( $current_url === $item->url ) {
		$item->classes[] = 'current-menu-item';
	}
}
```

The logic will need to be more complex than that, to account for child pages etc. There may be some existing Core or `functions-global.php` code we can adapt.

**Comment by dd32** [comment]
Fixed via #68
