### ISSUE TITLE
Navigation: Hide the adminbar in most cases, explore how to better integrate the register/login links

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-mu-plugins#355]
From WordPress/wporg-main-2022#221:

>   (Mobile) When a category is active (ie:Learn), the whole category of nav instances move position.

This shift is likely caused by the adminbar. Compare the homepage:

<img width="492" alt="Screenshot 2023-03-27 at 16 10 33" src="https://user-images.githubusercontent.com/1204802/227964884-2a18aa11-f893-437b-a64f-f596609096b7.png">

with the Learn section:

<img width="492" alt="Screenshot 2023-03-27 at 16 10 41" src="https://user-images.githubusercontent.com/1204802/227964963-bd86d58b-2ddf-4d06-adcc-3f4bb91cbeae.png">

This issue is the same on desktop.

In general, the admin-bar is an affordance created for editors or members of the site, which presumably would be very few. In that light, it seems we should hide the admin-bar by default, and only show it in a few notable exceptions. 

For example, it might be fine to show it if you are a member, and are logged in. In this case, it should be shown across the whole site, except if it breaks the layout. But it should be shown with a #24282e background color, instead of the default #1b2024.

For some of the community sections like the Make sites, In the forums, or where community members expect to see the existing interface, it could also be okay to show it. In those sections, mainly the Log in and Register links are pertinent for logged out users, and as we get a chance to redesign those sections, it would be good to omit the adminbar in that state, and show the login/register links in a different context and affordance which might also afford better context for when and why you should. As an example, these are mockups made for the Pattern Directory redesign, which integrate the login link into the breadcrumb bar. Logged out:

<img width="1320" alt="Header, logged out" src="https://user-images.githubusercontent.com/1204802/228230547-caf5c384-06f0-4d6b-ae09-bebedbf42bfe.png">

Logged in:

<img width="1320" alt="Group 1369" src="https://user-images.githubusercontent.com/1204802/228230571-90388c5f-21c5-4178-b15f-bf4cf82d9767.png">

Outside of the typographic orphan caused by the word "improved?" in this screenshot (which we should fix separately, can just add a linebreak after "helpful?"), [this section of the documentation](https://wordpress.org/documentation/article/first-steps-with-wordpress-block-editor/) is nevertheless a good example of how a log-in link can be shown with context, without the need for an adminbar:

<img width="728" alt="Screenshot 2023-03-27 at 16 18 14" src="https://user-images.githubusercontent.com/1204802/227968544-b49232f7-e47c-4b7f-bea8-89b3ff89510e.png">

**Comment by ryelle** [comment]
Moved this over from wporg-main-2022 since the admin bar is controlled in https://github.com/WordPress/wporg-mu-plugins/blob/trunk/mu-plugins/blocks/global-header-footer/admin-bar.php

> But it should be shown with a #24282e background color, instead of the default #1b2024.

That's `--wp--preset--color--charcoal-2` — currently used as the hover background for admin bar items. Should this flip to match the admin bar, where it's `--wp--preset--color--charcoal-2` by default, and `--wp--preset--color--charcoal-5` (aka Nero, #1c2024) on hover?

**Comment by jasmussen** [comment]
Just for clarity, #234 is the more important one, seeing the adminbar should be the exception. When you do see it, it should have the same background and hover colors as the main header toolbar, something along these lines:

<img width="640" alt="Screenshot 2023-03-28 at 09 09 21" src="https://user-images.githubusercontent.com/1204802/228156916-3b05c545-7414-44b2-ae0e-d2619955a164.png">

That does sound like the inverted behavior you are describing, yes. Mainly we want to avoid that "stacked" feeling.

**Comment by bengreeley** [comment]
For the admin/login bar appearing on too many pages, I'd suggest we inverse the logic that is in [this function](https://github.com/WordPress/wporg-mu-plugins/blob/0ffa239f837a86fc17e1e244d725378fd2ebb84d/mu-plugins/blocks/global-header-footer/admin-bar.php#L19), which _hides_ the admin bar on the homepage and download page. Since we only want the admin bar appearing on select pages or sections, it seems it should be false by default, and on specific pages we set it to true. 

These are the sections and pages that would make sense to me to show the login bar by default. Feel free to add any others I may have missed. I listed the directories, but each one has obvious in-page login buttons so it may not be needed there.
* If user is logged in (any page)
* [Make WordPress](https://make.wordpress.org/)
* [Photo Directory](https://wordpress.org/photos/) (though there are logical 'log in' buttons on the page)
* [Theme Directory](https://wordpress.org/themes/)
* [Plugin Directory](https://wordpress.org/plugins/)
* [Pattern Directory](https://wordpress.org/patterns/)
* [Five for the Future](https://wordpress.org/five-for-the-future/)
* [Learn WordPress](https://learn.wordpress.org/)
* [Forums](https://wordpress.org/support/forums/)
* [Developers](https://developer.wordpress.org/)
* [Documentation](https://wordpress.org/documentation/)

**Comment by ryelle** [comment]
> Just for clarity, https://github.com/WordPress/wporg-mu-plugins/pull/234 is the more important one, seeing the adminbar should be the exception.

Yes, `https://github.com/WordPress/wporg-main-2022/issues/234` is this issue, it's just been moved to the correct repo.

**Comment by jasmussen** [comment]
Thanks for the repo cleanup!

**Comment by ryelle** [comment]
I looked into flipping the logic in `should_show_admin_bar`, but realized something else was overriding the value— we have a plugin "Logged Out Admin Bar" active on some sites, so each site is controlling that individually.

So instead, I'm going to update `should_show_admin_bar` to default to hide the admin bar unless the user is logged in & has permissions on the current site, then each site can opt in to showing the admin bar by activating this plugin.

<details>
<summary>Sites where logged-out-admin-bar is active</summary>

```
+---------+--------------------------------------------+
| blog_id | url                                        |
+---------+--------------------------------------------+
| 3       | https://wordpress.org/showcase/            |
| 4       | https://make.wordpress.org/                |
| 5       | https://make.wordpress.org/design/         |
| 6       | https://make.wordpress.org/core/           |
| 7       | https://learn.wordpress.org/               |
| 8       | https://wordpress.org/news/                |
| 9       | https://make.wordpress.org/themes/         |
| 10      | https://make.wordpress.org/systems/        |
| 14      | https://make.wordpress.org/accessibility/  |
| 15      | https://make.wordpress.org/docs/           |
| 17      | https://make.wordpress.org/plugins/        |
| 19      | https://make.wordpress.org/polyglots/      |
| 21      | https://make.wordpress.org/support/        |
| 24      | https://make.wordpress.org/mobile/         |
| 25      | https://make.wordpress.org/summit/         |
| 27      | https://make.wordpress.org/meta/           |
| 28      | https://make.wordpress.org/training/       |
| 29      | https://make.wordpress.org/updates/        |
| 30      | https://make.wordpress.org/community/      |
| 33      | https://developer.wordpress.org/           |
| 34      | https://make.wordpress.org/test/           |
| 35      | https://wordpress.org/themes/              |
| 161     | https://test.wordpress.org/                |
| 189     | https://test.wordpress.org/support/        |
| 328     | https://make.wordpress.org/tv/             |
| 332     | https://it.wordpress.org/support/          |
| 351     | https://translate.wordpress.org/           |
| 352     | https://ary.wordpress.org/support/         |
| 357     | https://make.wordpress.org/marketing/      |
| 358     | https://make.wordpress.org/supportadmins/  |
| 367     | https://wordpress.org/plugins/             |
| 383     | https://pt.wordpress.org/support/          |
| 386     | https://emoji.wordpress.org/support/       |
| 389     | https://af.wordpress.org/support/          |
| 390     | https://am.wordpress.org/support/          |
| 391     | https://id.wordpress.org/support/          |
| 392     | https://mya.wordpress.org/support/         |
| 393     | https://ja.wordpress.org/support/          |
| 394     | https://ru.wordpress.org/support/          |
| 395     | https://de.wordpress.org/support/          |
| 396     | https://bs.wordpress.org/support/          |
| 397     | https://th.wordpress.org/support/          |
| 398     | https://cn.wordpress.org/support/          |
| 399     | https://ak.wordpress.org/support/          |
| 400     | https://an.wordpress.org/support/          |
| 401     | https://ar.wordpress.org/support/          |
| 402     | https://arq.wordpress.org/support/         |
| 403     | https://ug.wordpress.org/support/          |
| 404     | https://tw.wordpress.org/support/          |
| 405     | https://bg.wordpress.org/support/          |
| 406     | https://sr.wordpress.org/support/          |
| 407     | https://hr.wordpress.org/support/          |
| 408     | https://nl.wordpress.org/support/          |
| 409     | https://he.wordpress.org/support/          |
| 410     | https://ka.wordpress.org/support/          |
| 411     | https://fi.wordpress.org/support/          |
| 412     | https://mk.wordpress.org/support/          |
| 413     | https://ca.wordpress.org/support/          |
| 414     | https://sk.wordpress.org/support/          |
| 415     | https://pl.wordpress.org/support/          |
| 416     | https://ro.wordpress.org/support/          |
| 417     | https://es.wordpress.org/support/          |
| 418     | https://br.wordpress.org/support/          |
| 419     | https://wordpress.org/support/             |
| 420     | https://sq.wordpress.org/support/          |
| 421     | https://hy.wordpress.org/support/          |
| 422     | https://rup.wordpress.org/support/         |
| 423     | https://frp.wordpress.org/support/         |
| 424     | https://as.wordpress.org/support/          |
| 425     | https://ast.wordpress.org/support/         |
| 426     | https://az.wordpress.org/support/          |
| 427     | https://az-tr.wordpress.org/support/       |
| 428     | https://bcc.wordpress.org/support/         |
| 429     | https://eu.wordpress.org/support/          |
| 430     | https://bel.wordpress.org/support/         |
| 431     | https://bn.wordpress.org/support/          |
| 432     | https://bre.wordpress.org/support/         |
| 433     | https://ceb.wordpress.org/support/         |
| 434     | https://zh-hk.wordpress.org/support/       |
| 435     | https://co.wordpress.org/support/          |
| 436     | https://cs.wordpress.org/support/          |
| 437     | https://et.wordpress.org/support/          |
| 438     | https://eo.wordpress.org/support/          |
| 439     | https://uz.wordpress.org/support/          |
| 440     | https://dzo.wordpress.org/support/         |
| 480     | https://bg.wordpress.org/team/             |
| 481     | https://de.wordpress.org/team/             |
| 484     | https://ru.wordpress.org/team/             |
| 485     | https://es.wordpress.org/team/             |
| 486     | https://ja.wordpress.org/team/             |
| 487     | https://nl.wordpress.org/team/             |
| 488     | https://fr.wordpress.org/team/             |
| 489     | https://ar.wordpress.org/team/             |
| 490     | https://br.wordpress.org/team/             |
| 491     | https://it.wordpress.org/team/             |
| 492     | https://he.wordpress.org/team/             |
| 494     | https://uk.wordpress.org/support/          |
| 495     | https://lv.wordpress.org/team/             |
| 496     | https://nb.wordpress.org/team/             |
| 497     | https://uk.wordpress.org/team/             |
| 498     | https://tr.wordpress.org/team/             |
| 499     | https://id.wordpress.org/team/             |
| 500     | https://ko.wordpress.org/team/             |
| 501     | https://fi.wordpress.org/team/             |
| 502     | https://hr.wordpress.org/team/             |
| 503     | https://da.wordpress.org/team/             |
| 504     | https://ca.wordpress.org/team/             |
| 505     | https://sr.wordpress.org/team/             |
| 506     | https://pt.wordpress.org/team/             |
| 507     | https://fa.wordpress.org/team/             |
| 509     | https://eo.wordpress.org/team/             |
| 510     | https://tw.wordpress.org/team/             |
| 511     | https://hi.wordpress.org/team/             |
| 512     | https://sv.wordpress.org/team/             |
| 513     | https://hu.wordpress.org/team/             |
| 515     | https://eu.wordpress.org/team/             |
| 516     | https://el.wordpress.org/team/             |
| 517     | https://ms.wordpress.org/team/             |
| 518     | https://pl.wordpress.org/team/             |
| 519     | https://vi.wordpress.org/team/             |
| 520     | https://sq.wordpress.org/team/             |
| 521     | https://cs.wordpress.org/team/             |
| 522     | https://sk.wordpress.org/team/             |
| 523     | https://cl.wordpress.org/team/             |
| 524     | https://ve.wordpress.org/team/             |
| 525     | https://pe.wordpress.org/team/             |
| 526     | https://ro.wordpress.org/team/             |
| 527     | https://cy.wordpress.org/team/             |
| 528     | https://nn.wordpress.org/team/             |
| 529     | https://ka.wordpress.org/team/             |
| 530     | https://gl.wordpress.org/team/             |
| 531     | https://sl.wordpress.org/team/             |
| 532     | https://hy.wordpress.org/team/             |
| 533     | https://gu.wordpress.org/team/             |
| 534     | https://en-gb.wordpress.org/team/          |
| 535     | https://is.wordpress.org/team/             |
| 536     | https://te.wordpress.org/team/             |
| 537     | https://gd.wordpress.org/team/             |
| 538     | https://en-ca.wordpress.org/team/          |
| 539     | https://mr.wordpress.org/team/             |
| 540     | https://bn.wordpress.org/team/             |
| 541     | https://az.wordpress.org/team/             |
| 542     | https://bo.wordpress.org/team/             |
| 543     | https://es-ar.wordpress.org/team/          |
| 544     | https://en-au.wordpress.org/team/          |
| 545     | https://km.wordpress.org/team/             |
| 546     | https://lt.wordpress.org/team/             |
| 548     | https://es-mx.wordpress.org/team/          |
| 549     | https://oci.wordpress.org/team/            |
| 550     | https://de-ch.wordpress.org/team/          |
| 551     | https://fr-be.wordpress.org/team/          |
| 552     | https://fr-ca.wordpress.org/team/          |
| 553     | https://szl.wordpress.org/team/            |
| 554     | https://en-za.wordpress.org/team/          |
| 555     | https://en-nz.wordpress.org/team/          |
| 556     | https://ary.wordpress.org/team/            |
| 557     | https://es-gt.wordpress.org/team/          |
| 558     | https://th.wordpress.org/team/             |
| 559     | https://hau.wordpress.org/team/            |
| 561     | https://xho.wordpress.org/team/            |
| 562     | https://mr.wordpress.org/support/          |
| 565     | https://hi.wordpress.org/support/          |
| 566     | https://make.wordpress.org/cli/            |
| 567     | https://ur.wordpress.org/team/             |
| 568     | https://ne.wordpress.org/team/             |
| 570     | https://ur.wordpress.org/support/          |
| 575     | https://sv.wordpress.org/support/          |
| 581     | https://af.wordpress.org/team/             |
| 583     | https://cn.wordpress.org/team/             |
| 585     | https://zh-hk.wordpress.org/team/          |
| 587     | https://da.wordpress.org/support/          |
| 592     | https://tl.wordpress.org/support/          |
| 594     | https://tl.wordpress.org/team/             |
| 595     | https://make.wordpress.org/security/       |
| 599     | https://es-cr.wordpress.org/team/          |
| 602     | https://nl-be.wordpress.org/team/          |
| 605     | https://skr.wordpress.org/team/            |
| 607     | https://lug.wordpress.org/team/            |
| 619     | https://mfe.wordpress.org/team/            |
| 625     | https://el.wordpress.org/support/          |
| 641     | https://gax.wordpress.org/team/            |
| 643     | https://cor.wordpress.org/team/            |
| 644     | https://es-uy.wordpress.org/team/          |
| 648     | https://es-hn.wordpress.org/team/          |
| 652     | https://pcm.wordpress.org/team/            |
| 653     | https://de-at.wordpress.org/team/          |
| 655     | https://kaa.wordpress.org/team/            |
| 657     | https://es-do.wordpress.org/team/          |
| 659     | https://lij.wordpress.org/team/            |
| 661     | https://pt-ao.wordpress.org/team/          |
| 662     | https://pt-ao.wordpress.org/support/       |
| 665     | https://bn-in.wordpress.org/team/          |
| 667     | https://fr.wordpress.org/support/          |
| 668     | https://wordpress.org/five-for-the-future/ |
| 670     | https://ve.wordpress.org/support/          |
| 672     | https://es-mx.wordpress.org/support/       |
| 673     | https://vi.wordpress.org/support/          |
| 676     | https://hsb.wordpress.org/team/            |
| 677     | https://dsb.wordpress.org/team/            |
| 678     | https://pap-cw.wordpress.org/team/         |
| 679     | https://pap-aw.wordpress.org/team/         |
| 681     | https://wol.wordpress.org/team/            |
| 683     | https://mai.wordpress.org/team/            |
| 685     | https://pcd.wordpress.org/team/            |
| 686     | https://ko.wordpress.org/support/          |
| 687     | https://es-ar.wordpress.org/support/       |
| 689     | https://fon.wordpress.org/team/            |
| 691     | https://vec.wordpress.org/team/            |
| 693     | https://zgh.wordpress.org/team/            |
| 695     | https://es-ec.wordpress.org/team/          |
| 697     | https://learn.wordpress.org/meta/          |
| 698     | https://fa.wordpress.org/support/          |
| 699     | https://wordpress.org/patterns/            |
| 702     | https://wordpress.org/photos/              |
| 703     | https://make.wordpress.org/openverse/      |
| 704     | https://make.wordpress.org/project/        |
| 705     | https://wordpress.org/openverse/           |
| 707     | https://snd.wordpress.org/support/         |
| 708     | https://make.wordpress.org/photos/         |
| 716     | https://yor.wordpress.org/team/            |
| 717     | https://yor.wordpress.org/support/         |
| 722     | https://lmo.wordpress.org/team/            |
| 723     | https://azb.wordpress.org/team/            |
+---------+--------------------------------------------+
```

</details>

**Comment by jasmussen** [comment]
Thanks for this list and the changes. Coming back to [Ben's suggestions](https://github.com/WordPress/wporg-mu-plugins/issues/355#issuecomment-1486949594), @bengreeley can you elaborate on the reason for keeping the adminbar on these pages?

To expand a bit on my instincts here:

* If user is logged in (any page)
* [Make WordPress](https://make.wordpress.org/)
* [Forums](https://wordpress.org/support/forums/)

Agreed.

* [Photo Directory](https://wordpress.org/photos/) (though there are logical 'log in' buttons on the page)
* [Theme Directory](https://wordpress.org/themes/)
* [Plugin Directory](https://wordpress.org/plugins/)
* [Pattern Directory](https://wordpress.org/patterns/)

I would omit it from these as well. If need be, add in-page login links. The adminbar feels like the wrong place if the primary 

* [Five for the Future](https://wordpress.org/five-for-the-future/)
* [Learn WordPress](https://learn.wordpress.org/)
* [Developers](https://developer.wordpress.org/)

It makes sense to keep the adminbar here only so long as the screenshots [on pages like these refer to it](https://wordpress.org/five-for-the-future/for-individuals/). I would expect the content here to also be updated when we get a chance to refresh these pages.

In general, I see the adminbar as a vestige of WordPress itself, and not as a core element of a refreshed site design. With a few exceptions, I would expect few of the refreshed pages to keep the adminbar, even for log-in, which I think would be better served in-page.

The main thing we want to avoid is that suddenly the header grows taller, because the adminbar appears. This is okay when logged in, as then it's a permanent fixture, preventing subsequent layout shifts.

* [Documentation](https://wordpress.org/documentation/)

The adminbar appears to not be present here when I'm logged out. That's good, because we have this call to action in case you want to contribute:

<img width="758" alt="Screenshot 2023-04-26 at 14 32 37" src="https://user-images.githubusercontent.com/1204802/234575712-ccfd760d-ba6f-460e-8698-d894088fe4c7.png">

However, the adminbar is missing even though I am logged in. Perhaps it should follow the heuristic above, to always be visible when logged in? CC: @ryelle

**Comment by ryelle** [comment]
> However, the adminbar is missing even though I am logged in. Perhaps it should follow the heuristic above, to always be visible when logged in?

If the  "always show" plugin is disabled, it only shows up if you have a role on the site. So since your user can't add/edit content or moderate comments, there's no reason to see the admin bar. We could change that to "anyone logged in at all", if you think that would be better.

**Comment by bengreeley** [comment]
For the directories and other sites you listed, I don't have a strong feeling about having the 'Log in' button accessible in the toolbar as long as we have a straightforward way for people to log in when they need to do so. I agree, it's a bit confusing for folks who may assume that they are logging into WordPress vs functionality on the .org website.

If we can show it when somebody is already logged in so there's an easy way to log out and create posts and take other actions, that would work for me.

**Comment by jasmussen** [comment]
> If the "always show" plugin is disabled, it only shows up if you have a role on the site. So since your user can't add/edit content or moderate comments, there's no reason to see the admin bar. We could change that to "anyone logged in at all", if you think that would be better.

I guess the main issue is to avoid the layout shift for the overwhelming majority of visitors that do not have edit access, and a layout shift for the tiny subset that is logged in is probably acceptable.

That said I would still personally show the adminbar here as well, if we continue to show it on other sites when I'm logged in. Even if I can't edit, I can log out, or edit my profile.
