### ISSUE TITLE
Navigation: Active states isn’t consistent

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-mu-plugins#358]
From #221:

>  (Mobile) The behavior of active instances isn’t consistent (ie: Get WP vs Learn WP).

This also affects desktop. Here's Learn, with both the Learn menu item, and the ancestor item active:

<img width="229" alt="Screenshot 2023-03-28 at 09 57 32" src="https://user-images.githubusercontent.com/1204802/228168500-13ba9108-2480-4363-bcf4-7268a2afd44a.png">

Here's Download, with no items active, even if conceptually it should be "Get WordPress" that's active:

<img width="352" alt="Screenshot 2023-03-28 at 09 57 43" src="https://user-images.githubusercontent.com/1204802/228168748-6fa61b67-cd44-4318-bbe8-adf40022c189.png">

Consider also [#229](https://github.com/WordPress/wporg-main-2022/issues) as far as highlighting the ancestor.

**Comment by jasmussen** [comment]
My apologies, I created this issue in the wrong repository. @StevenDufresne or @ryelle are you able to move this to `wporg-main-2022`?

**Comment by ryelle** [comment]
This is the correct place for these global header issues.

The outcome you want is for "Get WordPress"/Download to be highlighted, mirroring the behavior of Learn, is that right?

**Comment by jasmussen** [comment]
> The outcome you want is for "Get WordPress"/Download to be highlighted, mirroring the behavior of Learn, is that right?

If we keep the dropdown called "Download & Extend" with a download link inside, then yes. But just for awareness, the ancestor might need consideration per https://github.com/WordPress/wporg-mu-plugins/issues/370, and there's https://github.com/WordPress/wporg-mu-plugins/issues/360 for download. Separate conversations. Thanks for the fix!
