### ISSUE TITLE
Navigation: Signal external links

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-mu-plugins#359]
At the moment, the main navigation contains a mix of internal and external links. In this case, internal means the link takes you to a section that maintains the global WP.org header, and external means it takes you to one that does not. 

We should sort items here according to their destination, and include an indicator when they are external. Eg. instead of this:

<img width="205" alt="Screenshot 2023-03-28 at 10 06 05" src="https://user-images.githubusercontent.com/1204802/228170780-2afcb626-3548-4ee5-b8b4-9c0d70c4ca4e.png">

We should do this:

<img width="280" alt="Download" src="https://user-images.githubusercontent.com/1204802/228171641-9c675dfd-fde8-4f03-bb51-2a7ac6caa628.png">

Additional sections:

<img width="280" alt="Learn" src="https://user-images.githubusercontent.com/1204802/228172498-55430588-82c2-4f73-8b76-396bfefd64e0.png">

<img width="280" alt="Community" src="https://user-images.githubusercontent.com/1204802/228172500-8fe1238b-ef48-4358-bd9e-91d6c5d555ac.png">

<img width="280" alt="About" src="https://user-images.githubusercontent.com/1204802/228172513-52d70f92-9e0e-411e-b8ec-4eaf962feb3f.png">

<img width="280" alt="Download" src="https://user-images.githubusercontent.com/1204802/228172528-ecb26e5b-eee8-40aa-b6be-bf22a3b80cf0.png">

That's the unicode northeast arrow: `↗`.

The above do not preclude separate changes to the menus, we may want to rename or move a few items around still, a separate issue will be opened if need be. But just as a baseline, this would make the navigation clearer.

**Comment by bengreeley** [comment]
Hey @renintw do you have any updates on the progress of this task?
