### ISSUE TITLE
Navigation: Mobile overlay "Get WP" button details

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-mu-plugins#363]
Get WordPress is a standard blue button in the desktop navigation:

<img width="1113" alt="Screenshot 2023-03-27 at 12 45 34" src="https://user-images.githubusercontent.com/1204802/227920358-3d39662a-1750-4dcd-8ff0-f09ed5911cb0.png">

In the mobile overlay, it becomes full width, and has a larger font size:

<img width="517" alt="Screenshot 2023-03-27 at 12 45 24" src="https://user-images.githubusercontent.com/1204802/227920404-cee5c28c-4cf3-4f79-b777-2a6dd57d5db1.png">

Can we use the same style of button inside the overlay? I.e. same height, font size, perhaps left aligned?

**Comment by ryelle** [comment]
> Can we use the same style of button inside the overlay?

I think it was designed to be larger to be a bigger tap-target, but if that's not an issue I'm sure we can remove the small-screen styles.

**Comment by jasmussen** [comment]
I think we should remove the extra styles, and allow the sizes to be egalitarian across. One separate issue, not actually ticketed yet, is that downloading WordPress on your phone is not that useful:

<img width="600" alt="Screenshot 2023-03-28 at 08 55 12" src="https://user-images.githubusercontent.com/1204802/228153182-070d758b-0618-4339-acf2-12e5950ab6d9.png">

It should still be allowed, naturally, but it might be worthwhile to actually de-emphasize the file download button on a physical device, in favor of something else, whether "explore hosts" or "email me a link". What do you think, worth a separate issue?

<img width="600" alt="Screenshot 2023-03-28 at 08 55 12" src="https://user-images.githubusercontent.com/1204802/228153599-3eabfd5d-ff00-48eb-8950-e620ead8d4e7.png">

**Comment by ryelle** [comment]
> I think we should remove the extra styles, and allow the sizes to be egalitarian across.

Sounds good.

> One separate issue, not actually ticketed yet, is that downloading WordPress on your phone is not that useful:

This "Get WordPress" button links off to the download page, it doesn't download WP itself. Once you're at `/download/` there are other actions you can take if you don't want the literal files. If you want to change the download page, that would be a separate discussion.

**Comment by jasmussen** [comment]
Good thought, I created https://github.com/WordPress/wporg-main-2022/issues/249 for this.
