### ISSUE TITLE
Language banner: list languages equally without parenthesis.

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-mu-plugins#365]
This is the language bar:

<img width="1260" alt="Screenshot 2023-03-28 at 14 35 16" src="https://user-images.githubusercontent.com/1204802/228237896-68fa513e-6ee6-40ec-9104-4d3e9d989033.png">

We should rephrase the wording to be agnostic. I.e. instead of:

> WordPress is also available in [Dansk](https://da.wordpress.org/) (also [Svenska](https://sv.wordpress.org/)).

it should be

> WordPress is also available in [Dansk](https://da.wordpress.org/), [Svenska](https://sv.wordpress.org/).

Instead of:

> WordPress también está disponible en [Español](https://es.wordpress.org/) (también [Català](https://ca.wordpress.org/), [galego](https://gl.wordpress.org/)).

it should be

> WordPress también está disponible en [Español](https://es.wordpress.org/), [Català](https://ca.wordpress.org/), [galego](https://gl.wordpress.org/).

**Comment by ryelle** [comment]
The string here is returned from the `lang-guess/lang-guess-ajax.php` which lives in dotorg.trac. (this is just a developer note)

**Comment by pablohoneyhoney** [comment]
In fact, a small nuance @thetinyl 

In `en` the languages are capitalized, but that isn't true for all –in `es` they aren't. So the issue is still true (needs to be consistent) but worth adding the capitalization nuance for each idiom.

**Comment by ryelle** [comment]
This is being tracked on meta.trac in these tickets [#6600](https://meta.trac.wordpress.org/ticket/6600), [#6599](https://meta.trac.wordpress.org/ticket/6599).

I left a comment with my latest work there. This string is API generated/pulled from locale databases, it's not something a content editor can update.

**Comment by ryelle** [comment]
I've deployed a fix that updates the strings used here— it should now read:

> WordPress también está disponible en <a href='https://es.wordpress.org/'>Español</a>, <a href='https://ca.wordpress.org/'>Català</a> y <a href='https://gl.wordpress.org/'>Galego</a>.
