### ISSUE TITLE
Header: Add hover style behind logo

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-mu-plugins#366]
We should add a hover style to the logo. Currently, the hover style is that of a dark background, and underlined text. We could apply that:

<img width="1320" alt="hover option 1" src="https://user-images.githubusercontent.com/1204802/227954303-911ea295-af32-4182-943e-541a7c8f9a2d.png">

- [ ] Add background color on logo hover

This is likely the best and simplest route to go, as it leans into established patterns. Be mindful that the left/right padding of the navigation menu itself needs to be increased a little, so that the logo button can have uniform padding left and right. At the moment, the logo has additional padding to the left, for positioning purposes, which would make the hover style awkward.

**Comment by ryelle** [comment]
@jasmussen Can you move the parts of this issue related to `/gutenberg/` to https://github.com/WordPress/wporg-gutenberg/? I think then the only part of this issue remaining would be adding the background color to the logo's hover state, and we can remove the "question" label.

**Comment by jasmussen** [comment]
Extracted into https://github.com/WordPress/wporg-gutenberg/issues/55
