### ISSUE TITLE
Search: Update label and placeholder, consider suggesting terms

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-mu-plugins#367]
Site wide search currently looks like this on desktop:

<img width="351" alt="Screenshot 2023-03-27 at 11 31 09" src="https://user-images.githubusercontent.com/1204802/227902108-561e1c48-6d9d-48c2-912b-7579845dfc13.png">

and like this on mobile:

<img width="512" alt="Screenshot 2023-03-27 at 11 31 01" src="https://user-images.githubusercontent.com/1204802/227902142-2f394b73-4482-42b2-abca-123d8f658b8f.png">

Outside of a few visual improvements (see also WordPress/wporg-mu-plugins#368), we can improve the label and placeholder. A few suggestions from WordPress/wporg-main-2022#221:

* Replace "Search" with "Search in WordPress" on the mobile view, with the modal open.
* The placeholder can be more suggestive, perhaps suggest the most searched terms.

**Comment by bengreeley** [comment]
Suggesting terms may be a challenge at the moment, as the current search box uses Google's search Javascript code. I suggest we look into what negative side-effects reusing Google autocomplete will produce on the global website if the Google search scripts need to be loaded on each page vs only the search page.

We do have another project in the works to replace the Google search with Elasticsearch and that could introduce some flexibility for having a more-targeted, lightweight implementation of autocomplete in the global search if need be.

**Comment by ryelle** [comment]
> Suggesting terms may be a challenge at the moment, as the current search box uses Google's search Javascript code.

**This** search box actually doesn't use google code at all, it's just a search that redirects to the google results page. Actually, it's a core search block, so really nothing fancy :)

Anyway, if we wanted to allow some _basic_ suggestion function, maybe [a datalist?](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) Since it's a native HTML feature, no JS required. It would need a set list of maybe 5-10 suggestions, rather than an arbitrary autocomplete. Definitely not the ideal solution, but could be a good iteration until we know the future of search.

I've updated the label text as part of https://github.com/WordPress/wporg-mu-plugins/pull/378, and since the placeholder/suggestion is still under discussion, I'm moving this to "Pending discussion".

**Comment by jasmussen** [comment]
Thanks, yes the input on the Google search page is going to be its own challenge.

Who can best help move forward the suggestions? My instinct is that we might want to explore some automated suggestions, such as pull a title from the docs, and suggest that.

**Comment by ryelle** [comment]
> we might want to explore some automated suggestions, such as pull a title from the docs, and suggest that.

So you're thinking more of an autocomplete, suggest something as the person types from all of wporg? I don't think we could quick-fix that, it would probably need an overhaul to the wporg search system— so I'd put that to @bengreeley to answer since he mentioned an Elasticsearch project.

If you're open to the `datalist` approach, we could give that a try now, as soon as we have a list of suggestions.

Another thing we _might_ be able to do is embed the google search in the header, but then we'd loose all the styling work we're doing in #378.

**Comment by jasmussen** [comment]
Given how little control we have over the google search, styling wise, my instinct would not go in that direction. The data list can probably work, but would also love to hear from @pablohoneyhoney in case he has input. 

I'm not thinking of an auto complete, I'm more thinking of a rotation of placeholder suggestions from the content of a particular section. So for documentation search, instead of this:

<img width="387" alt="general search" src="https://user-images.githubusercontent.com/1204802/229160585-3bcd97b7-902f-4399-808f-1ef12c407c21.png">

It could be this:

<img width="387" alt="Suggestions" src="https://user-images.githubusercontent.com/1204802/229160458-fe3f61f9-497c-4462-b42a-ffaadf604f14.png">

**Comment by ryelle** [comment]
> I'm not thinking of an auto complete, I'm more thinking of a rotation of placeholder suggestions from the content of a particular section. So for documentation search, instead of this:

Oh! okay, that's much more doable :) 

Also, I thought we were strictly talking about the header search

<img width="340" alt="Screenshot 2023-03-31 at 11 18 25 AM" src="https://user-images.githubusercontent.com/541093/229161534-e3a811e6-9dc7-4562-9bb5-1c4698ea1823.png">

which is always a global wporg search. But you're also talking about the local site searches?

<img width="852" alt="Screenshot 2023-03-31 at 11 18 28 AM" src="https://user-images.githubusercontent.com/541093/229161621-9f212950-28ee-47e9-af06-f46d99ebde04.png">
<img width="583" alt="Screenshot 2023-03-31 at 11 19 50 AM" src="https://user-images.githubusercontent.com/541093/229161803-0a7a6687-8ee4-4345-897b-f810d793c2a3.png">

So again, once we have a list of placeholders for each site, we can implement that.

I do wonder if having a suggestion like that as the placeholder would make it less clear that this is a search you can type into, and that it might be best to bring back the text label? Or switch to a text button. See also https://github.com/WordPress/wporg-parent-2021/issues/62#issuecomment-1346769551

**Comment by bengreeley** [comment]
Ah, I didn't understand the part about the _placeholder_ being what would be suggested. Thanks for clarifying. 

I'd recommend we focus on the easier label changes and implement the autocomplete placeholder logic separately since it might take a bit more planning and discussion to get it right. I agree with @ryelle that we'll want to figure out a way to avoid confusion.

**Comment by StevenDufresne** [comment]
I agree about the rotating placeholders and that they would be likely more confusing than helpful.

For me the ultimate goal is to build something like Algolia's third party search UI after we agree on the underlying search infrastructure. 

**Example**
<img width="300" alt="Screenshot 2023-04-05 at 1 18 01 PM" src="https://user-images.githubusercontent.com/1657336/229980234-caa18c95-48a0-44dd-8490-4070f45ca844.png">

If we do agree to not pursue rotating placeholders and look forward to autocompletion, it may be worth opening a new ticket for that work to help us focus.

**Comment by pablohoneyhoney** [comment]
I like the above, but perhaps let's fix the top global search first? 

i1
Label: _Search in WordPress.org_. Which we should look into incorporating to the desktop view too. 
Placeholder: _Type to search..._

i2
Consider suggestions

**Comment by ryelle** [comment]
I tried simply unhiding the label on desktop, and updating the placeholder:

| black | white | blue |
|---|---|---|
| <img width="327" alt="" src="https://user-images.githubusercontent.com/541093/230630104-3c7a6e6e-e8fe-485d-b002-81866d5d27ed.png"> | <img width="330" alt="" src="https://user-images.githubusercontent.com/541093/230630112-673eb525-9bbb-4a1f-b269-2bc444c9ab0b.png"> | <img width="325" alt="" src="https://user-images.githubusercontent.com/541093/230630442-4b012bf1-f00f-49fa-a67a-83f1b16ea6b1.png"> |
| ![black](https://user-images.githubusercontent.com/541093/230630737-362eec2c-83f4-46f3-a8d2-dd3135d0eb3d.png) | ![white](https://user-images.githubusercontent.com/541093/230630740-c27b3997-f568-4fbe-9d8c-44b18df0cd66.png) | ![blue](https://user-images.githubusercontent.com/541093/230630739-887e7063-1da2-4dcb-94dc-56846130d2ed.png) |

**Comment by bengreeley** [comment]
I think this works well with a label. The only thing that stands out to me is the text `Search in WordPress`. I could be overthinking it, but with the feedback we've heard about people being confused about the 'Log in' and 'Register' buttons, I wonder if we need to be more specific of what 'WordPress' is in this case. What do you think of 'Search in WordPress.org` or `Search WordPress.org`? That way it's clear that this is to search the website, not whatever else comes to mind when somebody reads it.

@thetinyl Do you have an opinion about wording for the label?

**Comment by ryelle** [comment]
Yeah, I noticed that Pablo suggested `Search in WordPress.org` _after_ I took these screenshots, so I have already updated it with that label, I just didn't retake all the screenshots 😅 

In any case, it looks like this:

<img width="326" alt="Screenshot 2023-04-10 at 10 58 43 AM" src="https://user-images.githubusercontent.com/541093/230927337-a15f5861-bd88-4de8-b210-ba3561d810a5.png">

**Comment by bengreeley** [comment]
Great, that makes more sense.

**Comment by thetinyl** [comment]
For what it's worth, I think the current label works and is clear enough. If I were going to suggest something it'd probably be a minor tweak to something like: "Search all of WordPress.org"
