### ISSUE TITLE
Delete static homepage

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#37]
part of #38

delete the static homepage so that we don't have to update it w/ the header changes

it doesn't seem needed these days. we'll have to sync the static and dynamic versions before deleting the static one, since they're not always kept in sync

there might be a jump in server load as the page moves from static to dynamic. i'm guessing it'll be negligible, but we should monitor it just in case. if it unstable we can revert, add nginx caching 

- [ ] sync changes
- [ ] setup flag to route to WP vs static
- [ ] flip flag so production goes to WP
- [ ] monitor munin for load spike
- [ ] if needed, reverse flag until optimizations in place
- [ ] if needed, add nginx caching
- [ ] once any performance issues sorted, delete static page

**Comment by dd32** [comment]
Went ahead and did it in r18205-dotorg after migrating/implementing everything needed into the main theme.

No significant server load changes, higher first-load KB count, but that's mostly related to some extra CSS/JS being loaded,
