### ISSUE TITLE
Navigation: Remove navigation highlights when on subpages/posts

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-mu-plugins#370]
From WordPress/wporg-main-2022#221 

> When in subpages, the top nav highlights the main page. Worth removing to not mislead the user with wayfinding.

As an example, in the main news section, the item is highlighted:

<img width="722" alt="Screenshot 2023-03-27 at 12 08 24" src="https://user-images.githubusercontent.com/1204802/227911887-4fffed18-e820-4ae9-9dbd-fb4ec73f677d.png">

When in subpages or permalinks, it remains highlighted (parent):

<img width="738" alt="Screenshot 2023-03-27 at 12 08 35" src="https://user-images.githubusercontent.com/1204802/227911966-e4726a54-f690-4428-b346-a99042e6f40e.png">

This is similar in About and About subpages:

<img width="1115" alt="Screenshot 2023-03-27 at 12 09 42" src="https://user-images.githubusercontent.com/1204802/227912104-b1725c1c-4e23-439e-90aa-bc115fbef638.png">

<img width="1113" alt="Screenshot 2023-03-27 at 12 09 53" src="https://user-images.githubusercontent.com/1204802/227912121-bac80d00-f9ae-442d-86f3-650e93523b4d.png">

While the ability to highlight the parent and ancestor of a page or post is a pattern we're leveraging here, it hasn't materially aided wayfinding, and has caused a few issues on its own. 

Should we hide this highlight? It seems especially an issue on mobile:

<img width="521" alt="Screenshot 2023-03-27 at 12 36 02" src="https://user-images.githubusercontent.com/1204802/227918966-7a204b94-b97a-44e0-b2f9-2c9b76f54480.png">

<img width="521" alt="Screenshot 2023-03-27 at 12 40 54" src="https://user-images.githubusercontent.com/1204802/227919111-7aa28fd5-1f45-4c29-b2e6-3ab288f12a1a.png">

**Comment by ryelle** [comment]
Is there a determined outcome here? It sounds like this is still under discussion to me.

**Comment by ryelle** [comment]
From the discussion on our call yesterday, the outcome here is to stop highlighting when in the section — the top level item should only be highlighted when it's an exact match for the page.

**Comment by ryelle** [comment]
The "Forums" (and "Learn") section should not be highlighted when on the search page. See https://github.com/WordPress/wporg-main-2022/issues/216
