### ISSUE TITLE
Fixed sidebar creates loss of visible focus & unreachable items.

### ISSUE THREAD

**Issue by joedolson** [WordPress/wporg-mu-plugins#409]
When the fixed sidebar is longer than the viewport, items in the sidebar that are below the scroll do not come into focus during keyboard navigation.  It's also not possible in that case to reach the lower part of the sidebar without scrolling to the end of the page.

There is a way to do this - if you toggle the sidebar closed, then re-open it, the `is-fixed-sidebar` class is removed, and you'll be able to use the sidebar normally. However, this is more "taking advantage of a bug to be able to use the site" than intent, I'm guessing. 

See [Roles and Capabilities](https://wordpress.org/documentation/article/roles-and-capabilities/) for an example of this problem; [see also this slack message in #docs](https://wordpress.slack.com/archives/C02RP4WU5/p1687386572350359) where this issue was noted.

**Comment by ryelle** [comment]
Hm, the sidebar should not be fixed if it's longer than the viewport, so something is going wrong with the initial JS which adds that `is-fixed-sidebar` class.
