### ISSUE TITLE
Header FOUC before priority nav script loads

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#41]
1. Size browser to `1025px`
2. Load a page w/ the header
2. Browser will render the header w/out the priority navigation, so menu items will wrap
3. Browser will load the priority nav script and re-render the header, this time w/ the extra items hidden behind `...`

We might need to load the script sooner, or something like that. Or maybe `overflow-x: none`

**Comment by dd32** [comment]
This was improved slightly via #121  - the header size no longer jumps around, but on a smaller screen the initial load will only show the second line of items, not the first, until the JS kicks in.

#132 should resolve the rest of the issues here.

Running the menu script earlier would still be beneficial, but doesn't remove the need for the above PR.
