### ISSUE TITLE
Add support for [time] shortcode

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wporg-mu-plugins#413]
The [time] shortcode is included in the o2 and p2 plugins. Find a way to make it available when this theme is loaded.

**Comment by adamwoodnz** [comment]
A better solution would be to migrate this shortcode to a block, available across the network via wporg-mu-plugins

**Comment by ryelle** [comment]
Have you seen the [formats API](https://developer.wordpress.org/block-editor/how-to-guides/format-api/)? It's not as robust as an entire block, but it lets you edit inline content.

**Comment by adamwoodnz** [comment]
> Have you seen the [formats API](https://developer.wordpress.org/block-editor/how-to-guides/format-api/)

Yes! I've just started building a block using that to format the inline text.

To cover the rest of the implementation in `mu-plugins/pub/wporg-time-shortcode.php`, I thought I would add a server side filter to format the output on the frontend (anchor with nested abbr), then add a frontend script to do the time conversion.

Does that make sense or is there a better way?
