### ISSUE TITLE
Login button too close to the scroll bar.

### ISSUE THREAD

**Issue by anik-cse** [WordPress/wporg-mu-plugins#426]
Browser: Firefox
Version: 116.0.3 (64-bit)
OS: Windows 11
Issue Description: The login button is too close to the scroll bar and when hovering over the scroll bar the scroll bar gets over the login button.
Default view https://paste.pics/P5924 After hovering the scroll bar https://paste.pics/P591M

**Comment by ryelle** [comment]
As of https://github.com/WordPress/wporg-mu-plugins/issues/647, the "Log in" link is now in the site navigation instead of the admin bar, so it doesn't overlap the scrollbar.

![Image](https://github.com/user-attachments/assets/d0fa88f3-c847-49ec-9626-90f70e025e1c)
