### ISSUE TITLE
Fix minor style conflicts with header/footer in Classic themes

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#44]
#19 got the core solution working, and fixed some of the conflicts. There are a good number more, though, which is to be expected.

Some of these are probably just because we haven't ported over all the stylesheets, link/meta tags, etc. ~~`wp4.css` isn't being included yet, as an example (although only some sites use it)~~

see https://github.com/WordPress/wporg-mu-plugins/issues/19#issuecomment-997058267 for setup instructions

### translate.w.org
- [x] translate.w.org - 2015 styles enqueued, messing up content styles.
- [x]  translate.w.org - instead of calling `wp_head` _or_ `gp_head`, add `gp_head` to the `wp_head` action. that way `wp_head` still gets called. this may fix the issue w/ `view.min.js` not enqueuing. same for footer
I think… you could pretty much hook those to wp_head and wp_footer and it’d work properly….
- [x] translate.w.org - navigation `view.min.js` not enqueued, which breaks this fixes menu/search. [the `viewScript`](https://github.com/WordPress/gutenberg/blob/f7d853bc81be74fadcd3b627e327fce548193683/lib/compat/wordpress-5.8/blocks.php#L21) for used blocks aren't being enqueued automatically. could manually enqueue it, but don't wanna do that for every single block that might have one. need to figure out what normally enqueues them, and why that's not being called here
- [x] #78

### patterns & learn

- [x] #71
- [x] #72
- [x] #74
- [x] #75

### misc

- [x] #60
- [x] #66
- [x] #81
- [x] news-test has weird fonts now on homepage. what change would have caused that? maybe gutenberg version update?
- [x] #76
- [x] #64
- [x] test login.w.org
- [x] #94
- [x] mobile search - input padding is coming from news theme search block, maybe that's for the 404?
- [x] title isn't set on most sites. It is on Patterns b/c JS resets it.
- [x] make sure sandbox hostname included in title, probably do via hook so affects all types of themes
- [x] [network-activate gutenberg plugin on all networks](https://github.com/WordPress/wporg-mu-plugins/issues/44#issuecomment-1010410433)
- [x] do a final test on all sites to make sure looks good, search/menu works on mobile and desktop, etc

### old news site  (wordblog)

don't spend any time here unless you know header/footer is gonna launch before the theme is replaced

- [x] over `975px`, `#pagebody` collapses, and needs something like `overflow: auto` to clear the floated child elements
- [x] content styles broken
- [x] header extra space
- [x] gap below footer caused by `#wpstats`
- [x] header menu/search isn't aligned w/ the logo.

**Comment by ryelle** [comment]
On make sites, it looks like the theme expects the header to load Open Sans, so the fonts are broken (Open Sans is not loaded, it falls back to `serif` headings & `sans-serif` body).

<img width="1244" alt="Screen Shot 2022-01-03 at 5 47 09 PM" src="https://user-images.githubusercontent.com/541093/147988636-fd544d82-ae14-4c28-a559-e6522f1f6002.png">

-----

> news-test has weird fonts now on homepage. what change would have caused that? maybe gutenberg version update?

If this means the font sizes - it looks like the custom properties are different. For example on the h2s, it uses `var(--wp--custom--h2--typography--font-size)` which is set to `var(--wp--custom--h2--breakpoint--mobile--typography--font-size)` but the actual property loaded is `--wp--custom--h-2--breakpoint--mobile--typography--font-size`. (note `h2` vs `h-2`). That's a place to start, at least.

**Comment by ryelle** [comment]
I think the custom property issue is due to https://github.com/WordPress/gutenberg/pull/37380

**Comment by ryelle** [comment]
Some real awkwardness happening on the "create pattern" page on wordpress.org/patterns:

<img width="1524" alt="Screen Shot 2022-01-05 at 4 35 21 PM" src="https://user-images.githubusercontent.com/541093/148292822-1d552391-a27a-4175-879b-6f476593654f.png">

Both the header & footer are z-indexed above the pattern creator, but for some reason the footer has no background (so I'm highlighting everything to show it, the lavender is my selected text color). This is probably something I can fix in the creator CSS, but let me know what you think.

**Comment by ryelle** [comment]
FYI, the title is only set on patterns because we're setting it post-load in JS.

**Comment by iandunn** [comment]
🤔  that is weird. One thing I noticed is a FOUC-ish behavior where the footer _does_ have the bg color when the page initially renders, but then it's repainted without it.

**Comment by iandunn** [comment]
i noticed some sites (like `/plugins`) don't have the Gutenberg plugin activated, which may cause some problems/inconsistencies

we should probably network-activate it on all the networks, but will need to test afterwards to make sure there aren't any side-effects

**Comment by dd32** [comment]
> old news site (wordblog)

Looks like all those issues have now been resolved?

**Comment by iandunn** [comment]
Most of them do, yeah :)

I still see a gap under the footer caused by `#wpstats`, and the header menu/search isn't aligned w/ the logo.

I'll update the list w/ those.

**Comment by dd32** [comment]
> I still see a gap under the footer caused by `#wpstats`, and the header menu/search isn't aligned w/ the logo.

Ah! Thank you @iandunn, I wasn't sure what it was specifically. I was using it as a "If this site works with no changes, other ancient things probably do too" rather than targeting the site.

**Comment by ryelle** [comment]
@iandunn For these two, are they still happening? I'm not totally sure what they mean, but opening search on mobile looks fine for me.

- mobile search - extra line appears when first open it. it's also under menu, maybe an outline/focus thing? goes away when click elsewhere.
- mobile search - input padding is coming from news theme search block, maybe that's for the 404?

**Comment by iandunn** [comment]
> mobile search - extra line appears when first open it. it's also under menu, maybe an outline/focus thing? goes away when click elsewhere.

I see this on Patterns and Learn:

<img width="563" alt="Screen Shot 2022-01-14 at 5 25 14 PM" src="https://user-images.githubusercontent.com/484068/149603579-eba0fd9a-6158-40bb-8b72-8c399b117c01.png">


> mobile search - input padding is coming from news theme search block, maybe that's for the 404?

I think that was fixed, I'll mark it off 👍🏻

**Comment by ryelle** [comment]
> I still see a gap under the footer caused by `#wpstats`

That should go away once wp.org is running Jetpack 10.5 (see https://github.com/Automattic/jetpack/pull/22196), but we're pinned to 10.2.1 right now.

**Comment by dd32** [comment]
> > I still see a gap under the footer caused by `#wpstats`
> 
> That should go away once wp.org is running Jetpack 10.5 

Flipped the option on to hide it on all dotorg sites in r18331-dotorg, as the dotorg Jetpack upgrade is pending a few blockers.

**Comment by dd32** [comment]
> * [ ]  [network-activate gutenberg plugin on all networks](https://github.com/WordPress/wporg-mu-plugins/issues/44#issuecomment-1010410433)'

The Gutenberg plugin was previously activated in a lot more places, but was globally deactivated on all WordPress.org sites after WordPress Trunk & Gutenberg stable release became incompatible with one another.

Previous to now, Gutenberg was activated network-wide on Rosetta & a handful of other sites (including main sites, the test make site, and Learn)

Not expecting any issues, I've network activated it on the Main & Make networks now, and finally on developer.w.org. 

So.. It should be active everywhere that matters now.

**Comment by ryelle** [comment]
Can this issue be closed out now? The last item remaining is

> do a final test on all sites to make sure looks good, search/menu works on mobile and desktop, etc

But I think we're all doing that now. Unless we want to list out specific sites & client combos to test?

**Comment by iandunn** [comment]
That WFM 👍🏻
