### ISSUE TITLE
Navigation: Make primary navigation submenus "Open on click"

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-mu-plugins#440]
This issue was extracted from the [larger discussion](https://github.com/WordPress/wporg-mu-plugins/issues/360) about updating the primary navigation on WordPress.org. 

The proposal is for the submenus to only open on click. Currently, the submenus open on hover, and the first item in the submenu is the same link as the top-level menu item. Switching to open on click will simplify the menu. 

| Current | Proposed (not real wp.org site) |
| --- | --- |
| ![submenu-hover](https://github.com/WordPress/wporg-mu-plugins/assets/4832319/fc95183d-12db-43fa-8f73-90966f507dd8) | ![menu demo](https://user-images.githubusercontent.com/1204802/234581663-5f5c49a7-941c-417b-8f39-fc10b2068098.gif) |

"Open on click" is a setting in the Navigation block, so no additional development work should be needed.  

<img width="292" alt="image" src="https://github.com/WordPress/wporg-mu-plugins/assets/4832319/555f5275-cb6f-473a-936f-4e8c2c8ef3bb">

**Comment by ndiego** [comment]
@alexstine from an accessibility perspective, do you have any concerns about using "Open on click" navigation submenus instead of open on hover?

**Comment by alexstine** [comment]
It should be better accessibility this way. Let's try it.
