### ISSUE TITLE
Version Header is hidden on mobile device.

### ISSUE THREAD

**Issue by dd32** [WordPress/wporg-mu-plugins#445]
As reported by @dhrumilkumbhani in https://meta.trac.wordpress.org/ticket/7189
**Describe the bug**

Releases Page header is hidden due to overlapping the image.
Page URL:- https://wordpress.org/download/releases/

**Screenshots**
![image](https://github.com/WordPress/wporg-main-2022/assets/767313/3ab25940-c213-4d87-be53-921bbacb82f4)

**Comment by pkevan** [comment]
Looks like it's broken more between 899-600px screen width, since the sub menu for download is hidden as white links below the header.

Screenshot:
![Image](https://github.com/WordPress/wporg-main-2022/assets/2290623/72d5aa73-aa74-4cc1-9dda-d333c19ebb0d)

**Comment by ryelle** [comment]
This is affecting all places that use the local navigation header, I think. I just noticed this one the About section as well

![Screen Shot 2023-09-07 at 11 17 58](https://github.com/WordPress/wporg-main-2022/assets/541093/340f266d-7f51-407e-b4e2-bb1df2ba06e3)
