### ISSUE TITLE
Update background hover color for `charcoal-1` nav menus 

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-mu-plugins#451]
When the background of a nav menu is set to `--wp--preset--color--charcoal-1: #1e1e1e`, such as in the case of [Showcase v2](https://wordpress.org/showcase-v2/), the submenu hover color is set to `--wp--preset--color--nero: #1c2024` ([reference](https://github.com/WordPress/wporg-mu-plugins/blob/46e2cc7f30e905eedd23d5d43cb84345ac8bf3e2/mu-plugins/blocks/global-header-footer/postcss/_common.pcss#L88)). While this works well with the default background color of `--wp--preset--color--charcoal-2: #1e1e1e`, the hover color does not stand out very well when using `charcoal-1`. 

| Showcase (`charcoal-1` + `nero`) | Other Pages (`charcoal-2` + `nero`) |
| ---- | ---- |
| <img width="377" alt="image" src="https://github.com/WordPress/wporg-showcase-2022/assets/4832319/a5e2b82f-ae73-4bbf-b481-d5e5b67f52b7"> | <img width="404" alt="image" src="https://github.com/WordPress/wporg-showcase-2022/assets/4832319/968c7656-e96c-4457-a7f3-7be843a9093d"> | 

One possible solution is to set the hover color to `charcoal-2`. 

| (`charcoal-1` + `charcoal-2`) |
| ---- |
| <img width="410" alt="image" src="https://github.com/WordPress/wporg-mu-plugins/assets/4832319/936e3ee7-5b2c-40f2-806b-b7e070eadf24"> |

If approved, we would need to add the following to [this file](https://github.com/WordPress/wporg-mu-plugins/blob/46e2cc7f30e905eedd23d5d43cb84345ac8bf3e2/mu-plugins/blocks/global-header-footer/postcss/_common.pcss#L88). 

```
.has-charcoal-1-background-color {
	--wp-global-header--background-color--hover: var(--wp--preset--color--charcoal-2);
}
```

**Comment by ryelle** [comment]
For a little more context, this is [the PR that introduced the ability to use a custom color for the block backgrounds](https://github.com/WordPress/wporg-mu-plugins/pull/350). Previously, only `white`, `blueberry-1`, and `charcoal-2` were supported. It just happens that the defaults work _okay_ with `charcoal-1`, but any new color really should get some custom CSS to support it.

The CSS in the description should be correct, if that's the route to take. 👍🏻

**Comment by ndiego** [comment]
@jasmussen @marko-srb any thoughts on this? It would be nice to get updated along with Showcase if this is the direction we want to take. Thanks!

**Comment by jasmussen** [comment]
Just to be sure, you're suggesting we use charcoal 2 (bg) + charcoal 1 (menu) for other pages, and charcoal 1 (bg) and charcoal 2 (menu) for showcase? If yes, I agree.

**Comment by ndiego** [comment]
> Just to be sure, you're suggesting we use charcoal 2 (bg) + charcoal 1 (menu) for other pages, and charcoal 1 (bg) and charcoal 2 (menu) for showcase? If yes, I agree.

Yup exactly. Cool, I'll get a PR together.
