### ISSUE TITLE
internationalize new header/footer

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#46]
it needs to work in other locales. not just on the rosetta sites, but also sites like Learn that have locale switchers, and the homepage (which has an automatic switch

### Basic string internationalization

- [x] Header: global menu items - done in https://github.com/WordPress/wporg-mu-plugins/commit/9a7ed8d0320865fc5404f0821cb1d9d6444eb78e for https://github.com/WordPress/wporg-mu-plugins/issues/49
- [x] Header `alt` tags, etc
- [x] Footer
- [x] sync code to w.org so new strings can be translated
- [x] sync strings to GlotPress - may need to update the bin script to explicitly process `mu-plugins/pub-sync/`
- [x] wait until translated in a few locales
- [x] test on rosetta sites

**Comment by iandunn** [comment]
I expected something like this to work, but it doesn't at first glance:

```php
<!-- wp:navigation-link {"label":"<?php esc_html_x( 'Privacy Policy', 'Page title', 'wporg' ); ?>","url":"https://wordpress.org/about/privacy/","kind":"custom","isTopLevelLink":true} /-->
```

The `label` ends up empty, so the link isn't rendered. I was testing on `nl.w.org`, and [that string is translated there](https://translate.wordpress.org/projects/meta/wordpress-org/nl/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=5857542&filters%5Btranslation_id%5D=54650904).

We'll need to dig in more to find out why.

_Note that the mockup actually calls for `Privacy` rather than `Privacy Policy`; the above is just a test to see if it worked._

**Comment by iandunn** [comment]
Doh, nevermind, that does work, I was just confusing `esc_html_x` with `esc_html_e` 😆 

`esc_html_x()` doesn't `echo` the output, but this works:

```php
<!-- wp:navigation-link {"label":"<?php echo esc_html_x( 'Privacy Policy', 'Page title', 'wporg' ); ?>","url":"https://wordpress.org/about/privacy/","kind":"custom","isTopLevelLink":true} /-->
```

**Comment by iandunn** [comment]
@ocean90 , @dd32: I'm trying to get strings from this repo imported into GlotPress. does the diff below look correct?

should this go in it's own GP project, or the main `wordpress-org` one? if a new one, do i need to create that in the GP UI, or do the code changes below do it?




```diff
Index: generate-pot.sh
===================================================================
--- generate-pot.sh	(revision 18316)
+++ generate-pot.sh	(working copy)
@@ -66,6 +66,7 @@

 		wpclimakepot $CO/learn-wordpress $CO/learn-wordpress/wporg-learn.pot --exclude=wp-content/mu-plugins
 		wpclimakepot $CO/pattern-directory $CO/pattern-directory/wporg-patterns.pot --exclude=public_html/wp-content/mu-plugins --exclude=public_html/wp-content/tests --exclude=node_modules
+		wpclimakepot $CO/wporg-mu-plugins $CO/wporg-mu-plugins/wporg-mu-plugins.pot

 		# Download the Openverse file. Additional check to ensure it's at least 100 lines.
 		curl -so "$CO/openverse-frontend.pot" https://raw.githubusercontent.com/WordPress/openverse-frontend/main/src/locales/po-files/openverse.pot
Index: init-repos.sh
===================================================================
--- init-repos.sh	(revision 18316)
+++ init-repos.sh	(working copy)
@@ -36,6 +36,12 @@
 	cd $CO/pattern-directory && git fetch origin --quiet && git reset --hard origin/build --quiet
 fi

+if [ ! -d $CO/wporg-mu-plugins ]; then
+	git clone --branch trunk https://github.com/WordPress/wporg-mu-plugins.git $CO/wporg-mu-plugins
+else
+	cd $CO/wporg-mu-plugins && git fetch origin --quiet && git reset --hard origin/trunk --quiet
+fi
+
 cd $CO

 svn co https://i18n.svn.wordpress.org/tools/trunk i18n-tools
Index: update-originals-wp.sh
===================================================================
--- update-originals-wp.sh	(revision 18316)
+++ update-originals-wp.sh	(working copy)
@@ -91,6 +91,9 @@
 if [ -d "$CO/pattern-directory" ]; then
 	import_po meta/pattern-directory $CO/pattern-directory/wporg-patterns.pot
 fi
+if [ -d "$CO/wporg-mu-plugins" ]; then
+	import_po meta/wporg-mu-plugins $CO/wporg-mu-plugins/wporg-mu-plugins.pot
+fi
 if [ -d "$CO/browsehappy" ]; then
 	import_po meta/browsehappy $CO/browsehappy/languages/browsehappy.pot
 fi
```

**Comment by ocean90** [comment]
@iandunn I'm assuming you want continue to use the `wporg` text domain? In this case we should use the existing project and merge the POT files for wporg-mu-plugins and wordpress-org.
This can be done with the [`--merge` option](https://developer.wordpress.org/cli/commands/i18n/make-pot/).

**Comment by dd32** [comment]
> I'm assuming you want continue to use the wporg text domain? In this case we should use the existing project and merge the POT files for wporg-mu-plugins and wordpress-org.

Agreed.

I've added this in r18321-dotorg and an incoming Meta commit will update the file references dynamically to point to the right location.

**Comment by dd32** [comment]
> if a new one, do i need to create that in the GP UI, or do the code changes below do it?

@iandunn FYI; yes you'd have to also manually create the GP project, the CLI tools don't do that automatically (Other than the custom Plugin/Theme import scripts)

**Comment by iandunn** [comment]
Yup, those commits look good, thanks!

**Comment by iandunn** [comment]
This is working on Rosetta sites.

It doesn't work on things like https://learn.wordpress.org/?locale=es_MX, but the old header/footer isn't translated there either, so I think that's something for another day.
