### ISSUE TITLE
Query Filter: On mobile, horizontal scroll bar is visible on page load.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-mu-plugins#467]
On my phone, I get the horizontal scrollbar for the list of filters when i load the page. If I interact with the menu and stop, it will fade away as expected. It isn't a transitional state since it will persist. It doesn't happen on all devices (tested using dev tool), but it does with my personal phone and I can reproduce using IPhone SE via dev tools.

## On Page Load
<img width="200" alt="Screenshot 2023-10-03 at 12 35 24 PM" src="https://github.com/WordPress/wporg-mu-plugins/assets/1657336/68336170-0ac2-4243-9a5f-fc39d85ccad6">

## GIF
<img src="https://github.com/WordPress/wporg-mu-plugins/assets/1657336/b24ce137-1c52-4b84-9946-0319d5cace99" width="200">

**Comment by ryelle** [comment]
This section is supposed to scroll, so I imagine it has scrollbars on load to indicate that it's scrollable, but I'm not sure. Do you think the scrollbar should not be visible on load?

**Comment by StevenDufresne** [comment]
> This section is supposed to scroll, so I imagine it has scrollbars on load to indicate that it's scrollable, but I'm not sure. Do you think the scrollbar should not be visible on load?

Yeah that's fair. I guess I appreciate the affordance, but I originally thought they were Material Design-like tab underlines. I think an inset box shadow on the right would be a better indication. Low priority.

**Comment by StevenDufresne** [comment]
I also the bar also appears on top of the modal.

<img src="https://github.com/WordPress/wporg-mu-plugins/assets/1657336/9bdef3da-49e5-42b5-bcd4-c4156d4a6961" width="300"/>
