### ISSUE TITLE
Replace Twitter icon with X

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-mu-plugins#470]
We currently show this:

![Screenshot 2023-10-06 at 09 42 47](https://github.com/WordPress/wporg-main-2022/assets/1204802/ac0f68d7-8955-413c-9e5c-202ff4a00ef8)

Let's update this to the new logo chosen by the company. 

I know that a PR has been merged to the Gutenberg plugin to add the icon, let's do that as soon as it's possible as this will also update the link text. 

Until then, and if that takes more than a couple of days to do, let's apply a temporary hack. You can use [this codepen](https://codepen.io/joen/pen/MWZzOZG?editors=1100), but the pertinent bit is this:

```
.wp-social-link-twitter {
	background: url(https://cldup.com/GnkaLzBcia.svg) no-repeat;
	background-size: 100%;
	
	svg {
		visibility: hidden;
	}
}
```

That cloudup link is just to show it working in the codepen, but you can snatch the SVG code here. X.svg:

```
<svg width="24" height="24" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false"><path d="M13.982 10.622 20.54 3h-1.554l-5.693 6.618L8.745 3H3.5l6.876 10.007L3.5 21h1.554l6.012-6.989L15.868 21h5.245l-7.131-10.378Zm-2.128 2.474-.697-.997-5.543-7.93H8l4.474 6.4.697.996 5.815 8.318h-2.387l-4.745-6.787Z"></path></svg>
```

**Comment by adamwoodnz** [comment]
This is part of the global footer, hence the transfer to the mu-plugins repo.

**Comment by StevenDufresne** [comment]
@ndiego has a pr for this: https://github.com/WordPress/wporg-mu-plugins/pull/461

**Comment by ndiego** [comment]
Yeah 🤞 Gutenberg 16.8 doesn't break things like 16.7, and we can merge https://github.com/WordPress/wporg-mu-plugins/pull/461 later this week.
