### ISSUE TITLE
Map marker modal misaligned

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#477]
The downward arrow should be centered with the W icon

![Screenshot 2023-04-13 at 9 24 49 AM](https://user-images.githubusercontent.com/484068/231823870-416185c9-e79a-44a3-968a-1bfa532439ee.png)

**Comment by adamwoodnz** [comment]
I believe we have new designs being worked on for these markers and modal. @marko-srb please add them to this issue when ready 🙏
