### ISSUE TITLE
New styles in TOC component

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wporg-mu-plugins#491]
As described [here](https://github.com/WordPress/wporg-developer/pull/305#issuecomment-1784796554) by @jasmussen in WordPress/wporg-developer#305, TOC component has the following changes:

## Styles
* Blue background was removed
* Padding was removed
* Bullets were removed for all indentation
* The indentation spacing is the same as Chapter component (#310)
* Active style follows [Content item component](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?type=design&node-id=2555-10584&mode=design&t=yiAlKtoJHOXCRUuJ-4).

## Behavior
The "Back to top action" shows up when users scroll down.

![Design of new TOC. Resting state on the left. Scroll state on the right](https://github.com/WordPress/wporg-developer/assets/895819/07228558-7665-4cc5-ba4d-6b8a8f09a3e5)

## Responsive
On mobile, the component is collapsed and placed below post title. The expanded version is the same as on desktop

![New design of TOC on mobile. Collapsed version on the left. Expanded version on the right](https://github.com/WordPress/wporg-developer/assets/895819/e1faa3a7-c07c-44b8-9e75-67f08dc275f1)

---

## Design
* [Component](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?type=design&node-id=3380-7875&mode=design&t=yiAlKtoJHOXCRUuJ-11) of TOC
* [Developer mockups](https://www.figma.com/file/2WxlJFzMJvqPfZL1EkAOVp/Developer-Resources?type=design&node-id=2934-6590&mode=design&t=7w1GtutWNO2sHH72-11). Updated with these changes.

**Comment by adamwoodnz** [comment]
Closed by #499 

Remaining work around showing/hiding 'Back to top' link and styling the current section title based on scroll position will be addressed in a separate issue.
