### ISSUE TITLE
Use native WordPress date formatting, instead of PHP DateTime for latest news

### ISSUE THREAD

**Issue by raikasdev** [WordPress/wporg-mu-plugins#493]
Instead of using PHP's DateTime to format the date, it would probably be better to use some API that allows for translating the date format. Currently the dates being in English look a bit out of place on localized/Rosetta sites.

Willing to PR. Tomorrow I'm going to try using get_the_date and calling it with the WP_Post object. If someone knows a better way, please tell me :smiley:
 
https://github.com/WordPress/wporg-mu-plugins/blob/7048e1b99c22862d2f1235c598b4944127d68ce6/mu-plugins/blocks/latest-news/latest-news.php#L86-L90

**Comment by adamwoodnz** [comment]
Open to a PR, thanks!
