### ISSUE TITLE
Add Rosetta locale header

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#50]
The Rosetta sites have their locale name added to the header; e.g. https://es-mx.wordpress.org/ looks like:

<img width="965" alt="Screen Shot 2021-12-28 at 10 47 59 AM" src="https://user-images.githubusercontent.com/484068/147597432-bee0a893-8f87-420d-ba4e-dc89e6e4c7f6.png">

It's currently done via `h2` text; the shortest name is `Lao`, and the longest is `Papiamento (Curaçao and Bonaire)`. See https://make.wordpress.org/polyglots/teams/ for a list and links to each site.

@beafialho , can you add an example of that to the mockup?

**Comment by beafialho** [comment]
Here's a mockup of what the header with the locale sites names should look like:

<img width="1456" alt="Captura de ecrã 2022-01-04, às 10 31 26" src="https://user-images.githubusercontent.com/65220155/148046322-0409a243-0898-402f-91e3-8709dd1b7a19.png">

<img width="1490" alt="Captura de ecrã 2022-01-04, às 10 46 31" src="https://user-images.githubusercontent.com/65220155/148047815-ccb2157d-74b3-4bba-add6-6e02bd24042c.png">

👉 [Header mockups](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=10279%3A111020)

I'd also add the locale name to the footer as a clickable link, possibly taking users to the page you have posted above: https://make.wordpress.org/polyglots/teams/ so they could easily switch to another site. We could also work an a design for this page later. Here's an example of what it could look like: https://www.apple.com/choose-country-region/

<img width="1375" alt="Captura de ecrã 2022-01-04, às 10 31 52" src="https://user-images.githubusercontent.com/65220155/148046354-23738557-dd21-4696-93dc-427aa6395fa6.png">

👉 [Footer mockups](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=2414%3A4910)

Let me know if anything else is needed.

**Comment by iandunn** [comment]
Those look great, thanks!

**Comment by iandunn** [comment]
@ryelle , @dd32 , this was fixed by #98, right?

**Comment by ryelle** [comment]
Not yet, the locale was also added to the footer in the designs. (I'm working on it now)
