### ISSUE TITLE
Footer should link to Rosetta pages when available

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#52]
Similar to #49, the footer links need to go to Rosetta-specific pages, when they're available. When they're not, they should fallback to the main site. 

e.g., https://nl.wordpress.org/about/ exists, so the current footer uses that. There isn't a translated Hosting page, though, so it just links to https://wordpress.org/hosting/

The simplest way might be to copy the old footer, which just manually makes specific links use `$localised_domain`.

If that won't work well, then another approach might be to:
- [ ] rename `get_global_menu_items()` to `get_global_header_menu_items()`
- [ ] create a similar function called `get_global_footer_menu_items()`, populate it w/ the current/English links
- [ ] convert `footer.php` to loop through the items programattically, and generate `wp:navigation-link` comments, just like `header.php` does. Maybe create a helper function to make it DRY across both files.
- [ ] create a function called something link `inject_rosetta_urls()`. it could be passed the global items, and loop through them. when the rosetta site has a localized page, it could replace the url/title. then it'd return all the items (some of which are now localized, and some of which are still the original English version)
- [ ] in `render_global_footer()`, do something like:
	```php
	$menu_items = get_global_footer_menu_items();
	
	if ( is_rosetta_site() ) {
		$menu_items = inject_rosetta_urls();
	}
	```

**Comment by ryelle** [comment]
Now that #106 is merged, is there anything else to do here?

**Comment by iandunn** [comment]
Nope 👍🏻
