### ISSUE TITLE
Sidebar container: hide 'Back to top' link until scrolled

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wporg-mu-plugins#521]
Can we show it only if you've scrolled at least a little bit?

![image](https://github.com/WordPress/wporg-mu-plugins/assets/1017872/cd07b270-7558-4a5f-b024-75912f94d013)

This one is actually kind of important, to the point that if we can't hide until scroll for launch we should hide the entire link until we can get that to work. Mostly we want to avoid the above case where you are scrolled to the top, but the link is still showing, quite prominently in some cases.

**Comment by adamwoodnz** [comment]
Hope you haven't spent much time on this @renintw, it looks like it will be fixed as a side effect of https://github.com/WordPress/wporg-mu-plugins/issues/524

**Comment by outdoor2kode** [comment]
Ah, yeah, that's why I left a comment in #524, seems related. I'll unassign myself first. Thanks!
