### ISSUE TITLE
Integrate new header/footer into Trac

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#53]
It should use the endpoint from #45, and we should do this in parallel to that issue, so that feedback can be given to shape how the endpoint is created

- [x] do brain dump on how to update/test trac templates
- [ ] turn brain dump into docs
- [x] pull API response into trac env and cache there
- [x] integrate cached markup into trac templates
- [x] give feedback on #45 and iterate there
- [ ] test on production behind feature flag (if convenient)

**Comment by iandunn** [comment]
@dd32 IIRC you're one of the few people how knows how to edit and test the Trac templates, do you mind doing a brain dump here with the important stuff that someone else would need to know? 

Is it just setting up a local Trac install w/ the templates from `meta.svn` ? Any quirks or confusing stuff?

**Comment by iandunn** [comment]
There's a rough version of the API available at these URLs:

* https://wordpress.org/news-test/wp-json/global-header-footer/v1/header
* https://wordpress.org/news-test/wp-json/global-header-footer/v1/footer

We'll need feedback on how well that approach works for Trac.

**Comment by dd32** [comment]
> Is it just setting up a local Trac install w/ the templates from `meta.svn` ? Any quirks or confusing stuff?

Yes, and yes.

There's a bunch of Quirks, some of which require customising the templates from meta. For testing some components of Trac, you also need to write a custom `trac-wsgi.py` to allow authentication, or to route requests correctly.
You can mostly just put the template directory on top of a regular Trac install and be able to do most things, but digging deeper requires dealing with the quirks.

https://github.com/WordPress/wordpress.org/pull/50 is some initial work to make it work, I've gone with a local script initially, but we may be able to convert it to auto-updating one from the rest endpoints.

**Comment by iandunn** [comment]
👍🏻  thanks!

**Comment by dd32** [comment]
https://github.com/WordPress/wordpress.org/pull/50 is ready for use when we roll the header out.

See #45 above for some other discussion about ways to implement this within Trac.

**Comment by iandunn** [comment]
@dd32 is there anything left to do here, other than deploy stuff on launch day?

**Comment by dd32** [comment]
Nope! I think it's all launch-day stuff now. I'll close this in preference for #100

**Comment by dd32** [comment]
>  turn brain dump into docs

Just noting that I've started collating my testing info into  https://github.com/dd32/trac-w-org-env/issues/1

It's not a working environment, but is where I'll make it happen if I get to it.

**Comment by iandunn** [comment]
That's great, thanks!
