### ISSUE TITLE
A polished local nav component

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wporg-mu-plugins#535]
Now that the [new Showcase](https://wordpress.org/showcase/) has been released, Developers section [is in progress](https://developer.wordpress.org/redesign-test/), and [other designs](https://www.figma.com/files/project/1339429) are in a solid position, I noticed there is room for improvement to make navigation components more flexible and appealing when displaying location across the site.

I have been exploring different ideas, and this week I landed on a design that addresses key areas of navigation. Before dive into detail, here is a prototype involving four sections of the site.

https://github.com/WordPress/wporg-mu-plugins/assets/895819/84b608d7-1f21-4793-8317-72fcf85ee29f

https://github.com/WordPress/wporg-mu-plugins/assets/895819/9e6b70ac-bf55-425d-a687-cbfb2f4a6a26

---

In a previous comment, I mixed up the site depth taxonomy and the nested levels. That ended up confusing more and revisiting the breadcrumb location a few times. So to avoid new misunderstandings, I will refer to the page structure from the following logic.

| Level | Example 1 | Example 2 | Example 3 |
|:---|:---|:---|:---|
| Level 1 | News | About WordPress | Showcase |
| Level 2 | Community | Etiquette | [The Line Hotels](https://wordpress.org/showcase/the-line-hotels/) |
| Level 3 | … | … | … |

## Components height

One minor spacing tweak across components is making global header, local nav, and breadcrumb components 70px height on big screens and 60px on small ones. This equivalency makes the layout reachable across breakpoints and eases the interaction shown in the video.

![Components height](https://github.com/WordPress/wporg-mu-plugins/assets/895819/f0cccb74-3cca-463c-bb59-f157e7b44551)

## Current page visibility

When users are in level 2 pages not displayed in the local nav, the component shows the page name next to the section label. For level 3 and deeper pages, page name is hidden as breadcrumb takes that role. But once you scroll down, all pages, except for the section’s landing pages, show the page name. This will ease page and section recognition as the component remains fixed when you scroll down.

This change makes the site details page in Showcase simpler by removing breadcrumb above the cover image, whereas, deep pages in Documentation keep you in context as you scroll down in text-heavy posts.

![Current page visibility](https://github.com/WordPress/wporg-mu-plugins/assets/895819/7eba9e96-4eef-4c51-9559-37985b195c5e)

## Handy breadcrumb

From level 2 and deeper, “section and page” button expands the breadcrumb pages in the local nav, similarly to global header dropdown. When you are in level 3 and deeper pages, the breadcrumb bar appears below the local nav showing all parent pages. 

On small screens, local nav and breadcrumb pages are hidden until you expand the chevron button. The full size view allows you to scroll the area in those cases where items listed go overflow.

![Breadcrumb all the time](https://github.com/WordPress/wporg-mu-plugins/assets/895819/d7fbda75-9b73-4773-821d-617487de3d83)

![Breadcrumb all the time  Mobile](https://github.com/WordPress/wporg-mu-plugins/assets/895819/d53d5457-a1e7-4b89-9799-4155b84b13b2)

---

The local nav variant needed per page level, as described above, can be summarized as the diagram below shows

![Documentation](https://github.com/WordPress/wporg-mu-plugins/assets/895819/75a13184-fbb4-4a37-950c-6a7738857919)

This idea taps into the last changes applied to nav components, and I’m optimistic this change would clean layouts more and make more consistent the way of browsing the site.

What do you think?

**Comment by ndiego** [comment]
I think this is looking really great @fcoveram 🙌 So long as this approach passes accessibility tests, I love it.

**Comment by askdesign** [comment]
Very effective solution. Accessibility may be an issue.

- "Current page" treatment on black banner may be too subtle on levels 2 and 3. 
- "Current page" treatment on level 3 white area looks good.

**Comment by ryelle** [comment]
I think this is a good iteration on the current navigation 👍🏻  

Some of these technical details are already in place, like the sticky scrolling bar with W, site title, and local nav. The mobile version, where the dropdown includes more than just the navigation, might be tricky- hopefully we can work _with_ the core block instead of needing to make a new one, but that could be a dev quagmire.

Currently this part of the bar is just paragraphs, so to create the dropdown we'll need to custom-build a block. the navigation dropdown will not work because it doesn't support non-link items. This plus the mobile changes could maybe be bundled into our existing Local Nav block.

As for design feedback…

In the "Level 3" pages, I think the dropdown would be redundant— for example the Harvard University mockup, there are 4 items in the dropdown: a heading, link to wp.org (exists in bar), link to showcase (exists in bar), and the current page (not a link). It makes sense for deeper levels (the docs mockup), but I wouldn't show it for L3.

![annotated](https://github.com/WordPress/wporg-mu-plugins/assets/541093/8822fb8a-04f0-46aa-9964-b1908bcc3a68)

(My note about click targets is more of a dev note— I assume the click target is the whole label, but we want to keep that a consistent string throughout the site (eg, "local navigation", "parent pages", or something) - we can do it by making the chevron the button & making it bigger with CSS.)

Do we need the two "Level 2" options? It's not trivial to conditionally show the page title based on whether the page is in the navigation (since it's a separate block). If we could always show the page title that would be better.

**Comment by fcoveram** [comment]
> In the "Level 3" pages, I think the dropdown would be redundant (…) It makes sense for deeper levels (the docs mockup), but I wouldn't show it for L3.

I agree. And after testing different ideas, I don't see it as a problem. Since this header exists across all pages, I lean towards consistency and showing a single pattern rather than creating variants where some links are visible, or the whole popover is different. At first sight, the redundancy effect is hidden until you expand the dropdown. I'd like to see what other folks think of this (cc @jasmussen)

> (My note about click targets is more of a dev note— I assume the click target is the whole label, but we want to keep that a consistent string throughout the site (eg, "local navigation", "parent pages", or something) - we can do it by making the chevron the button & making it bigger with CSS.)

On big screens, the target is label and icon. On small screens, the target area is 52px width and 60px height; slightly different to [the current one](https://share.cleanshot.com/yvSkRxq2). Although I can't remember why it couldn't be a box of 60px.

| Big screens | Small screens |
|:---|:---|
| ![Wireframe of new hader in its big version](https://github.com/WordPress/wporg-mu-plugins/assets/895819/4b81af1e-3d69-4775-bd48-faecc739b8f2) | ![Wireframe of new hader in its small version](https://github.com/WordPress/wporg-mu-plugins/assets/895819/47215821-7bab-4fe0-a8ff-6b8265dd713d) |

> Do we need the two "Level 2" options? It's not trivial to conditionally show the page title based on whether the page is in the navigation (since it's a separate block). If we could always show the page title that would be better.

Showing the page title all the time, no matter whether it's in the local nav or not, was mainly to avoid visual redundancy. In opposition to the first point. The idea behind showing it while scrolling was the need to stand out the site context in pages strongly visual, like in the showcase details page and, eventually, the plugin details page. Both pages belong to the Extend group, and likely Themes and Patterns will look alike.

**Comment by jasmussen** [comment]
Thanks for the deliberate work and attention to detail Francisco, this is lovely work and a strong direction.

> In the "Level 3" pages, I think the dropdown would be redundant (…) It makes sense for deeper levels (the docs mockup), but I wouldn't show it for L3.

> I agree. And after testing different ideas, I don't see it as a problem. Since this header exists across all pages, I lean towards consistency and showing a single pattern rather than creating variants where some links are visible, or the whole popover is different. At first sight, the redundancy effect is hidden until you expand the dropdown.

One of the challenges we have for unification is mainly on Developers and Documentation. If you look at something like [the Footnotes Block documentation](https://wordpress.org/documentation/article/footnotes-block/), you have three breadcrumbs in addition to the link to the main landing page. Unifying that into a single row would be very space challenged, especially with 5 pinned items on the right of that same bar. 

I believe that the motivation for the dropdown is to afford that space, an "eliding mechanism", if you will, so that you could fit breadcrumbs and pinned items in a single bar. This is kind of the holy grail that Francisco diligently has been reaching for, and as they say about reaching for the stars, you might not reach one, but you won't end up with a handful of mud either. 

So this is a starry design, beautiful, and despite loving it, I'm not entirely convinced it will work for all pages. For things like Showcase, Hosting, Themes, Patterns, Plugins Blocks, — in fact, every section of WordPress except probably, those in the Learn category, it'll work beautifully. Notably the Learn section itself has some extremely long titles and categories, making it very hard to fit in a single bar. 

![Screenshot 2024-01-25 at 10 33 02](https://github.com/WordPress/wporg-mu-plugins/assets/1204802/69f1e7e5-7278-4cbc-9544-acef1600fabc)

So I still am not sure we're able to avoid having two versions of this — the unified version for most sections, and the stacked version for documentation. This is also because the full breadcrumb path feels valuable as a navigational aid in those sections, much less so for all the other, flatter sections.

And if we do end up with having the two versions, the dropdown in the unified version might not be needed. I also echo Kelly's concern, that it may be a technical challenge.

**Comment by ryelle** [comment]
I'm looking at it again and I think the "Harvard University" example is actually a "level 2" page, so it shouldn't have the dropdown.

@jasmussen's screenshot is a level 3 page, so it would, and in the dropdown would be "WordPress - Learn WordPress - Lessons - How to create a Lesson Plan". There's still redundancy there, but it's not _all_ redundant. I also agree that it makes sense as a pattern for even more nested items (like [this "level 5" handbook page](https://developer.wordpress.org/block-editor/how-to-guides/curating-the-editor-experience/block-locking/)).

**Comment by mpc** [comment]
Fantastic contribution

**Comment by fcoveram** [comment]
Sorry folks for not replying timely, I was working on a new iteration that address the redundancy point.

## Design (i3)

Since showing breadcrumb in level 2 pages was the main point, removing it creates the variant @jasmussen mention. In that way, going to main homepage and section landing page is reachable from the global header and local navigation.

The page structure and what local header belongs to each remains the same, breadcrumb as dropdown was the only element removed. Here is a diagram with more notes

![image](https://github.com/WordPress/wporg-mu-plugins/assets/895819/ff2dfd8f-661e-4c27-b6d2-33e6609591c5)

And here are the big picture per level type you can find in [i3 page](https://www.figma.com/file/VO03eHjoYJrX1aLisReB8q/Simpler-navigation?type=design&node-id=943-4841&mode=design) in the Figma file.

### L1A

![L1A](https://github.com/WordPress/wporg-mu-plugins/assets/895819/72718daf-5d40-492e-99a0-faa2ebe35363)

### L1B

![L1B](https://github.com/WordPress/wporg-mu-plugins/assets/895819/e0409cdf-f638-4d3e-adbe-0ecebd7bb2ac)

### L2A

![L2A](https://github.com/WordPress/wporg-mu-plugins/assets/895819/95745b9d-cfd0-48ba-b69f-e6cef01f66f9)

### L2B

![L2B](https://github.com/WordPress/wporg-mu-plugins/assets/895819/e7dba182-4520-4c11-8c63-334e646d6392)

### L3

![L3](https://github.com/WordPress/wporg-mu-plugins/assets/895819/a1f87ea9-1ece-4892-a17a-25fd3ed891d3)

**Comment by fcoveram** [comment]
As reported by @ryelle in this comment, the design above doesn't properly address showing local nav links on middle breakpoints. The remaining space stacks up the row and breaks down the layout.

I'm drawn to the following idea as it behaves like a transition towards the full-size menu in small screens

![Before and after of menu hidden in dropdown at 782px screen](https://github.com/WordPress/wporg-mu-plugins/assets/895819/bbaa234e-2682-4e3c-8206-4759cb1a3f04)

My question here is whether it is possible to detect when the links row overlaps the section name link to shift to this design. As you can see below, not all sections face this problem.

![Mockups showing the local nav at 782px screen](https://github.com/WordPress/wporg-mu-plugins/assets/895819/8aac6853-908e-460c-8621-3f75f7a75f37)

**Comment by ryelle** [comment]
> My question here is whether it is possible to detect when the links row overlaps the section name link to shift to this design. 

Maybe? It's possible, but I don't know if it would create too many edge-cases. It's worth exploring though. If it doesn't work, we could probably use different fixed breakpoints for each different site though, like Documentation drops to the chevron at <900px, but About stays with the 600px default.

I think we've got a good path here, and the next step is to start building so we can see if any other issues shake out.

**Comment by fcoveram** [comment]
> …we could probably use different fixed breakpoints for each different site though, like Documentation drops to the chevron at <900px, but About stays with the 600px default.

I like this idea

> …the next step is to start building so we can see if any other issues shake out.

I will clean up the [Figma file](https://www.figma.com/file/VO03eHjoYJrX1aLisReB8q/Simpler-navigation?type=design&node-id=0-1&mode=design&t=kKPBOyjHpEHEdwZA-0) and put all mockups and components in the "Design" page.

**Comment by fcoveram** [comment]
The [designs are ready](https://www.figma.com/file/VO03eHjoYJrX1aLisReB8q/Simpler-navigation?type=design&node-id=1%3A2193&mode=dev). I added a few notes to convey the style specs accurately.

**Comment by ryelle** [comment]
I'm trying to roll out the changes incrementally, so here's a status update:

On production:
- The breadcrumb updates are deployed, they should not wrap, instead they'll scroll offscreen
- The site title appears on scroll on Level 1 pages now, and multiple items can be in the "site title" section (code is on production, but site templates need to be updated)

In review:
- https://github.com/WordPress/wporg-mu-plugins/pull/573 — update the navigation code to collapse the menu to fit on one line
- https://github.com/WordPress/wporg-developer/pull/500 — update the templates in Developer to use new variations

A design check on ^ would be good, though I'd like to get these merged before getting any detailed feedback - there are a few different blocks at play here, _and_ it will be easier for you to see it in action on production.

One thing I noticed while doing this was in L3 where the page title appears on scroll, it looks strange with the animation. In the Developer PR above, I've left it appearing all the time. What do you think?

https://github.com/WordPress/wporg-mu-plugins/assets/541093/37e0609f-2d08-484d-ae83-8c4e8ea4cc0e

**Comment by fcoveram** [comment]
> A design check on ^ would be good, though I'd like to get these merged before getting any detailed feedback - there are a few different blocks at play here, and it will be easier for you to see it in action on production.

Perfect. Looking forward to reviewing once merged.

> One thing I noticed while doing this was in L3 where the page title appears on scroll, it looks strange with the animation. In the Developer PR above, I've left it appearing all the time. What do you think?

I really like the animation. It's subtle and the transition effect does not caught big attention. But I'm open to hear other thoughts.

**Comment by ryelle** [comment]
> I really like the animation. It's subtle and the transition effect does not caught big attention. 

Personally, I think it's strange that the middle item stays still while the two around move & drop in. It worked when it was just the logo. Maybe the text could just appear, a fade-in with the same duration? But TBH I prefer all the text always visible, rather than having things changing on me.

**Comment by ryelle** [comment]
@StevenDufresne's review pointed out an issue with my approach here. In all the designs, there is a page title (`h1`) in the content on the homepage, so for the site title in the local nav bar, we can use a `p` tag. This is the same for desktop and mobile on almost all the sites, except Showcase. On showcase, the page title in content disappears, so the site title in the local nav bar needs to be an `h1`. This works now because the local-nav site title does not appear on desktop, so there is only ever one visible `h1`. Once we update this, the site title appearing on scroll on desktop will be invalid (there should be only 1 visible `h1`).

So my question, @fcoveram: Is this a pattern (of the page title in content disappearing on mobile) that will show up on other site designs? Should I account for it here, or could we simply work around it on showcase (likely by leaving the current behavior in place)?

**Comment by adamwoodnz** [comment]
I left some [feedback on the PR](https://github.com/WordPress/wporg-mu-plugins/pull/573#issuecomment-1942900942) regarding the site title being shown on the homepage:

Seems unnecessary to me to show the title on the homepage on tablet and mobile, especially as the local nav isn't sticky on those screen sizes, so it isn't visible once scrolled:

| Tablet | Mobile | Scrolled |
|-|-|-|
| ![developer wordpress org_(iPad)](https://github.com/WordPress/wporg-mu-plugins/assets/1017872/064132b6-68c0-44cb-bc2f-6cd91374dae8) | ![developer wordpress org_(Samsung Galaxy S20 Ultra)](https://github.com/WordPress/wporg-mu-plugins/assets/1017872/4a2651da-941d-4215-9c82-a53800174870) | ![developer wordpress org_(Samsung Galaxy S20 Ultra) (1)](https://github.com/WordPress/wporg-mu-plugins/assets/1017872/1d8fc2a8-87dc-481f-bbb9-9dd2bdc0cebf) |

**Comment by fcoveram** [comment]
> Is this a pattern (of the page title in content disappearing on mobile) that will show up on other site designs? Should I account for it here, or could we simply work around it on showcase (likely by leaving the current behavior in place)?

The logic here is:
* When page title ("Showcase", "News", "Documentation", etc) is in the cover area (just below local nav), then it's hidden in local nav.
* When page title is not in the cover area (like in About WordPress), then it's visible in local nav.

If you see Showcase, the same logic applies. On desktop, page title is only in cover area; whereas on mobile, it's in local nav. That's why [L1 has variant A and B](https://private-user-images.githubusercontent.com/895819/300877216-ff2dfd8f-661e-4c27-b6d2-33e6609591c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MDIyMTEsIm5iZiI6MTcwNzkwMTkxMSwicGF0aCI6Ii84OTU4MTkvMzAwODc3MjE2LWZmMmRmZDhmLTY2MWUtNGMyNy1iNmQyLTMzZTY2MDk1OTFjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQwOTExNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWMyYzYxOTdjNzlkM2FmNmFjN2U5MTI2ZTY1YTljYzI5MzUyMjI2ZjMwZmYwMDU1ZDllZDVkOWZhMzcxOWU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kB2E7yk2NXOFReLhq54rrS1Rg-GRmZvsaQSigDsLyzk).

The general approach of "show or hide" for the page title lies on reducing redundancy. That is also the reason of showing page title when scrolling down as in many pages you might have page title in local nav, breadcrumb, and main content area just by landing on the page.

**Comment by fcoveram** [comment]
To @ryelle's point

>  Maybe the text could just appear, a fade-in with the same duration? But TBH I prefer all the text always visible, rather than having things changing on me.

Fade-in with the same duration works for me. My other comment above mentions why we decided to hide page title before scrolling in certain cases.

**Comment by ryelle** [comment]
@fcoveram  I do understand the difference between the A/B variants. The question for Showcase (specifically) is that there's a technical issue with how we hide the page title on mobile (in content), which we don't do on the other sites that L1A. Will there be other sites that hide the site title in the page content (_not_ local nav) only on mobile?

> Fade-in with the same duration works for me. 

Okay, I'll get that updated and use that for https://github.com/WordPress/wporg-developer/pull/500.

**Comment by fcoveram** [comment]
Oh now I understand. Sorry for the confusion.

> Will there be other sites that hide the site title in the page content (not local nav) only on mobile?

Probably yes. Themes, Plugins and Patterns belong to the Extend group, and given that sites part of a group share design features, there are high chances of make a single content more predominant in the hero section on mobile.

**Comment by ryelle** [comment]
Quick status update: The local navs have been updated on Developer, About, Downloads (no change), Dev Blog, & the in-progress Pattern Directory.

Sites left:

- [x] Documentation https://github.com/WordPress/wporg-documentation-2022/commit/f24f28635c24de59dcf1e79b02c3188e6d5474f4
- [x] Rosetta: [News archive & posts](https://es.wordpress.org/news/) https://github.com/WordPress/wporg-main-2022/commit/04e156d129bf8bf8e3e281522fc27da560d5d933
- [x] Events — no change needed?
- [x] Showcase https://github.com/WordPress/wporg-showcase-2022/commit/9b057878ae29918a9d9c33dd6fa45eb8d3fa4125, https://github.com/WordPress/wporg-showcase-2022/commit/6694d2df0b9ce9fb4c5b1f2e3894a902deb56ba1
- [x] Forums — updated the site title on homepage, left the L2-pages alone
- [x] Themes — done as part of refresh
- [x] Patterns — done as part of refresh
- [x] Plugins — done as part of refresh

**Comment by adamwoodnz** [comment]
> Sites left:

I think we can do Forums in a future iteration when updating the breadcrumbs.

**Comment by adamwoodnz** [comment]
Regarding the separate section in the Learn local nav for My Courses, I've added a temporary styling solution until we support this properly in the local navigation block.

![Local nav](https://github.com/WordPress/wporg-mu-plugins/assets/1017872/265e3c92-2792-4494-96b3-e759c211fc1d)

Issue: https://github.com/WordPress/Learn/issues/2481
Commit: https://github.com/WordPress/Learn/compare/bfb44be95853...e74485b61109

**Comment by fcoveram** [comment]
Do you need me to create an issue for including the links related to the user account?

**Comment by adamwoodnz** [comment]
> Do you need me to create an issue for including the links related to the user account?

Yes please!

**Comment by fcoveram** [comment]
Sorry for being late @adamwoodnz, I created #621 introducing the idea.

**Comment by ryelle** [comment]
I think at this point all of the sites have been updated with this iteration of the local navigation bar styles. If anyone notices any pages that were missed, or are using the wrong L* layout, open a new issue in the respective github project.
