### ISSUE TITLE
Top nav is inconsistent on events.wordpress.org

### ISSUE THREAD

**Issue by jdevalk** [WordPress/wporg-mu-plugins#557]
**Describe the bug**

I personally find it confusing that the main nav changes color when I move from [wordpress.org](http://wordpress.org/) to [events.wordpress.org](http://events.wordpress.org/), and that Community is not highlighted in the menu when I’m on an Events page.

**Comment by jdevalk** [comment]
@ndiego Rocio told me to ping you here ;)

**Comment by askhellosatya** [comment]
Hey, @jdevalk you mentioned the wrong URL. It should be [events.wordpress.org](http://events.wordpress.org/) rather than [events.wordress.org](http://events.wordress.org/),

**Comment by jdevalk** [comment]
Fixed

**Comment by iandunn** [comment]
I moved this to the `wporg-mu-plugins` repo, since that's where the global header and footer blocks live.

I think the changing colors is an intentional part of the new series of designs, but @jasmussen can speak to that better than I can.

Related #515

**Comment by fcoveram** [comment]
The color change was intentional to highlight the content difference compared to other areas, such as "Learn" in the global header, where all internal pages will have a similar look and feel. But I agree that landing on this page should be more reachable from the menu, a change being addressed in #515

**Comment by iandunn** [comment]
It sounds like that addresses both of the issues, so I'm gonna go ahead and close this. Feel free to reopen if you'd like to discuss it more though.
