### ISSUE TITLE
Mobile menu not working correctly when browser window is resized

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-mu-plugins#56]
This is how the header currently behaves when I resize the browser window:

https://user-images.githubusercontent.com/65220155/148217309-8c8ffc76-f0fa-4c13-863b-6c4f5f80eea7.mp4

It should adopt its original responsive behaviour, with menu links showing or hiding as the window is resized, as it does when the menu button is not active:

https://user-images.githubusercontent.com/65220155/148218052-20959605-9073-4a69-837e-ed091b2bfad7.mp4

**Comment by iandunn** [comment]
That's Gutenberg's standard behavior. Do you think anyone will do that in practice?

**Comment by beafialho** [comment]
> Do you think anyone will do that in practice?

Yes, I think it can happen.
