### ISSUE TITLE
Update the breakpoint where the TOC turns into a button

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-mu-plugins#566]
After using the new redesign for a few weeks, I found that the breakpoint where the TOC turns into a button feels too narrow. 

On smaller browser windows, the article content gets quite narrow. Therefore, I propose we change the breakpoint from `1200px` to `1400px` (or perhaps something like `1350px`). Need some design feedback here. cc @fcoveram @marko-srb @jasmussen 

| Current design (1200px) | Current design (1199px)|
|-|-|
|<img width="1317" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/594115a9-9856-48eb-b9a7-6c3f3848f35b">|<img width="1313" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/e931099f-8b79-4626-ac06-2684298be3b1">|

| Proposed breakpoint (1400px) |
|-|
|<img width="1539" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/e849e105-feb3-4651-8bb1-1a649361a2eb">|

**Comment by jasmussen** [comment]
This is not a strong opinion, but I do think the current breakpoint can work, though I can also support the wider one. I wonder if @justintadlock might have a preference?

**Comment by marko-srb** [comment]
For me this suggestion is ok and feels valid to go with 1400 (with first eye test). But the old one also can work, it's not so big issue for me too. 

So, whatever feels best to you can work if you ask me. You can also gather feedback from Justin and Francisco to learn other preferences and then decide if easier.

**Comment by justintadlock** [comment]
Just ran some browser testing. I think we could do 1300 and keep the content at a comfortable level. 1200 is definitely too narrow.

At least for me, I usually have my browser window at around 1350, and I've felt good with the layout at that size.

**Comment by ndiego** [comment]
> Just ran some browser testing. I think we could do 1300 and keep the content at a comfortable level. 1200 is definitely too narrow.

Sounds good to me. Just figured we would nail this one down before a similar layout is applied to Documentation. Thanks all!
