### ISSUE TITLE
Mobile menu and search: inconsistent behaviour and visual refinement

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-mu-plugins#57]
Currently there are a few inconsistencies with the mobile menu that are critical for launch:

https://user-images.githubusercontent.com/65220155/148218743-fc3b0f9a-2544-467a-abe1-baf05bdcf07f.mp4

- [ ] If I have the menu open and click the Search icon, the search field doesn't show up. The way it should behave is: if I click a button, it should override the other.

- [ ] When the menu is open, its icon should then be replaced by the `Close x` icon.

Here's the intended behaviour:

https://user-images.githubusercontent.com/65220155/148219311-6ff042cf-0190-44d3-bf80-75e788901766.mp4

- [x] The search field should have `2px` radius

- [x] On Desktop, there's a tiny space between the icon and the search box that shouldn't be there:
<img width="375" alt="Captura de ecrã 2022-01-05, às 12 43 14" src="https://user-images.githubusercontent.com/65220155/148219501-dacb1c37-352b-4cba-bbce-5d7fbfe4881f.png">

**Comment by iandunn** [comment]
> have the menu open and click the Search icon

👍🏻   we probably need to add some JS to hook into the open actions for both menus, and close the other one. I'm not sure if Gutenberg provides hooks for those, but hopefully.


> ​The search field should have 2px radius

Do you mean a `border-radius` on the `input` field? That seems like a valid change, but I don't understand why it'd be critical for the launch. Can you help me understand that?

**Comment by beafialho** [comment]
> Do you mean a border-radius on the input field? That seems like a valid change, but I don't understand why it'd be critical for the launch. Can you help me understand that?

That's right, a border-radius on the input field is critical. In a redesign [details matter](https://uxmyths.com/post/712451083/myth-if-your-design-is-good-small-details-dont-matter), otherwise it looks unfinished and unpolished.

**Comment by iandunn** [comment]
I agree that *some* small things matter, but more so with UX impacts like that article cites. 

If your standard for "critical" includes having everything *visually* polished, that works for me, we just need to pick a launch date that reflects that.

**Comment by kellychoffman** [comment]
Bringing in additional designers to address this.

**Comment by ryelle** [comment]
> If I have the menu open and click the Search icon, the search field doesn't show up. The way it should behave is: if I click a button, it should override the other.

The search shows up, it's just hidden behind the menu. Opening one menu _should_ close the other (this is the bug). After almost explaining why we couldn't do this, I think I figured out a way 😆  See #97.

> When the menu is open, its icon should then be replaced by the Close x icon.

I can't replicate this, I'm seeing the close icon on both search & menu.
