### ISSUE TITLE
A scroll bar is displayed on the breadcrumb trail in the Rosetta site

### ISSUE THREAD

**Issue by t-hamano** [WordPress/wporg-mu-plugins#575]
I noticed that the breadcrumbs on the Rosetta site had an unnatural scrollbar.

The following is a screenshot on Windows OS, but it should be possible to reproduce it on MacOS as well by changing the scroll bar display settings.

![image](https://github.com/WordPress/wporg-mu-plugins/assets/54422211/644f63d1-087f-4be3-8e1b-c15de57af22e)

I think we probably need to change `overflow: scroll` to `overflow-x: auto`.

https://github.com/WordPress/wporg-mu-plugins/blob/a14fdd00695ba58dbc5b71a908780d9e7b92f537/mu-plugins/blocks/site-breadcrumbs/postcss/style.pcss#L14

**Comment by keyurptl** [comment]
I can reproduce this scroll issue in breadcrumb & query filter block both.

**For Breadcrumb:**  https://prnt.sc/Qw2_xIwRKPWw

**For Query Filter Block:** https://prnt.sc/bCAfnPLCwe8X

**Comment by keyurptl** [comment]
**Created PR:** https://github.com/WordPress/wporg-mu-plugins/pull/581

**Comment by t-hamano** [comment]
Hi @keyurptl,

A PR has already been submitted for this issue and appears to have been approved.

https://github.com/WordPress/wporg-mu-plugins/pull/576

**Comment by keyurptl** [comment]
@t-hamano 
I have Closed My PR.
