### ISSUE TITLE
Emoji replacement is running on the arrow in menu's

### ISSUE THREAD

**Issue by dd32** [WordPress/wporg-mu-plugins#578]
<img width="767" alt="Screenshot 2024-02-15 at 3 59 10 pm" src="https://github.com/WordPress/wporg-mu-plugins/assets/767313/c123bfd6-3591-43cc-91da-fc83399d3684">

<img width="1214" alt="Screenshot 2024-02-15 at 3 59 19 pm" src="https://github.com/WordPress/wporg-mu-plugins/assets/767313/0992dbad-0781-4389-b36b-91920a894166">

This is https://github.com/WordPress/wporg-parent-2021/issues/58 no longer applying, unsure why, but could be related to the aria-hidden callback.

The upstream fix has been applied, so we should be able to simply add `wp-exclude-emoji` to the entire nav menu now.

**Comment by ryelle** [comment]
I'm not seeing this right now, was it happening before Gutenberg was pinned, maybe?

**Comment by dd32** [comment]
This only happens on old browsers that need the Emoji replacement in the first place.

In this case, it's `Chrome Version 121.0.6167.160 (Official Build) (64-bit)` on Linux w/ XFce.
