### ISSUE TITLE
Hide Rosetta header search for initial launch

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#58]
The old Rosetta header doesn't have a search form, but the new global header does.

Some Rosetta subsites like `/support`, `/themes`, etc have their own search forms in the secondary header.

Should we disable the search in the primary header on Rosetta sites, to match the old header, or keep it? If we keep it, what content should be searched?

Search options:

* global w.org network (including main English sites) - `https://wordpress.org/search/do-search.php` regardless of which subsite you're on
* current rosetta site (e.g., when on `/support`, only `/support` would be searched)
* main rosetta site (e.g., when on `/support`, only `/` would be searched. the secondary header form could be used to search `/support`
* main and subsites (e.g., when on `/support`, it'd search `/`, `/team`/, `support`, etc)

**Comment by dd32** [comment]
Historically the Global Search has been excluded from rosetta sites, as one may expect it to search localised content, rather than the english content.

From a search perspective for non-English locales, a search that doesn't search their locale-specific data is pretty irrelevant.

I vote we hide it, until a better option comes forward for full site search.

**Comment by iandunn** [comment]
So that's basically the "main and subsites" option above? That makes sense to me 👍🏻

The first idea that comes to mind is using Google to search `{user query} site:{locale}.wordpress.org`, similar to how the English search works.

**Comment by dd32** [comment]
> So that's basically the "main and subsites" option above?

My vote was to exclude the Search block from the header entirely for localised sites, which is the current rosetta header functionality.

> The first idea that comes to mind is using Google to search {user query} site:{locale}.wordpress.org, similar to how the English search works.

If Google Custom Search worked in such a way that we could do this, now that w.org/search is a WP page, we could probably do just that - but AFAIK it would require us to create a specific search-engine instance for each locale.

I suggest:
 - We hide it for initial news launch for localised sites
 - Post launch we look at a custom GCS instance, or making the existing one domain-aware

**Comment by iandunn** [comment]
👍🏻

**Comment by ryelle** [comment]
The search was hidden in #105, and #89 is for adding a real search, so I think this issue can be closed.
