### ISSUE TITLE
Local navigation bar: Dropdown nav layout broken on mobile

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-mu-plugins#592]
Looks like this is a global issue with the local nav block CSS, because the navigation block no longer uses the `is-collapsed` class (see https://github.com/WordPress/gutenberg/commit/ad1c0b4c17269a67e06e740ce14971d2b276e792), none of [the CSS here](https://github.com/WordPress/wporg-mu-plugins/blob/ee4bad3d99f2d3ada70e94963df9dad3f3cdf5b0/mu-plugins/blocks/local-navigation-bar/postcss/style.pcss#L216) is applied anymore.

That class was the easiest way to target the menu when it was in the "chevron" state (whether that was because it was mobile screen size or the always-mobile version), removing it would apply that CSS to the inline menu too.

**Screenshot**

| Production (broken) | Expected |
|---|---|
|  ![Image](https://github.com/WordPress/wporg-mu-plugins/assets/541093/770cf739-7764-4596-b4a9-84d6ad7b63f4) | ![Image](https://github.com/WordPress/wporg-mu-plugins/assets/541093/e13709fa-6f88-4f46-8e4f-49c652862c19) |

**Comment by ryelle** [comment]
@adamwoodnz Are you actively working on this? I saw it was high priority & in progress in the Forums board (I used that card to create this issue, it applies to all the sites — my screenshot above is from Patterns).

**Comment by adamwoodnz** [comment]
> @adamwoodnz Are you actively working on this? I saw it was high priority & in progress in the Forums board (I used that card to create this issue, it applies to all the sites — my screenshot above is from Patterns).

I was not, thanks for fixing!
