### ISSUE TITLE
Global header/footer compat issues on make.w.org

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-mu-plugins#60]
On make sites, it looks like the theme expects the header to load Open Sans, so the fonts are broken (Open Sans is not loaded, it falls back to `serif` headings & `sans-serif` body).

<img width="1244" alt="Screen Shot 2022-01-03 at 5 47 09 PM" src="https://user-images.githubusercontent.com/541093/147988636-fd544d82-ae14-4c28-a559-e6522f1f6002.png">

Homepage - max width container is gone, fonts are all too big. container also missing on meetings page.

![Screen Shot 2022-01-06 at 17 15 21](https://user-images.githubusercontent.com/541093/148459856-fefa3a6d-cda5-4cc4-8d8e-e850c9327d76.png)

Header spacing is also off, and "get wordpress" button has underline

**Comment by dd32** [comment]
Re-opening this based on https://github.com/WordPress/wporg-mu-plugins/commit/d09415375bb57e4091d1303581e5028b6c2cd350 - It looks like `wp4-styles` theme support isn't enough or something.

See https://wordpress.slack.com/archives/C02QB8GMM/p1642056619063500

**Comment by ryelle** [comment]
I pushed https://github.com/WordPress/wporg-mu-plugins/commit/fe9bde9e250c3a73c3fc581f00d0a801e56224a9 to fix this, but realized it might break the work done in #62 — checking that out now.

**Comment by ryelle** [comment]
@dd32 I'm having trouble figuring out if broke anything— I can't sandbox planet or the codex, but looking at `/wp-json/global-header-footer/v1/header/planet`, it looks like the same files are output before & after. l don't see `wporg-style` & do see wp4.css, open sans & dashicons. Let me know if something's actually broken though.

**Comment by dd32** [comment]
I think that works too, I think I was incorrect in changing the priority to later, I thought it fixed the problem I was chasing, but caused another.
