### ISSUE TITLE
Styles of selected item and apply action in multiple selection flow

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wporg-mu-plugins#601]
The [design shared](https://github.com/WordPress/pattern-directory/issues/648#issuecomment-2031738949) for multiple-selection filter in [pattern-directory#648](https://github.com/WordPress/pattern-directory/issues/648) works correctly in Showcase. However, two styles are different than the designs.

## Filter applied

The style of the item selected shows a grey background that was thought only for the hover state.

## Apply button

After applying multiple filters, the popover in the search results page show the "Apply" button in its active style. Clicking on it does nothing

Here are images of current Showcase and design that work for both points.

| Screenshot from Showcase | Mockup from the [design file](https://www.figma.com/file/SQwX90pGxS0XlNTEyNhDRE/WordPress.org-Navigation?node-id=1005%3A595&mode=dev) |
|:---|:---|
| <img src="https://github.com/WordPress/wporg-mu-plugins/assets/895819/01908d02-5ad9-4c16-a82a-7ca81470bcd2"> | <img src="https://github.com/WordPress/wporg-mu-plugins/assets/895819/0c6aedee-28e9-4d4f-b0bb-58b6a7e50aba"> |

**Comment by ryelle** [comment]
> Apply button

We can't conditionally disable/enable Apply, because we don't track the selections that way. There's no way to differentiate between 3 items already selected, vs 2 already selected + 1 new — they're all just selected or not.

(mentioned in the PR https://github.com/WordPress/wporg-mu-plugins/pull/596)

> Filter applied

Okay, I can remove that from active 👍🏻  On both multi and single selects, right?

**Comment by fcoveram** [comment]
> We can't conditionally disable/enable Apply, because we don't track the selections that way.

Oh right. You already mentioned that before. Sorry.

> Okay, I can remove that from active 👍🏻 On both multi and single selects, right?

Yes.
