### ISSUE TITLE
Local Navigation: Fix dropdown caret alignment on mobile

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-mu-plugins#604]
This is a minor thing, but the dropdown caret in the local navigation should probably be aligned with the double-line "hamburger" icon in the primary navigation. 

| Current | Proposed | 
|-|-|
|<img width="497" alt="image" src="https://github.com/WordPress/wporg-mu-plugins/assets/4832319/7c1bf7e2-afbf-424e-85f6-393de0451150">|<img width="451" alt="image" src="https://github.com/WordPress/wporg-mu-plugins/assets/4832319/1847b148-c1f4-47d7-9964-c18bdf411c3d">|

cc @WordPress/meta-design

**Comment by jasmussen** [comment]
Yep, good eye!
