### ISSUE TITLE
Scrolling glitch when content is shorter than sidebar container

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wporg-mu-plugins#611]
Visit https://developer.wordpress.org/plugins/security/securing-output/ on desktop and attempt to scroll down.

A glitch occurs when the Chapter List reaches the top of the screen.

**Comment by coffee2code** [comment]
Reported here: https://meta.trac.wordpress.org/ticket/7647

**Comment by ryelle** [comment]
In the trac ticket, Otto mentioned that "the content does get width limited upon scroll. Chrome on Windows." — I was able to reproduce this on a smaller browser height (for example, 1200x800, on Chrome/Mac). This also appears to happen on longer pages too, but the size difference is less obvious (in the second set of screenshots, the content area went  from 752px wide to 672px wide). I don't know how it's related, but both issues seem to happen on scroll.

| Top of page | Scrolled |
|---|---|
| ![Image](https://github.com/user-attachments/assets/7c2c97d5-f216-40a0-9c73-71750ebadfeb) | ![Image](https://github.com/user-attachments/assets/1eefd853-9a54-48a0-ba1b-0e85101303f1) |
| ![Image](https://github.com/user-attachments/assets/e40185d0-c75c-4674-9136-adead934d80b) | ![Image](https://github.com/user-attachments/assets/fb083bd5-eac7-4cee-b91a-6b30c8a1e21a) |
