### ISSUE TITLE
Remove links to https://mercantile.wordpress.org/ on WordPress.org

### ISSUE THREAD

**Issue by joemcgill** [WordPress/wporg-mu-plugins#614]
Originally reported by [Dan Soschin](https://profiles.wordpress.org/dansoschin/) on https://core.trac.wordpress.org/ticket/61292.

> On WordPress.org, we have links to the Mercantile Store (swag store) located in the main navigation (About >> Swag Store) and the footer (4th column, 4th item).
> 
> The Mercantile store is currently closed and has no plans to reopen. (A separate discussion on that may occur in the future.) However, to support its closure, we should remove those two links to reduce inbound traffic.

Looks like [removing these lines](https://github.com/WordPress/wporg-mu-plugins/blob/4ab57d37d930c8b8526458fc510568d0fb0050f8/mu-plugins/blocks/global-header-footer/blocks.php#L577-L581) might do the job.

**Comment by adamwoodnz** [comment]
There are also links in the [About](https://wordpress.org/about) page navigation, which I will also remove, issue created: https://github.com/WordPress/wporg-main-2022/issues/443

![Screenshot 2024-05-27 at 9 50 47 AM](https://github.com/WordPress/wporg-mu-plugins/assets/1017872/a26a10c8-3693-4247-8f38-93749e621bcf)

![Screenshot 2024-05-27 at 9 51 00 AM](https://github.com/WordPress/wporg-mu-plugins/assets/1017872/85bb651f-f8fd-4737-937e-a490c914a5a9)

**Comment by adamwoodnz** [comment]
@WordPress/meta-design it's unfortunate that this leaves a hole in the footer links, anything we can do here?

![Screenshot 2024-05-27 at 10 31 31 AM](https://github.com/WordPress/wporg-mu-plugins/assets/1017872/2e12abf2-d349-46fe-91d6-a77111af1d87)

**Comment by adamwoodnz** [comment]
We have a redirect set up that takes visitors from https://wordpress.org/about/swag to the mercantile store, what should happen instead @dansoschin?

**Comment by jasmussen** [comment]
Last we curated there were many options we omitted for the sake of making room. The conversation is somewhere in the archive, but hard to find. Perhaps @thetinyl remembers?

**Comment by adamwoodnz** [comment]
I've removed the links while we wait for answers on the above.

**Comment by courtneyr-dev** [comment]
> @WordPress/meta-design it's unfortunate that this leaves a hole in the footer links, anything we can do here?
> 
> 
> 
> ![Screenshot 2024-05-27 at 10 31 31 AM](https://github.com/WordPress/wporg-mu-plugins/assets/1017872/2e12abf2-d349-46fe-91d6-a77111af1d87)
> 
> 

I suggest as soon as Make gets a redesign and this page gets some design help, we put in 

[HTTPS://make.wordpress.org/latest](HTTPS://make.wordpress.org/latest) there.

**Comment by thetinyl** [comment]
> Last we curated there were many options we omitted for the sake of making room. The conversation is somewhere in the archive, but hard to find. Perhaps @thetinyl remembers?

Oof. I tried digging around for this. Maybe it was [this issue](https://github.com/WordPress/wporg-mu-plugins/issues/364#issuecomment-1708576169)?

Based on how the links are organized, a couple of things that might fit there:

- [WP Briefing](https://wordpress.org/news/podcast/) 
- [Five for the Future](https://wordpress.org/five-for-the-future/)

@adamwoodnz @jasmussen For the About page, I'm not sure if it's bothersome to have a missing link in that last column. If so, some options we can throw in there are Events (although we link to Events everywhere so could be overkill) or the [WordPress Remembers](https://wordpress.org/remembers/) page (my personal preference).

**Comment by ndiego** [comment]
I would vote for [Five for the Future](https://wordpress.org/five-for-the-future/) both on the About page and in the Footer.

**Comment by jasmussen** [comment]
FFTF can work, though it increases the urgency of refreshing that page.

**Comment by DanSoschin** [comment]
> We have a redirect set up that takes visitors from https://wordpress.org/about/swag to the mercantile store, what should happen instead @DanSoschin?

Great question. (Apologies for delayed response as I've been on AFK.) I don't have an obvious answer as to where to direct folks that land on any swag page. Perhaps it would be ideal if we created a temporary page that said something along the lines of "The swag store is currently closed. We don't have an update on when it will reopen."

**Comment by adamwoodnz** [comment]
⬆️ Two new PRs open to address the missing header and footer links, and redirect.

Please leave feedback if you agree or disagree with either approach 🙏
