### ISSUE TITLE
Personal area in Local nav component

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wporg-mu-plugins#621]
Based on [wporg-theme-directory#55](https://github.com/WordPress/wporg-theme-directory/issues/55) report, I explored an idea for separating the links to pages related to user's personal area in the local nav.

The section uses the link style and includes a dot separator between public and personal area on desktop, and a menu section with white at 10% border on mobile. This idea aims to update all site sections where this case exist. As per my knowledge, the sections involved are: Learn, Themes, Plugins, and Patterns.

Below you can see how those sections would look like on desktop and the mobile version of Learn, and in [this section](https://www.figma.com/design/VO03eHjoYJrX1aLisReB8q/Simpler-navigation?node-id=1-2193&m=dev) the Figma mockups.

![Local nav with personal area on desktop and mobile](https://github.com/WordPress/wporg-mu-plugins/assets/895819/51b17e00-a068-4e0a-82f8-056b2d094fcd)

---

This change relates to the following tickets in one or another way.
* #535 
* [pattern-directory#692](https://github.com/WordPress/pattern-directory/issues/692)
* [wordpress.org#318](https://github.com/WordPress/wordpress.org/issues/318)

**Comment by ryelle** [comment]
I've added this by creating a `has-separator` helper class. Any nav item with that class will add a &middot; to the left (or right, on RTL sites).

This needs to be updated on the child sites, still.

- [x] Theme directory https://github.com/WordPress/wporg-theme-directory/commit/bb5b298e3969e7d9c2107802b56ae494a2b8990f
- [x] Pattern directory
- [x] Plugin directory
- [x] Learn (update to new class)

**Comment by ryelle** [comment]
This has been updated on all the relevant sites.
