### ISSUE TITLE
Global Header: hover effects

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-mu-plugins#63]
The global header items currently have just an horizontal line separating them from the submenus. Both the hovered link as well as its submenu should have a darker background color `#1C2024`, as below:

<img width="965" alt="Captura de ecrã 2022-01-10, às 10 43 39" src="https://user-images.githubusercontent.com/65220155/148753386-7c327628-4607-4dfc-a33e-fac2cfe4e6ea.png">

**Comment by ryelle** [comment]
@beafialho Is there a hover effect for the submenu items?

**Comment by beafialho** [comment]
@ryelle yes, submenu links should be underlined.

**Comment by ryelle** [comment]
@beafialho Should the main menu items also be underlined, or just the submenu items?

**Comment by ryelle** [comment]
These should all be fixed now 👍🏻

**Comment by beafialho** [comment]
@ryelle only the submenu items should be underlined. The main menu items should have a darker background, like this:

<img width="1206" alt="Captura de ecrã 2022-01-17, às 17 38 15" src="https://user-images.githubusercontent.com/65220155/149815892-aa5fb4e9-91b8-468e-8db2-55c449ac64e4.png">
