### ISSUE TITLE
Global header menus broken on Safari

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wporg-mu-plugins#632]
Reported in [Slack](https://wordpress.slack.com/archives/C02QB8GMM/p1719077627012289)

> Since the latest update to wordpress.org, the menus Extend, Learn, Community, and About do not work on Safari on my MacBook Pro, Safari Version 17.5 (19618.2.12.11.6) & MacOS 14.5 (23F79). They work on Safari on my iPhone and iPad. No problems with Chrome and Firefox. Clicking on the menus doesn’t do anything. I need to type in https://wordpress.org/plugins/ for example to get to the plugins as clicking on Extend doesn’t do anything. The behavior is like those menu elements don’t get triggered by mouse clicks.

**Comment by adamwoodnz** [comment]
Reproduced locally with Gutenberg 18.6, was not an issue with 18.4.1.

Production is running 18.6

**Comment by adamwoodnz** [comment]
On clicking the submenu I can briefly see `aria-expanded` become `true`, before it immediately becomes `false` again, so the click event is firing, but something is likely wrong with the interactivity API state.

**Comment by adamwoodnz** [comment]
[This change](https://github.com/WordPress/gutenberg/pull/62160) looks closely related

**Comment by adamwoodnz** [comment]
Pinned Gutenberg to 18.5.0 as a temp fix.

**Comment by luisherranz** [comment]
I've opened a PR with the fix:

- https://github.com/WordPress/gutenberg/pull/62800

**Comment by cbravobernal** [comment]
I've released [Gutenberg 18.6.1](https://wordpress.org/plugins/gutenberg/) with that fix.

**Comment by adamwoodnz** [comment]
18.6.1 has been deployed, looks good. Thanks all!

**Comment by ryelle** [comment]
If the GB update fixed this, can the issue be closed or is there something to follow up on?

**Comment by adamwoodnz** [comment]
Thanks for the reminder.
