### ISSUE TITLE
Main navigation bar: Make the logo bigger

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-mu-plugins#646]
The W logo in the main WordPress.org navigation bar serves both as a branding element for the project, and an anchor for navigating to the homepage. At 27x27px it's a tad small. Here's a proposal to scale that up to 30x30px to give it a little more presence.

<img width="1480" alt="before after" src="https://github.com/user-attachments/assets/88f14f3d-3940-4d5b-b98c-c2fce5b3568b">

Here's an overlay showing before / after (in blue):

![W symbol](https://github.com/user-attachments/assets/9c00358e-2e93-459a-a275-fb969b2b3f14)

Overall it's not that much larger, but it's enough to make it feel slightly more substantial. The mockups in WordPress/wporg-mu-plugins#647 also include this.

**Comment by fcoveram** [comment]
It would be good to include this change with the one proposed in ticket [wporg-mu-plugins#572](https://github.com/WordPress/wporg-mu-plugins/issues/572). The design in the latter already reflects this change and the component is ready for dev in the [Design Library](https://www.figma.com/design/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?node-id=4387-5634&m=dev).
