### ISSUE TITLE
Login/Register links, move to secondary navigation, remove adminbar

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-mu-plugins#647]
Now that the majority of sections across WordPress.org are updated, with a consistent header and secondary navigation bar, the sections of the site that—when logged out—show the WordPress adminbar, stand out. Those sections feature the adminbar **only to offer login and register links**, features which are not going to be relevant to the majority of visitors. The adminbar appearing causes both a layout shift, and gives undue prominence to links that are only situationally relevant to a minority of users:

* I want to create a list of favorite themes|plugins|patterns.
* I want to build and upload a theme|plugin|pattern.
* I want to contribute to documentation, or WordPress itself.
* I want to participate in the forums.
* Any combination of the above.

Here's a recent audit of sections that feature the adminbar, showing a ❌ next to the sections that still include it:

<img width="2121" alt="i2 before" src="https://github.com/user-attachments/assets/677c6cb0-8915-4cb1-b191-e212a79976a0">

From this audit, we can extract the following sections still showing the adminbar, purely to support login/register links:

* Themes
* Plugins
* Patterns
* Learn
* Forums
* Make & Make P2s
* Photos

For those pages, there appears to be plenty of room to simply add a "Sign-in" link to the secondary navigation toolbar, like so:

<img width="1480" alt="i2 key changes" src="https://github.com/user-attachments/assets/4ad5bdc4-dff5-4bab-9935-ffa3c6c68af7">

Doing so would both avoid the layout shift of the adminbar appearing or disappearing as you navigate across the site, and it would also make the sign in link secondary to the primary navigation, thus implying its context implicitly: _I can sign in here to submit a theme._

When you click "Sign in" you see this page:

![login](https://github.com/WordPress/wporg-mu-plugins/assets/1204802/2687c5f3-1b8d-43b7-a16e-e20274b8ca63)

On that page, if you click "Create an account" you see this page:

![register](https://github.com/WordPress/wporg-mu-plugins/assets/1204802/e8a5544d-6b96-4fe8-a9c2-3f40b55386b6)

Here's a full flow of the suggested changes:

![i2 flow](https://github.com/user-attachments/assets/0b5749a2-0dbd-4a3c-bcc4-4b672c190614)

Note, this flow includes the mockup for a refreshed login page (#241). That's a separate effort.

[Figma](https://www.figma.com/design/6KPZbXujMGDRWWDR5odjDE/WP.org-improvements-%2F-QA?node-id=1071-2970&t=LacX9ErYtqnZjabs-1).

When you are successfully logged in, show the adminbar across the whole site. Shown here, logged out, and in, for the Forums section:

<img width="1480" alt="i2 logged out and in alt" src="https://github.com/user-attachments/assets/42c36b71-a91b-4fe0-bb9b-9c1ff09fb5f5">

**Summary:**

* Remove the adminbar for logged out users on Themes, Plugins, Patterns, Learn, Forums, Make, Make P2s and Photos.
* Add the sign-in link in the secondary navigation bar on those same pages.
* When logged in, the adminbar should be present on every page of the site.

---

Issue updated Aug 21.

<details><summary>Previous version of this issue ↓</summary>

Doing a quick review of navigating across all sections of WordPress.org this morning, and noticing a jump in the top navigation for every page that shows the adminbar. It seems that in every case where the adminbar shows, it exists to surface the login and register links. Here are pages that show the adminbar for this reason.

News:

![news](https://github.com/WordPress/wporg-mu-plugins/assets/1204802/ba945188-ef3a-4bdd-a590-0f83d149b89d)

Themes:

![themes](https://github.com/WordPress/wporg-mu-plugins/assets/1204802/7c3d45f1-33eb-4f21-93bf-9e5b25987e23)

Plugins:

![plugins](https://github.com/WordPress/wporg-mu-plugins/assets/1204802/5885eb03-2d7d-4a1f-aad7-976704979737)

Patterns:

![patterns](https://github.com/WordPress/wporg-mu-plugins/assets/1204802/883d8696-56e6-49d8-9a1b-0c4965aa6b82)

Learn:

![learn](https://github.com/WordPress/wporg-mu-plugins/assets/1204802/60206db3-07f9-41cf-aab3-fefd2cd892c6)

Forums:

![forums](https://github.com/WordPress/wporg-mu-plugins/assets/1204802/45009b26-23f4-43c8-a493-e2333788fc68)

Make (both landing and all P2s):

![make](https://github.com/WordPress/wporg-mu-plugins/assets/1204802/707231d7-64a3-4cf1-9edf-d5c2f4a0a6df)

Photos:

![photos](https://github.com/WordPress/wporg-mu-plugins/assets/1204802/67efb6b0-e4d5-4865-ae79-1399c5c97d07)

FFTF:

![fftf](https://github.com/WordPress/wporg-mu-plugins/assets/1204802/e4699b72-a6b6-4037-9961-431de968f12c)

Also for reference, when you click "Log In" you see this page:

![login](https://github.com/WordPress/wporg-mu-plugins/assets/1204802/2687c5f3-1b8d-43b7-a16e-e20274b8ca63)

When you click "Register" you see this page:

![register](https://github.com/WordPress/wporg-mu-plugins/assets/1204802/e8a5544d-6b96-4fe8-a9c2-3f40b55386b6)

In all these cases, those login/register links exist in context of those pages either being editable by contributors, or places where people can submit themes patterns, or otherwise. Those are all page-contextual actions, however, which suggest hierarchically those links should exist in context of the page, rather than in context of _the site_ as they do when they are the first thing on the page. 

Outside of fixing the hierarchy, addressing the jump is especially important on mobile, where those buttons get extra prominence and height:

![mobile news](https://github.com/WordPress/wporg-mu-plugins/assets/1204802/21d96550-d98c-4227-afd4-6e133b69ab24)

**Suggestions**

* Can we remove the log-in links and adminbar from Five for the Future? It's not clear why it needs to be there at all.
* Move all login and register links into a secondary navigation bar. 

Mockup showing a single unified Log in/Register link:

<img width="1040" alt="login register links" src="https://github.com/WordPress/wporg-mu-plugins/assets/1204802/ca6c0ff8-d316-4827-97e5-cdd6cda64529">

This single link leans into WordPress/wporg-main-2022#241, which puts a "Register" link right on the login page that'll take you there:
<img width="960" alt="login-register-page" src="https://github.com/WordPress/wporg-mu-plugins/assets/1204802/de80c1b7-1bb2-4b31-93eb-d0bf84aed8e1">

</details>

**Comment by dd32** [comment]
> Can we remove the log-in links and adminbar from Five for the Future? It's not clear why it needs to be there at all.

Done. It's there because it's primarily for logged in users, as that's how you manage your pledge - but if you don't know how to login, probably not actively contributing.

**Comment by jasmussen** [comment]
Ah good note. To clarify, if you _are logged in_ it's okay to show the adminbar across all sections. And in fact ideally we show it across _all_ sections if you're logged in, so you don't get an inverse jump in that case of the adminbar disappearing.

**Comment by tobifjellner** [comment]
Is showing menu items like "my favorites" for not logged-in visitors desirable?

**Comment by jasmussen** [comment]
> Is showing menu items like "my favorites" for not logged-in visitors desirable?

I'd think so, yes, it makes clear a benefit you get from logging in. Besides, clicking Favorites if logged in, would take you to a screen prompting you to do that.

**Comment by ndiego** [comment]
I wonder if we could explore something similar to the [Amazon](https://www.amazon.com/) experience. 

<img width="493" alt="image" src="https://github.com/user-attachments/assets/665add2e-f7dc-4293-952b-b2373a0ced1d">

The login/register is combined with more info revealed in a dropdown, and it's placed in the primary header. This is tricky with the Navigation block, but might be worth exploring.

**Comment by jasmussen** [comment]
I've updated this issue based on a fresh audit of the WordPress.org site after the recent string of style refreshes, then collaborated with @fcoveram to leverage the new secondary navigation bar for a simple and claer sign-in link that's contextual to the pages that need it.

It's a big win that improves an increasingly frustrating aspect of the new experience, so I added a high priority to it.

I also opened WordPress/wporg-mu-plugins#646 to make the logo bigger, which pairs well with this change now that we're in the same space, code-wise! Penny for your thoughts?

**Comment by keoshi** [comment]
Wondering what's the rationale behind the switch from the “Log in” expression to “Sign in”.

Especially inconsistent in this flow where a “Sign in” link leads to a log in page with a “Log in” action:


> When you click "Sign in" you see this page:
> 
> ![image](https://github.com/user-attachments/assets/796fab3a-a7e5-4457-9b80-5e96604d4dac)

**Comment by jasmussen** [comment]
Good point. "Log in" can work equally well. The motivation for "Sign in" was to simply emphasize the link a bit more.

**Comment by ryelle** [comment]
For the Photo Directory & Make sites, it looks like your screenshots are not using the current site, but the redesign mockups. Should those…

1. Wait for the redesign to apply, so they would keep the admin bar for now?
2. Remove the admin bar, add sign in to the current "local nav", with the caveat that Photo Directory doesn't have a local nav on the homepage.
3. Something else… (that isn't "do the redesign" 😅 )

These should be fine to update, no issues. It will require updating each theme, and disabling the Admin Bar plugin on each site.

- [x] Themes https://github.com/WordPress/wporg-theme-directory/pull/156
- [x] Plugins https://github.com/WordPress/wordpress.org/pull/368
- [x] Patterns https://github.com/WordPress/pattern-directory/pull/708
- [x] Learn https://github.com/WordPress/Learn/pull/2885
- [x] Five for the Future

----

These are lower priority or have other concerns

- [x] Forums https://github.com/WordPress/wordpress.org/pull/394
- [x] Make (currently being updated)
- [ ] Photos

> When you are successfully logged in, show the adminbar across the whole site.

We have some mu-plugins code which currently handles [hiding it unless you have permissions](https://github.com/WordPress/wporg-mu-plugins/blob/7a999b5b06cf9a708e69e9d34758339fb29299d3/mu-plugins/blocks/global-header-footer/admin-bar.php#L13-L23), but that can easily be updated.

**Comment by jasmussen** [comment]
Doing it on themes, plugins, patterns, learn and forums would be a big step forward. We migth be able to wait for refreshes of Make and Photos, to ask, how hard would it be to add the new secondary navigation bar to those? A rough sketch could look like this:

<img width="1475" alt="i2, headers, with the not-refreshed sites" src="https://github.com/user-attachments/assets/66b1648f-03a6-48c2-bf22-f78a6c7487d4">

Though I recognize those secondary bars would need to disappear when you're logged in. A hacky alternative (rough sketch) could be this:
<img width="1475" alt="i2, headers, with the not-refreshed sites alt" src="https://github.com/user-attachments/assets/4c0f664f-08bf-4b00-9d38-636aac87df3f">

Would either of those be feasible?

> We have some mu-plugins code which currently handles [hiding it unless you have permissions](https://github.com/WordPress/wporg-mu-plugins/blob/7a999b5b06cf9a708e69e9d34758339fb29299d3/mu-plugins/blocks/global-header-footer/admin-bar.php#L13-L23), but that can easily be updated.

The motivation is to remove the layout shift, so it'd be nice to show it across the whole site once logged in. That should also at least give you quick access to logging out, or editing your profile, even if you're on a page you don't have other permissions for.

Thank you for looking!

**Comment by ryelle** [comment]
> Would either of those be feasible?

The second option would be more likely than adding the local nav without any other redesign updates, especially for Make. But a nav banner might be possible on the Photo Directory, it just wouldn't do the scrolling behavior that the others do.

> The motivation is to remove the layout shift, so it'd be nice to show it across the whole site once logged in. That should also at least give you quick access to logging out, or editing your profile, even if you're on a page you don't have other permissions for.

Yes, I was saying we can do that.

**Comment by ryelle** [comment]
This has now been done on all the relevant redesigned sites, and is in progress for Make (half-done already, the logged out admin bar needs to be deactivated on all the sites) & Photos (will happen with the redesign). I'm going to close this issue, as it's not necessary for tracking anymore.
