### ISSUE TITLE
Teams with 2 language packs need a second download button or notice

### ISSUE THREAD

**Issue by timse201** [WordPress/wporg-mu-plugins#669]
The Dutch, German and Swiss teams are maintaining a second language package. As they only differ in the form of the address (formal/informal), we don't provide a second landing page. Therefore, we (+ the download page team) need a discussion about how we handle this and what is possible.

1. solution
Please add a second download button

2. solution
Add a notice that a second language pack is available for users to choose from within WordPress

@swissspidy @jeroenrotty @tacoverdo @remkus @ocean90 @Zodiac1978 @nickw108

**Comment by timse201** [comment]
wrong place sry

**Comment by tobifjellner** [comment]
There are a couple more: Serbian and Portuguese (Portugal) have variants for various spelling conventions. 
Technically, there are a couple of variants on Catalan, but at least Valenciano has been defined separately, too.
