### ISSUE TITLE
Make header stick to top on all sites

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#67]
right now it's only being done by the news theme, but the global header should have it even if there isn't a local header, or a container around the global header. 

maybe duplicating the markup should be moved from the theme templates to this repo, to make sure it's done consistently, and to make the templates less cluttered. cc @shaunandrews , since it sounds like you may have an alternative to double-markup hack

**Comment by ryelle** [comment]
Is the issue here that the header should be stuck to the top on all sites?

**Comment by iandunn** [comment]
yeah

**Comment by shaunandrews** [comment]
Over in https://github.com/WordPress/wporg-news-2021/pull/178 I used `position: sticky` along with `flex` to handle the positioning of the elements. I'm not sure how well that will work across all the w.org sites.

**Comment by iandunn** [comment]
Yeah, we should probably use the same method for consistency, and move the styles out of the theme for DRYness, if that's practical.

I'll make the title more generic
