### ISSUE TITLE
Footer menu glitch

### ISSUE THREAD

**Issue by pkevan** [WordPress/wporg-mu-plugins#673]
When viewing a menu with extended sub-menu depth, and only at certain browser height the following glitch occurs:

https://github.com/user-attachments/assets/b95bf4f7-1504-424c-9840-a072542a9934

It's reasonably hard to reproduce but seems to be when the sub-menu is higher than the content, and the browser hadn't triggered the menu to appear over the content.

Sorry there isn't much easily reproducible details!

**Comment by ryelle** [comment]
This has also been reported at #611.
