### ISSUE TITLE
desktop, patterns: hover on search icon, blue line between menu and search box. happens on most classic themes, if not all

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#72]

**Comment by dd32** [comment]
Is this the gap you're referring to?

I see it more often on classic themes, but also at certain zooms on the news blog.

It appears that `<header>` is `99.453px` high, and the search box is offset at 100px, depending on your screen resolution, zoom, and other system settings, it seems to round up/down leaving a few px gap.

<img width="1212" alt="Screen Shot 2022-01-12 at 6 19 33 pm" src="https://user-images.githubusercontent.com/767313/149089871-3948adf5-4119-4071-9651-b99fde6e8f10.png">
 
<img width="1081" alt="Screen Shot 2022-01-12 at 6 21 27 pm" src="https://user-images.githubusercontent.com/767313/149090197-faa14b10-16ed-417a-a3e3-36985a42011f.png">

**Comment by iandunn** [comment]
Yeah, that's what I was referring to 👍🏻
