### ISSUE TITLE
mobile, patterns/learn: Header & footer use Open Sans instead of Inter

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#74]
mobile, patterns/learn: search "search" font and spacing different from news-test.
maybe classic theme styles overriding?
maybe header styles added to news theme instead of this repo? font looks like being overridden by learn theme b/c targets any `label` tag, probably update learn css to be more targeted

**Comment by ryelle** [comment]
The root styles to use Inter are set in News, but are not carried over to this project. (I don't know why I keep thinking it's system fonts 😅 )

**Comment by ryelle** [comment]
Spacing will be fixed by #79
