### ISSUE TITLE
translate.w.org social icons aren't on the same line

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#78]
this happened before because the `wp-container-{hash}` styles weren't being output, but that was fixed by f5835d2

<img width="1039" alt="Screen Shot 2022-01-11 at 5 03 46 PM" src="https://user-images.githubusercontent.com/484068/149045509-e227ede0-29f8-45dc-8717-a76bcdb523ee.png">

- [x] initial fix
- [x] [move `gp_head()` back inside `<head>`](https://github.com/WordPress/wporg-mu-plugins/issues/78#issuecomment-1013224630)
- [x] [get `wporg-main` working on old site, or flip during launch](https://github.com/WordPress/wporg-mu-plugins/issues/78#issuecomment-1013224630)?

**Comment by iandunn** [comment]
That is happening because:

1. the `ul` doesn't have `display: flex`, which is because...
2. the `wp-container-{hash}` styles from `gutenberg_render_layout_support_flag()` aren't output, which is because...
3. that function [hooks them to `wp_footer`](https://github.com/WordPress/gutenberg/blob/3f43af06db0b017bc09124f1ca99ed89d16cb471/lib/block-supports/layout.php#L170-L175), but that's not called in glotpress, which is because...
4. GP ignores the activated theme and uses it's built-in one instead. only `gp_footer` is called, not `wp_footer`

I suspect [the `view.min.js` issue](https://github.com/WordPress/wporg-mu-plugins/issues/44) is a similar problem w/ `wp_enqueue_script()` vs `gp_enqueue_script()`.

I'm thinking of doing something like the following, but it's obviously a fragile hack.

```php
global $wp_filter;
foreach ( $wp_filter['wp_footer'][10] as $callback ) {
	$reflected          = new \ReflectionFunction( $callback['function'] );
	$is_layout_file     = false !== strpos( $reflected->getFileName(), 'block-supports/layout.php' );
	$has_style_variable = isset( $reflected->getStaticVariables()['style'] );

	if ( $is_layout_file && $has_style_variable ) {
		add_action( 'gp_footer', $callback );
	}
}
```

@ryelle , @dd32, @ocean90  : Do any of y'all see a better way?

**Comment by dd32** [comment]
Another aspect of this is that GlotPress doesn't accept that scripts/styles might be printed in the footer (Which might be why view.min.js isn't loading?) as it only [adds head-related hooks ](https://github.com/GlotPress/GlotPress-WP/blob/f55ca5a9cde6ee50902e6202ad6f3ed8b8c6ace4/gp-includes/default-filters.php#L18-L21).

At least on WordPress.org, I think the solution is to drop the GlotPress header/footer calls, and hook them to the WordPress actions instead. It would mean some hackery, but I feel like it's likely to be less hackery than the above.
https://github.com/GlotPress/GlotPress-WP/issues/8 is the upstream GlotPress ticket for migrating away from the GlotPress specific template structure.

**Comment by iandunn** [comment]
Yeah, that does sound better. I think it might also help to create a blank/empty theme, and activate that on translate.w.org, so that TwentyFifteen scripts/styles aren't enqueued.

I'll play around w/ all that.

**Comment by iandunn** [comment]
We'll probably need to revert part of those two commits, and move `gp_head|footer()` back to `classic-header|footer.php`, so that they get output inside `<head>`.

I guess the footer could still be in GlotPress templates, but then it wouldn't be consistent 🤷🏻 

We also had to re-enable TwentyFifteen for the current site, so that will need to be addressed. One option might just be to swap the theme when we launch the new header.

**Comment by ryelle** [comment]
Is the issue here still the social icons? Because I see a lot more wrong right now:

![Screen Shot 2022-01-14 at 17 41 18](https://user-images.githubusercontent.com/541093/149594656-e9bf95f3-c927-4ce8-957c-f04ae94a578b.png)

**Comment by iandunn** [comment]
That's because TwentyFifteen was reactivated, and its stylesheets are enqueued again. I'm working on it now.
