### ISSUE TITLE
Profiles header/footer missing styles, footer laid out in sidebar

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#81]
Maybe similar issue to #78 but w/ BuddyPress instead of GlotPress

- [x] pull header/footer from rest api
- [x] need to call `wp_head()` and output inside `<head>`
- [x] minor differences in spacing
- [x] footer laid out in sidebar
- [x] mobile search input margin different
- [x] mobile menu item spacing different
- [x] account for admin bar not being present

**Comment by dd32** [comment]
https://meta.trac.wordpress.org/changeset/11436 may help here - specifically `body.wporg-responsive .wp-block-group.global-footer { clear: both }`.

The old footer styles had a clear, which the older themes are expecting.

I didn't realise profiles was affected too, so droping the `body.wporg-responsive` part from that wp4 style might work.

**Comment by iandunn** [comment]
👍🏻  thanks! I'll play around w/ that.

**Comment by dd32** [comment]
> droping the body.wporg-responsive part from that wp4 style might work.

Did that for Trac support too. https://meta.trac.wordpress.org/changeset/11441

**Comment by iandunn** [comment]
Thanks :)

**Comment by iandunn** [comment]
Fixed by 00afe59 and `r18316-dotorg`
