### ISSUE TITLE
`Get WordPress` button should be wide width

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-mu-plugins#83]
| Test Site | Mockup |
| --- | ----------- |
| ![IMG_8734](https://user-images.githubusercontent.com/65220155/148379159-19b1d14e-db55-4c24-bed0-8d23c2d82707.PNG) | <img width="400" alt="Captura de ecrã 2022-01-06, às 11 55 31" src="https://user-images.githubusercontent.com/65220155/148379358-d40d89e3-7001-4871-b5bd-d9e09f07af21.png"> |

**Comment by ryelle** [comment]
Fixed in #84
