### ISSUE TITLE
Classic themes: Double global styles

### ISSUE THREAD

**Issue by dd32** [WordPress/wporg-mu-plugins#86]
It looks like for classic themes, we now have two copies of the global styles being output

```
$ curl -s https://test.wordpress.org | grep -B1 -E 'body{--wp--preset--color--black'

<style id="global-styles-for-classic-themes">
	body{--wp--preset--color--black: #000000; ....
</style>
--
<style id='global-styles-inline-css' type='text/css'>
body{--wp--preset--color--black: #000000; .... </style>
```

**Comment by ryelle** [comment]
I checked into this and it appears to only be setting the defaults twice, so we don't need to worry about style conflicts - so this can stay as a post-launch fix 👍🏻

**Comment by ryelle** [comment]
This is causing the `--wp--preset--font-size--small` value to be overwritten with the core default of 13px, rather than our value of 14px, which is a problem now that we're using this value in the header menu (#131).
