### ISSUE TITLE
`current-menu-item` assigned to Make on Translate

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#91]
Open https://translate.wordpress.org/ w/ the flag enabled, and you'll see Get Involved as the current item.

https://github.com/WordPress/wporg-mu-plugins/blob/677e0ece827c5df9a74066af9f9ebd893edecb04/mu-plugins/blocks/global-header-footer/blocks.php#L765-L767

```php
var_dump( $sub, $current_url, $item['url'] );
```

```
false

'https://make.wordpress.org/' (length=27)

'https://make.wordpress.org/' (length=27)
```

**Comment by dd32** [comment]
This was intended (from me) based on the behaviour of the existing menu. I'm okay to pull it out though. It might make more sense to find a home for these other URLs in the menu structure.

https://github.com/WordPress/wporg-mu-plugins/blob/677e0ece827c5df9a74066af9f9ebd893edecb04/mu-plugins/blocks/global-header-footer/blocks.php#L780-L789

**Comment by iandunn** [comment]
Ah, I missed that, and assumed it was a bug w/ the loops. It makes sense now 👍🏻
